### ISSUE TITLE
Is it possible to perform ReID on a multi-camera setup where the target exits the FOV of one camera and enters another?

### ISSUE THREAD

**Issue by PiDGMT** [mikel-brostrom/Yolov5_StrongSORT_OSNet#370]
I would like to know if it is possible to add to the bounding box if the person (class 0) has been detected before if a new shot (different perspective camera) is presented. 
So I have a video of a person walking in one angle, but the same person has a different tracking ID in the next, but I would like to know if the person has been detected before.
Could this be done?

**Comment by mikel-brostrom** [comment]
Sure. Check the track's `state`.

https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/tree/master/deep_sort/sort/track.py

Append the state to DeepSort's output and use it to extend the string that get printed with the bbox to show whether it
is a new track or not

**Comment by PiDGMT** [comment]
Thank you for your response! What else does the state say than Tentative/Confirmed/Deleted? I basically just want it to give a person an ID as well and if that person reappears later it's a new track but the same ID.

I appended the state but that doesn't seem to do anything except adding '2' to the bbox

**Comment by mikel-brostrom** [comment]
I revisited your question. Sorry for my previous response.  I made very little sense.

This functionality is being worked on. Each stream share the Yolov5 model but not the DeepSORT model. This means that each stream has its individual DeepSORT instance which makes it impossible to re-identify a person from different cameras perspectives at the moment

**Comment by jyothirrose** [comment]
i sthere any solution to this issue?

**Comment by PiDGMT** [comment]
Thank you for your response Mikel.

Right now I'm performing the re-identification for cross camera streams afterwards on the saved crops to connect similar tracks with a model trained specifically for that, and using time constraints (two tracks occuring at the same time can't be the same person, assuming no track switch etc.) This works fairly well, but might be a little cumbersome.  

You mentioned that this is a functionally that's being worked on, how are you planning on making this work? I'd like to look into it as well.
Thanks!

**Comment by mikel-brostrom** [comment]
> You mentioned that this is a functionally that's being worked on, how are you planning on making this work?

I think it could be as easy as offsetting the location of each track by the (width, height) of the camera. In that way, each track associated to a camera stream would not interfere with any track from other camera feeds and the same DeepSORT module could be used for all the streams.

> You mentioned that this is a functionally that's being worked on, how are you planning on making this work?

I have been spending most of my time implementing StrongSORT lately (https://arxiv.org/pdf/2202.13514.pdf). But feel free to try my suggestion, or try your own and leave PR.

**Comment by jyothir07** [comment]
It seems Re-identifying across multiple cameras is not solved yet.
