### ISSUE TITLE
In my project, I found a small problem in the program，TypeError: endswith first arg must be str or a tuple of str, not list

### ISSUE THREAD

**Issue by songjiahao-wq** [mikel-brostrom/Yolov5_StrongSORT_OSNet#380]
VID_FORMATS parameters are a list, not the tuple required by the ENDSWITH functio
![1650964779(1)](https://user-images.githubusercontent.com/75210061/165267647-9211ec3f-0eb1-4274-9ff8-d6847a4ce469.png)

**Comment by mikel-brostrom** [comment]
This works on Linux. I don't own a Windows machine so cannot reproduce his error. Maybe somebody else could help out here...

**Comment by Diva-Mio** [comment]
Can you check variance "VID_FORMATS" in datasets.py ?
I checked it is tuple of str.

**Comment by leijobs** [comment]
I got same error in Linux, and you can just make the if-else into annotations will be OK. This part is different from YOLOV5 version6.1, so you just compare and make it.
`if source.endswith(VID_FORMATS):
                    txt_file_name = p.stem
                    save_path = str(save_dir / p.name)  # im.jpg, vid.mp4, ...
                # folder with imgs
                else:
                    txt_file_name = p.parent.name  # get folder name containing current img
                    save_path = str(save_dir / p.parent.name)  # im.jpg, vid.mp4, ...`
into this
`# if source.endswith(VID_FORMATS):
 txt_file_name = p.stem
 save_path = str(save_dir / p.name)  # im.jpg, vid.mp4, ...
                # folder with imgs
                #else:
                    # txt_file_name = p.parent.name  # get folder name containing current img
                    # save_path = str(save_dir / p.parent.name)  # im.jpg, vid.mp4, ...`

**Comment by mikel-brostrom** [comment]
I revisited this specific part of the code @leijobs, @songjiahao-wq, @Diva-Mio. Can you confirm that it works now?

**Comment by songjiahao-wq** [comment]
> 

I solved it through a simple modification
![image](https://user-images.githubusercontent.com/75210061/172153814-dc8a05ed-b7a5-4490-bf6e-d464601b8989.png)
![image](https://user-images.githubusercontent.com/75210061/172153896-291e8cab-6fbc-4df7-8f99-93f886debea9.png)

**Comment by Wubl-cy** [comment]
> > 
> 
> I solved it through a simple modification ![image](https://user-images.githubusercontent.com/75210061/172153814-dc8a05ed-b7a5-4490-bf6e-d464601b8989.png) ![image](https://user-images.githubusercontent.com/75210061/172153896-291e8cab-6fbc-4df7-8f99-93f886debea9.png)

hey,I meet the say problem.could you please give me some details about this. thanks

**Comment by Wubl-cy** [comment]
> > > 
> > 
> > 
> > I solved it through a simple modification ![image](https://user-images.githubusercontent.com/75210061/172153814-dc8a05ed-b7a5-4490-bf6e-d464601b8989.png) ![image](https://user-images.githubusercontent.com/75210061/172153896-291e8cab-6fbc-4df7-8f99-93f886debea9.png)
> 
> hey,I meet the say problem.could you please give me some details about this. thanks

thans. I have solved the problem through your method
