### ISSUE TITLE
How to do human head re-identification？Does reid need to retrain the human head

### ISSUE THREAD

**Issue by Yekaiii** [mikel-brostrom/Yolov5_StrongSORT_OSNet#401]
I know the crowdhuman_yolov5m.pt can do head detection. And this project can also track the human head target. But I cannot find any human head datasets of reid.

**Comment by mikel-brostrom** [comment]
You would need to create your own dataset from scratch. Mostly because you probably want to have high resolution faces to train on for re-identification. There is none publicly available what I know

**Comment by cxbrooks** [comment]
I'm just starting out with all of this, but I did find a model for yolo11 that does facial detection at https://www.kaggle.com/code/emmanuelmess/yolov11-retrain-for-face-detection/
I'm not sure if that model is sufficient for re-identification.
