### ISSUE TITLE
Load Yolov5_DeepSort_OSNet from PyTorch Hub

### ISSUE THREAD

**Issue by ThomasCochou** [mikel-brostrom/Yolov5_StrongSORT_OSNet#407]
YOLOv5 could be used very easily with PyTorch Hub.
Will Yolov5_DeepSort_OSNet in the future simplify is use ?
I don't know how to use it inference simply in my program.
Thanks for your work :)

**Comment by mikel-brostrom** [comment]
This wouldn't simplify the repository's use in any way. Most of the code surrounding the tracking isn't neural network related. This means that you would not be able to do something like:

```python
import torch
# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
# Images
imgs = ['https://ultralytics.com/images/zidane.jpg']  # batch of images
# Inference
results = model(imgs)
```

and expect the tracker to work. The association process is more complex and you need frame feeding as well which
make this repo not so PyTorch Hub friendly.
