### ISSUE TITLE
Dose it Handle the Occlusions ?

### ISSUE THREAD

**Issue by bwithai** [mikel-brostrom/Yolov5_StrongSORT_OSNet#408]
can we visualize the kalman filter prediction as to show that it can handle the occlusions ? like

**From #774 to #792 in img**

![Occlusions](https://user-images.githubusercontent.com/76056239/171910485-e37eb893-ebb3-4652-8d10-4f5630b30b33.png)

**Comment by mikel-brostrom** [comment]
The Kalman Filter predictions is only one part of the ID matching algorithm. It also uses visual appearance information for re-ID after occlusion. So, make KF predictions ahead during occlusion is not absolutely necessary for successful re-ID as the visual appearance information covers for that. However, if you still want to make predictions ahead during occlusion check: https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/issues/368

**Comment by bwithai** [comment]
Thanks for your kind replay. Now I understand this better.

**Comment by bwithai** [comment]
Hi @mikel-brostrom hope you will be doing well 

my tracking camera move accordingly as object moves to track the obj lets it (person) suddenly occlusion appear.
> I want to track the velocity of the object in occlusion and move on prediction that it might be moving (focus on not miss the enemy). camera is placed on gun.

**Explanation of 1, 2, 3**

1. camera track the person at (1) and moving accordingly as object move but,
2. at point (2) occlusion appear detection loss and object keep moving,
3. at point (3) we loss the object 

![ask_question](https://user-images.githubusercontent.com/76056239/172991016-97264d38-e347-4f8b-a04b-1e71e1304ef7.png)

Please give your precious time sincerely

**Comment by bwithai** [comment]
@mikel-brostrom Please have a look if you have time thanks

**Comment by bwithai** [comment]
@mikel-brostrom, @gkeechin, @Borda, @hdnh2006 
Hi hope you will be doing well, please just give the direction as it possible or not.

initially my camera track the bbox vertices through arduino when no detection it will never move so please help me (read the above image from reopen issue for better understand what i mean), how can i force the camera to move accordingly by predicting kalman filter assumption please help.
