### ISSUE TITLE
Multi -video flow reasoning ends with short video

### ISSUE THREAD

**Issue by songjiahao-wq** [mikel-brostrom/Yolov5_StrongSORT_OSNet#409]
I have encountered a problem now. When reasoning multiple video streams, such as 1 minute, 10 minutes, and cameras, the reasoning will end with 1 minute video, not all reasoning。This is the reasoning source I set up。Hope someone helps me
![1654306085(1)](https://user-images.githubusercontent.com/75210061/171971367-9afc93a4-b761-4749-962e-2eaaa4a71b7f.png)
。

**Comment by mikel-brostrom** [comment]
The tracking stops whenever any source ends.
