### ISSUE TITLE
How to save images?

### ISSUE THREAD

**Issue by RubyRose-TAT** [mikel-brostrom/Yolov5_StrongSORT_OSNet#415]
It should work with images now as well. I don't understand however why you would run it on an individual image...

_Originally posted by @mikel-brostrom in https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/issues/400#issuecomment-1148649453_

How to save the image？

**Comment by mikel-brostrom** [comment]
First of all, the tracker needs a few frames to confirm a new track, by default 3 frames. Hence, the results will be empty for a single image. Moreover, the results are not saved as an image but as an mp4. If you still want a single frame mp4 with no results file you can run the tracker with the `--save-vid` flag
