### ISSUE TITLE
track other object?

### ISSUE THREAD

**Issue by Naughty-Galileo** [mikel-brostrom/Yolov5_StrongSORT_OSNet#416]
When I want to track other objects, how to use only yolov5+deepsort without OSNet?

**Comment by mikel-brostrom** [comment]
If what you mean is that you want to disregard the visual appearance descriptor, then set lambda here:

https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/blob/84494fe6ca7330e90ac75839752508fe78b350a3/deep_sort/sort/tracker.py#L38

to 1

**Comment by Naughty-Galileo** [comment]
> 

Thanks!

**Comment by Naughty-Galileo** [comment]
I would like to ask one more question. Deepsort is particularly slow, and I want to deploy to xavier. how can I improve the speed?

**Comment by Naughty-Galileo** [comment]
1.3ms pre-process, 13.2ms inference, 4.2ms NMS, 57.1ms deepsort

**Comment by mikel-brostrom** [comment]
OSNet models are particularly slow due to their multi-stream design. Try with: `--deep-sort-weights mobilenetv2_x1_4_msmt17.pt`

**Comment by Naughty-Galileo** [comment]
> OSNet models are particularly slow due to their multi-stream design. Try with: `--deep-sort-weights mobilenetv2_x1_4_msmt17.pt`

I will try, thanks a lot!
