### ISSUE TITLE
I'd like to count with custom model

### ISSUE THREAD

**Issue by BenzKukkik** [mikel-brostrom/Yolov5_StrongSORT_OSNet#423]
Dear,

I try to use your Yolov5 Deepsort Pytorch for my custom model. I got a weight file from my trained name as "[best.pt](http://best.pt/)" but I don't know how to replace your DeepSort.

Please recommend it to me.
Thank you very much for supporting me.

**Comment by BenzKukkik** [comment]
I already trained with Yolov5. Can I use? or I have to train on OSNet on a custom Re-ID

**Comment by mikel-brostrom** [comment]
> or I have to train on OSNet on a custom Re-ID

As I already said, ideally yes. You would get better results by training OSNet on your custom data. But try with the default OSNets provided by this repo, in this way you will see whether they are enough for your use-case or not.
