### ISSUE TITLE
No module named 'utils.dataloaders' (after updated clone link)

### ISSUE THREAD

**Issue by zohaib-khan5040** [mikel-brostrom/Yolov5_StrongSORT_OSNet#425]
![image](https://user-images.githubusercontent.com/67925902/173572381-5ae42117-5d83-4707-b27f-c00d19c04997.png)

This issue persists after cloning with the link provided in issue #411

**Comment by LudvigKnast** [comment]
I had the same problem when I was using python 3.10 so I changed to 3.7 and it worked fine...

**Comment by zohaib-khan5040** [comment]
This worked, along with a fix to the parser args for --name
Thank you so much!

**Comment by sivaji123256** [comment]
> This worked, along with a fix to the parser args for --name Thank you so much!

Hi @zohaib-khan5040 ,I was also facing the same issue while trying to use latest yolov5 trained weights for tracking .Can you explain me in details you have resolved it ?
