### ISSUE TITLE
Counting objects & displaying only boxes

### ISSUE THREAD

**Issue by zohaib-khan5040** [mikel-brostrom/Yolov5_StrongSORT_OSNet#428]
I've trained a model to detect only one class of cattle. 
I'd also like to display the count of the object in a corner of the video window.  
Can someone please guide me as to how I can accomplish this (by passing some argument or modifying a script)?
Also I'd like to hide the confidence labels and *just* show the bounding boxes. When I pass `--hide-conf True` there is a parsing error. Can someone suggest a fix (I only want to display the bounding boxes)?

**Comment by mikel-brostrom** [comment]
I just enabled all the hide flags in my last update.

Use the `--hide-labels` args in this way:

`python3 track.py --hide-labels`
