### ISSUE TITLE
Question about multi rtsp streams

### ISSUE THREAD

**Issue by vishyVishal** [mikel-brostrom/Yolov5_StrongSORT_OSNet#433]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi. So I have 2 separately RTSP IP streams that I have added into a text file called 'streams.txt'. When I run it and stop it to look at the saved video. I have 1 video which shows video from 1st item and then after a while from 2 item. But the 2nd video starts at a later time than the first video. 
I want to confirm that the processing is done simultaneously for both streams? What would be the best way to confirm this?

Thank you for your time

**Comment by arturo-collado-rosell** [comment]
Hello, I have the same question.

**Comment by mikel-brostrom** [comment]
> When I run it and stop it to look at the saved video. I have 1 video which shows video from 1st item and then after a while from 2 item. But the 2nd video starts at a later time than the first video.

Hmm, I have no idea what could cause this. The result from each stream should be saved in its corresponding video
