### ISSUE TITLE
Question on understanding Strongsort.yaml settings

### ISSUE THREAD

**Issue by fatbringer** [mikel-brostrom/Yolov5_StrongSORT_OSNet#437]
### Search before asking

- [x] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

hello i am writing to ask about the folowing settings in strong_sort.yaml

```
  ECC: True
  MC_LAMBDA: 0.995
  EMA_ALPHA: 0.9
````

What does ECC, MC_LAMBDA and EMA_ALPHA stand for ? And what effects do these have ? 
Why do MC_LAMBDA and EMA_ALPHA have such high values ? (assumiing they range from 0 to 1)

**Comment by mikel-brostrom** [comment]
```python
  ECC: True            # activate camera motion compensation
  MC_LAMBDA: 0.995     # matching with both appearance (1 - MC_LAMBDA) and motion cost
  EMA_ALPHA: 0.9       # updates  appearance  state in  an exponential moving average manner
```

**Comment by fatbringer** [comment]
@mikel-brostrom thank you :)
