### ISSUE TITLE
Can run videos files (1000 avi files) in txt list?

### ISSUE THREAD

**Issue by BenzKukkik** [mikel-brostrom/Yolov5_StrongSORT_OSNet#444]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello, I try to use this code for counting animals with camera trap and I have to run many video files (more than 1000 files).
I made list txt file following you recommend it but I cannot track in video file list (1000 files) then I decrease video file to 10 files in txt file list, I can run track. 

Please suggestion to me if I 'd like to run more than 1000 videos for tracking and counting with your code.

**Comment by mikel-brostrom** [comment]
To me this sounds like a RAM limitation. But post the error please

**Comment by BenzKukkik** [comment]
> To me this sounds like a RAM limitation. But post the error please

I ran 236 video files. I got error as below. And don't get any files such as video with detection or text files.
> Traceback (most recent call last):
>   File "C:\Users\xxx\track.py", line 343, in <module>
>     main(opt)
>   File "C:\Users\xxx\track.py", line 331, in main
>     run(**vars(opt))
>   File "C:\Users\xxx\Anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "C:\Users\xxx\track.py", line 283, in run
>     t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
>   File "C:\Users\xxx\track.py", line 283, in <genexpr>
>     t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
> ZeroDivisionError: float division by zero

**Comment by BenzKukkik** [comment]
> > ZeroDivisionError: float division by zero
> 
> Could it be that some of the videos are empty, i.e. contains zero frames?

No, After I checked it, every video files was contained the data
