### ISSUE TITLE
Dealing with raw RGB stream

### ISSUE THREAD

**Issue by carlok** [mikel-brostrom/Yolov5_StrongSORT_OSNet#445]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,
thank you for your work.
I'm studying/modifying a copy of `track.py` because I'm going to deal with raw IP camera like [ATL314S-CT](https://www.edmundoptics.eu/p/lucid-vision-labs-atlastrade-atl314s-ct-sony-imx342-314mp-color-camera/41835/) which does not have RTSP, nor MP4 or H.264, just raw RGB images (no JPG) changing "instantly" on a given IP and port.
So I can't directly use the "JPG folder options" or "RTSP" or "MP4" etc that `track.py` provides.
What do you suggest for a quick prototype?
It's not `LoadImages` or `LoadStreams` I have to find a way to refill dataset which is just one image at a time... maybe something like eveloping your for like

```python
while True:
	dataset = newCustomFunctionToGetSingleRemoteRawImage()
	for frame_idx, (path, im, im0s, vid_cap, s) in enumerate(dataset):
		# current code
```

Thank you

**Comment by mikel-brostrom** [comment]
You will need some customization. The fastest thing would be to inherit from some of the dataset classes and change what is strictly necessary for your specific use-case.

Creating a dataset every interation in the while-loop is a bad idea. It will slow down everything.

**Comment by carlok** [comment]
Thank you for your answer. I created a new class from an existing one.
