### ISSUE TITLE
When run the "!python track.py" getting error. : track.py: error: unrecognized arguments: --yolo_model /content/Yolov5_DeepSort_OSNet/yolov5/weights/crowdhuman_yolov5m.pt

### ISSUE THREAD

**Issue by pgupta119** [mikel-brostrom/Yolov5_StrongSORT_OSNet#448]
<img width="1395" alt="Screenshot 2022-07-05 at 14 30 19" src="https://user-images.githubusercontent.com/62263152/177327852-20a23673-46cc-4844-9717-da570c2a9e01.png">

**Comment by pgupta119** [comment]
> --yolo-model

track.py: error: unrecognized arguments: --yolo-model /content/Yolov5_DeepSort_OSNet/yolov5/weights/crowdhuman_yolov5m.pt

**still not working**

**Comment by RAMBOCJ1** [comment]
try --yolo-weights your.pt   instead of --yolo_model

**Comment by mikel-brostrom** [comment]
> try --yolo-weights your.pt instead of --yolo_model

Your are right @RAMBOCJ1. Updated my commend aove

**Comment by pgupta119** [comment]
> 

FileNotFoundError: [Errno 2] No such file or directory: '/content/Yolov5_DeepSort_OSNet/yolov5/weights/crowdhuman_yolov5m.pt'

**Comment by mikel-brostrom** [comment]
Have you run:

```bash
# get yolov5m model trained on the crowd-human dataset
!wget -nc https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/releases/download/v.2.0/crowdhuman_yolov5m.pt -O /content/Yolov5_StrongSORT_OSNet/yolov5/weights/crowdhuman_yolov5m.pt
```

**Comment by pgupta119** [comment]
yes, I did and checked in the weights folder "crowdhuman_yolov5m.pt" but couldn't find it.x
<img width="1395" alt="Screenshot 2022-07-07 at 00 24 02" src="https://user-images.githubusercontent.com/62263152/177653454-abd319aa-02d0-432e-90f4-780454f3d663.png">

**Comment by mikel-brostrom** [comment]
The colab notebook got an update. Everything should work now. Let me know @pgupta119 if it works for you

**Comment by pgupta119** [comment]
@mikel-brostrom, it is working now.
