### ISSUE TITLE
Are there any StrongSORT weights that can be deployed on an edge device?

### ISSUE THREAD

**Issue by Puturbold** [mikel-brostrom/Yolov5_StrongSORT_OSNet#450]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

We are trying to deploy this repo on an edge tpu, but are having trouble because the existing weights are incompatible with the Google Coral Dev Board. The inference times are very slow without the edge tpu/tflite weights for the StrongSORT algorithm. Do you have any recommendations for deploying this on an edge device? Any help will be appreciated.

**Comment by mikel-brostrom** [comment]
Conversion to TFLite can be achieved. It is cumbersome as you will need to do something like:

1. PyTorch -> ONNX (https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html)
2. ONNX -> OpenVino (https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html) 
3. OpenVino -> TfLite (https://github.com/PINTO0309/openvino2tensorflow)

**Comment by Puturbold** [comment]
Hi Mikel,

We tried the steps you outlined to convert the mobilenetv2_x1_4_market1501.pt to a .tflite and successfully converted the model weights. However, we encountered a pickling error as shown below. 

Would you have any idea what could be causing this?

![image](https://user-images.githubusercontent.com/45886051/178863311-a1d0e08d-73c6-4f7e-84e4-68d6a1f7c409.png)
![WhatsApp Image 2022-07-11 at 5 02 10 PM](https://user-images.githubusercontent.com/45886051/178864545-d3916ae8-ae8e-4263-9aa7-188c18be1f79.jpeg)

**Comment by mikel-brostrom** [comment]
Wow, nice, I am glad that it worked! The current code in StrongSORT does not support TFLite model loading. `torch.load` is not meant for TFLite models. Try this: https://stackoverflow.com/questions/50443411/how-to-load-a-tflite-model-in-script. Consider leaving a PR for this and sharing the TFLite ReID model :smile:

**Comment by mikel-brostrom** [comment]
Check https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/tree/reid_tflite_export @Puturbold. I have a working export pipeline that goes through the following frameworks Pytorch --> ONNX --> OpenVino --> TFLite

**Comment by mikel-brostrom** [comment]
TensorRT and TorchScript supported now as well
