### ISSUE TITLE
How is the stpes to totally new detector and tracker on custom task

### ISSUE THREAD

**Issue by q671383789** [mikel-brostrom/Yolov5_StrongSORT_OSNet#451]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

So, I have read some issues but still confused.
I have a MOT task but its not person. 
the dataset is like 10 sets of sequential imgs. and I got the box and the tracking id in each phase so I can locate every obj and the trail.
So far I have trained yolov5 in my own dataset, what's the next I should do for tracking?

**Comment by mikel-brostrom** [comment]
If you want to train your own ReID model your should read: [Deep appearance descriptor training (link to external repository)](https://kaiyangzhou.github.io/deep-person-reid/user_guide.html)

But basically:

1. Understand how other ReID datasets such as Market 1501 or dukemtmcreid are structured
2. Structure your custom data the same
3. Train

**Comment by q671383789** [comment]
THX，I just want to know if there any uses for my ground truth of the trail for each object?
if just appearance, I thank some informations of the gt would be wasted




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mikel-brostrom/Yolov5_StrongSORT_OSNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月10日(星期天) 凌晨1:50
***@***.***&gt;;
抄送:&nbsp;"系要听Rock &amp; ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikel-brostrom/Yolov5_StrongSORT_OSNet] How is the stpes to totally new detector and tracker on custom task (Issue #451)





 
If you want to train your own ReID model your should read: Deep appearance descriptor training (link to external repository)
 
But basically:
  
Understand how other ReID datasets such as Market 1501 or dukemtmcreid are structured
 
Structure your custom data the same
 
Train

**Comment by mikel-brostrom** [comment]
If you check the structure of ReID datasets such as Market1501 you will understand that you need your MOT ground truth in order to create a ReID dataset

**Comment by q671383789** [comment]
yeah, I will check it soon, THX for ur patience again.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mikel-brostrom/Yolov5_StrongSORT_OSNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月10日(星期天) 晚上6:03
***@***.***&gt;;
抄送:&nbsp;"系要听Rock &amp; ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikel-brostrom/Yolov5_StrongSORT_OSNet] How is the stpes to totally new detector and tracker on custom task (Issue #451)





 
If you check the structure of ReID datasets such as Market1501 you will understand that you need your MOT ground truth in order to create a ReID dataset

**Comment by q671383789** [comment]
one more question, say I have 6 classes should I train 6 model for each class or just one is enough?

**Comment by remeberWei** [comment]
> 671383789

Is this nickname number your qq? Can I add you as a friend to discuss this MOT issue together?

**Comment by q671383789** [comment]
yeah of course




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月21日(星期四) 下午4:42
收件人: ***@***.***&gt;; 
抄送: "系要听Rock &amp; ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [mikel-brostrom/Yolov5_StrongSORT_OSNet] Custom ReID model (Issue #451)





  
671383789
  
Is this nickname number your qq? Can I add you as a friend to discuss this MOT issue together?

**Comment by q671383789** [comment]
one more question, if I have to detect 6 classes, should I train 6 tracker model for each class or just one?
I think maybe train a tracker for each class is better but time cost more?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mikel-brostrom/Yolov5_StrongSORT_OSNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月10日(星期天) 晚上6:03
***@***.***&gt;;
抄送:&nbsp;"系要听Rock &amp; ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikel-brostrom/Yolov5_StrongSORT_OSNet] How is the stpes to totally new detector and tracker on custom task (Issue #451)





 
If you check the structure of ReID datasets such as Market1501 you will understand that you need your MOT ground truth in order to create a ReID dataset
