### ISSUE TITLE
deep-person-reid can not be run on Kaggle.com

### ISSUE THREAD

**Issue by rkuo2000** [mikel-brostrom/Yolov5_StrongSORT_OSNet#455]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

I was told by Kaggle reviewer that my account was blocked because deep-person-reid can not be run on Kaggle.com

**Comment by mikel-brostrom** [comment]
I am not familiar with Kaggle competitions and have no idea why you got blocked. Maybe because of the License? I read in a post that Kaggle is not letting people use Yolov5 due to the license

**Comment by mikel-brostrom** [comment]
Let me know what the issue is!

**Comment by rkuo2000** [comment]
It just bump me out the kaggle, and my account get blocked, no idea what happen. Kaggle engineer is checking, only them can debug it.
