### ISSUE TITLE
camera_update issue

### ISSUE THREAD

**Issue by otsebriy** [mikel-brostrom/Yolov5_StrongSORT_OSNet#456]
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/ca6937569bf582f8efb46abf30a18c4246f35ce5/track.py#L186

It looks like you pass `prev_frame` that equals to `None` and a `current frame` that equals, for example, to `(720, 1280, 3)`.
Then it has to pass the `assert` in the `ECC` and it crushes.
Please take a look at that issue.

**Comment by mikel-brostrom** [comment]
I see. Weird it isn't crashing for me...

**Comment by mikel-brostrom** [comment]
Assert now part of condition for ECC after checking src and dst are not none. Thx for pointing this out @otsebriy
