### ISSUE TITLE
How to track with custom Yolov5 model?

### ISSUE THREAD

**Issue by KVishwas98** [mikel-brostrom/Yolov5_StrongSORT_OSNet#458]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I may sound childish with my questions. I have searched a lot and this is the last option to get my problem solved.

I have custom trained model on yolov5. I have got best/pt. and all other files.

How am i supposed to integrate yolov5 custom train model with deep sort in order to get counting on my objects.

And I want to perform this task on google colab. as my laptop configuration is low. 

Appreciate your time.

**Comment by KVishwas98** [comment]
help

**Comment by mikel-brostrom** [comment]
All you need to is to load your weights by

`python track.py --source 0 --yolo-weights /weights/to/your/best.pt`

Tracking will start

**Comment by KVishwas98** [comment]
Thank you for your quick response. Just to correct my query. I am able to detect object and able to track. My question is How am i supposed to count the object with the help of deep sort.

github repo of deepsort has pretrained object counting model. How am i going to custom trained deepsort with custom trained model. Help me with this.

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/406#issuecomment-1145093104
