### ISSUE TITLE
Is there a way how to count multiple objects separately?

### ISSUE THREAD

**Issue by adamekcerv** [mikel-brostrom/Yolov5_StrongSORT_OSNet#459]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,
Is there a way how to count multiple objects separately?
I would like to setup a real time traffic counter from cctv and calculate how many different cars and bicycles crosses the road.
Would it be better to implement a line on screen and count how many people, cars and bicycle cross it? - is it possible implement something like that?
My final question is, if it is possible to use your software on this site and cctv Cameras?
http://kamery.ovanet.cz/

**Comment by mikel-brostrom** [comment]
> Is there a way how to count multiple objects separately?
> I would like to setup a real time traffic counter from cctv and calculate how many different cars and bicycles crosses the road.

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/428#issuecomment-1156757869, https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/406#issuecomment-1145093104

each track has a class_id which can be used to achieve this


> Would it be better to implement a line on screen and count how many people, cars and bicycle cross it? - is it possible implement something like that?

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/pull/211

> My final question is, if it is possible to use your software on this site and cctv Cameras?

This tracker works with: RTSP, RTMP, HTTP streams

**Comment by adamekcerv** [comment]
> > Is there a way how to count multiple objects separately?
> > I would like to setup a real time traffic counter from cctv and calculate how many different cars and bicycles crosses the road.
> 
> [#428 (comment)](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/428#issuecomment-1156757869), [#406 (comment)](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/406#issuecomment-1145093104)
> 
> each track has a class_id which can be used to achieve this
> 
> > Would it be better to implement a line on screen and count how many people, cars and bicycle cross it? - is it possible implement something like that?
> 
> #211
> 
> > My final question is, if it is possible to use your software on this site and cctv Cameras?
> 
> This tracker works with: RTSP, RTMP, HTTP streams

Thank you for your answer.
Although, when I run the tracker. The IDs were same for bicycles and pedestrians. How can I recognize the diference between them? What is the real number of objects in scene/video? Is it the ID number or the record of unique IDs in TXT (run folder)? If it is the real number is the same as ID number, the tracker is probably very inaccurate for me.
