### ISSUE TITLE
Giving different ID for same object at same location is detector change car to truck ie.

### ISSUE THREAD

**Issue by MyraBaba** [mikel-brostrom/Yolov5_StrongSORT_OSNet#460]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,

very stable and stopped vehicles. If detector change its decision car to truck the ID is changing even the same time and same place. Can we tell the StrongSort hey this is same object dont change the ID ?

Best

**Comment by mikel-brostrom** [comment]
Solution here:

https://github.com/ultralytics/yolov5/issues/6035

Use:

`python track.py --agnostic-nms`

**Comment by MyraBaba** [comment]
@mikel-brostrom  Thanks it looks solved.


which one is good for low HW resources ie ARM bytetrack or stronSort ?
