### ISSUE TITLE
BOTSORT

### ISSUE THREAD

**Issue by yums24** [mikel-brostrom/Yolov5_StrongSORT_OSNet#462]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello, consider adding bot-sort algorithm? In some scenarios, Reid can't improve but reduce the speed.

**Comment by mikel-brostrom** [comment]
Their improvements are marginal:

```
+0.7 IDF1
+0.6 HOTA
+0.4 MOTA  (on MOT17)
```

I will wait for at least a +1 on any of those metrics before I implement any new tracking solution
