### ISSUE TITLE
Jetson TX2

### ISSUE THREAD

**Issue by MyraBaba** [mikel-brostrom/Yolov5_StrongSORT_OSNet#463]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,

Is there any convenient way to run on the Jetson TX2 ? 

Or a docker image for JetsonTX2

**Comment by mikel-brostrom** [comment]
I have not run this on a JetsonTX2. But you could try using the official Yolov5 docker image adding the missing libraries for this project. Good luck!
