### ISSUE TITLE
 Detect continuous pictures

### ISSUE THREAD

**Issue by yan-ctrl** [mikel-brostrom/Yolov5_StrongSORT_OSNet#465]
Thank you very much for your work. I found that when I detect continuous pictures, I will synthesize videos. How can I modify it? Like the original yolov5, each picture corresponds to a txt file, and the relative coordinates are saved. I look forward to your reply.

**Comment by mikel-brostrom** [comment]
I changed this behavior so that I could generate videos out of the MOT16, MOT17 and MOT20 datasets. It changed in https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/releases/tag/v5.0. Check https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/releases/tag/v4.0 for saving pictures separately instead of videos.

**Comment by yan-ctrl** [comment]
Thank you for your reply. I'll have a look.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mikel-brostrom/Yolov5_StrongSORT_OSNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 下午2:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikel-brostrom/Yolov5_StrongSORT_OSNet]  Detect continuous pictures (Issue #465)





 
I changed this behavior so that I could generate videos out of the MOT16, MOT17 and MOT20 datasets. It changed in https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/releases/tag/v5.0. Check https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/releases/tag/v4.0 for saving pictures separately instead of videos.
