### ISSUE TITLE
mark objects already in first frame. N_INIT = 0

### ISSUE THREAD

**Issue by silvanro** [mikel-brostrom/Yolov5_StrongSORT_OSNet#466]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hey Mikel, thank you very much for your work!

My question: Is it possible, to have the tracked object already marked in the first frame of its appearance? I tried setting the N_INIT parameter to 0 but in the resulting .txt file and also in the resulting video the objects seem to be marked only from the second frame even if they are detected a frame earlier by YOLO as is visible from the console output.

Thanks for your help!

**Comment by mikel-brostrom** [comment]
This behavior is to be expected. You need at least two frames for association. This mean that the first frame will initiate the visual descriptor and Kalman filters and the second frame will make it possible to associate the incoming observation to the already existing visual descriptors and Kalman filter states. That is why you see no bboxes starting from frame 0, but from 1.
