### ISSUE TITLE
Model selection

### ISSUE THREAD

**Issue by SSTato** [mikel-brostrom/Yolov5_StrongSORT_OSNet#468]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

![image](https://user-images.githubusercontent.com/93987794/181412515-ad9dfc01-3df0-44e6-b78a-9d36934522d0.png)

When I use this algorithm to detect my own video, if there is no person in my video, but to detect other categories, such as only dogs in the whole video, can I still use these weights, or which weight should I use is more appropriate.

**Comment by mikel-brostrom** [comment]
All the ReID models have been trained on people only datasets. This doesn't mean that they cannot reidentify other classes, but the models will be suboptimal, of course, than if you would fine-tune them for your specific use-case.
