### ISSUE TITLE
Enable GPU + IDs question

### ISSUE THREAD

**Issue by adamekcerv** [mikel-brostrom/Yolov5_StrongSORT_OSNet#470]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,

I would like to figure out how to enable gpu for acceleration. I've tried to change the device to the "gpu" in track.py. But I am not sure if it works or not.

Another question is related to the actual tracking. I am trying to count three different object types - (pedestrians, cars and bicycles). Where can I find out which ID is connected to the actual object in the output txt.?

Furthermore, do I get it right, that I am counting only with the unique IDs to count the actual number of objects in the scene. - And the ID number is not represent the actual count?

Sorry for my noob questions, but I am really new into this.
Thank you.

**Comment by mikel-brostrom** [comment]
> I've tried to change the device to the "gpu" in track.py. But I am not sure if it works or not.

Do you have CUDA installed?

> Where can I find out which ID is connected to the actual object in the output txt.?

For COCO you have the class names and IDs associated to them [here](https://tech.amikelive.com/node-718/what-object-categories-labels-are-in-coco-dataset/)

> And the ID number is not represent the actual count?

Exactly, it is the unique ID associated to that object

**Comment by adamekcerv** [comment]
> > I've tried to change the device to the "gpu" in track.py. But I am not sure if it works or not.
> 
> Do you have CUDA installed?
> 
> > Where can I find out which ID is connected to the actual object in the output txt.?
> 
> For COCO you have the class names and IDs associated to them [here](https://tech.amikelive.com/node-718/what-object-categories-labels-are-in-coco-dataset/)
> 
> > And the ID number is not represent the actual count?
> 
> Exactly, it is the unique ID associated to that object

Yes, I have CUDA 11.7

I know about the class name ID (different for different objects). In my test video I only work with bicycles and pedestrians. But I cannot see the differences in my output txt. file.

**Comment by adamekcerv** [comment]
> > I've tried to change the device to the "gpu" in track.py. But I am not sure if it works or not.
> 
> Do you have CUDA installed?
> 
> > Where can I find out which ID is connected to the actual object in the output txt.?
> 
> For COCO you have the class names and IDs associated to them [here](https://tech.amikelive.com/node-718/what-object-categories-labels-are-in-coco-dataset/)
> 
> > And the ID number is not represent the actual count?
> 
> Exactly, it is the unique ID associated to that object

I'd also like to display the count of each object class in a corner of the video window.
I saw this issue: https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/428
However I am not sure how to edit tracks and n_init: List[Track]: https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/strong_sort/sort/tracker.py#:~:text=tracks%20%3A%20List%5BTrack%5D

When I put any number behind self.tracks = [] the code doesn't work. https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/strong_sort/sort/tracker.py#:~:text=.KalmanFilter()-,self.tracks%20%3D%20%5B%5D,-self._next_id
