### ISSUE TITLE
If I wanna use my model, how can i modify code ?

### ISSUE THREAD

**Issue by huchi00057** [mikel-brostrom/Yolov5_StrongSORT_OSNet#471]
### Search before asking

- [ ] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

If I wanna use my model, how can i modify code ?

**Comment by mikel-brostrom** [comment]
`python track.py --source 0 --yolo-weights /path/to/your/model,pt`
