### ISSUE TITLE
How to minimize `track.py`'s iteration time?

### ISSUE THREAD

**Issue by leon8491** [mikel-brostrom/Yolov5_StrongSORT_OSNet#472]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Frame rate is too low, it seems like after i set class == 0, the frame rate almost doesn't change, is there anyone can give some advice to improve my computing speed，maybe we can reduce some unnecessary operations?
Much appreciations for my foolish question!

By the way, my PC is macbookpro m1 2021.

**Comment by leon8491** [comment]
Hi, i am back now , i know how to set parameters now. I want to appreciate every person who have seen my question.However, my problem  still exits.the Frame rate is still  too low, it seems like after i set class == 0, the frame rate almost doesn't change, is there anyone can give some advice to improve my computing speed，maybe we can reduce some unnecessary operations?
Much appreciations for my foolish question again!

**Comment by mikel-brostrom** [comment]
> Frame rate is still too low, it seems like after i set class == 0, the frame rate almost doesn't change

The amount of computations in the NN does not change by filtering a certain class. So, the behavior you see is to be expected. However, you can try the following:

> is there anyone can give some advice to improve my computing speed

- Train a smaller Yolov5 model (s instead of l, for example)
- Make your input images smaller (640x640 to for example 320x320)
- Quantize the model to FP16 or INT8
