### ISSUE TITLE
image distortion and cpu skipping frames

### ISSUE THREAD

**Issue by zyakubova86** [mikel-brostrom/Yolov5_StrongSORT_OSNet#475]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi
While running with cpu videostream is not smooth and frames are skipped and time by time occuring image distortion causing inaccurate object counting. 
With GPU even worse with distortion 

Videocard: NVIDIA GeForce RTX 3090
NVIDIA-SMI 516.59       Driver Version: 516.59       CUDA Version: 11.7 
OS: Windows server 2022 datacenter

How can I fix this issue?

**Comment by mikel-brostrom** [comment]
Can you post a snippet of the video so that we can better help you resolving this issue?

**Comment by zyakubova86** [comment]
> Can you post a snippet of the video so that we can better help you resolving this issue?

@mikel-brostrom 
![photo_2022-08-01_21-43-04](https://user-images.githubusercontent.com/74640447/182200773-3e28a45d-4869-40e6-ab17-f249e1e3d93b.jpg)
![photo_2022-08-01_21-42-55](https://user-images.githubusercontent.com/74640447/182200778-05a5795d-da3c-4e20-b9ae-8cdd598325fb.jpg)
![photo_2022-08-01_21-43-00](https://user-images.githubusercontent.com/74640447/182200780-20dd3556-d283-46d4-a15f-d21b61b04c55.jpg)
![photo_2022-08-01_21-42-35](https://user-images.githubusercontent.com/74640447/182200783-dd4ddf6d-41d3-4390-b178-d09f3bf78680.jpg)
