### ISSUE TITLE
Bug in tracking

### ISSUE THREAD

**Issue by somieee20** [mikel-brostrom/Yolov5_StrongSORT_OSNet#476]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Tracking

### Bug

YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients
WARNING: Environment does not support cv2.imshow() or PIL Image.show() image displays
cv2.imshow() is disabled in Google Colab environments
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Traceback (most recent call last):
  File "track.py", line 321, in <module>
    main(opt)
  File "track.py", line 316, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 104, in run
    dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt)
  File "/content/Yolov5_StrongSORT_OSNet/yolov5/utils/dataloaders.py", line 325, in __init__
    assert cap.isOpened(), f'{st}Failed to open {s}'
AssertionError: 1/1: 0... Failed to open 0

### Environment

YoloV5 Tracking

**Comment by mikel-brostrom** [comment]
You are trying to open a webcam that is non-existent in Google Colab. Try:

pyhton track.py --source /path/to/your/vid.mp4

instead of

python track.py --source 0  # same as python track.py
