### ISSUE TITLE
int8 performance for new AI chips

### ISSUE THREAD

**Issue by MyraBaba** [mikel-brostrom/Yolov5_StrongSORT_OSNet#477]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,
@
I wonder how is the performance accuracy wise for the yolo5 and StrongSORT_OSNet on the new emerginf int8 AI chips ? 

Is the detection has the same quality ? or poor ? Can we have same quality ?

ie:

(mythic) , (hail o 8 )

**Comment by mikel-brostrom** [comment]
I have very bad experiences exporting to INT8 using TFLite. Some of my results for custom Yolov5 models can be seen [here](https://github.com/ultralytics/yolov5/issues/8762). This optimization method still needs to improve a lot in TFLite

**Comment by mikel-brostrom** [comment]
INT8 inference is insanely fast. Nobody can argue about that. But the export to INT8 of many frameworks, specially TFLite leaves a lot to be desired atm. Not making it a viable option for deployment in most cases

**Comment by MyraBaba** [comment]
do you think strongSort and yolo5 this repo could be fine in int8 ?

**Comment by mikel-brostrom** [comment]
With the official Yolov5 PT --> TFLiteIN8, no

**Comment by MyraBaba** [comment]
what will be the minimum req for realtime run ? is nvidia xavier good enough ?

**Comment by mikel-brostrom** [comment]
What do you mean by real-time? 10FPS? 50? 100?

**Comment by MyraBaba** [comment]
:) good point 

25 fps
