### ISSUE TITLE
I want to request person re-identification using face and body image.

### ISSUE THREAD

**Issue by hemangjoshi37a** [mikel-brostrom/Yolov5_StrongSORT_OSNet#481]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar enhancement requests.

### Description

In the given model it can not  re-identify the person. And i want to log person activities using thier names and ID.

### Use case

I am HIgh school teacher. I want to use this as classroom activity tracker for teachers to track which student is doing their work sincerely and which students are not working properly or cheating in examinations.

[hjlabs.in](https://hjlabs.in)

**Comment by mikel-brostrom** [comment]
Have you tried training your own Yolov5 model for your specific task? I would suggest you to start there

**Comment by hemangjoshi37a** [comment]
It would be great help you can suggest me any website to find that kind of
custom models. Your suggestions are highly appreciated.

Hjlabs.in

**Comment by mikel-brostrom** [comment]
The open source datasets that you can find online are very limited. Most of them would not suit you use-cases. You will have to collect you own for optimal performance

**Comment by hemangjoshi37a** [comment]
> The open source datasets that you can find online are very limited. Most of them won't suit you use-cases. You will have to collect you own for optimal performance

ok mikel, thanks for your input. Enjoy.
