### ISSUE TITLE
Continuous tracking  under different cameras

### ISSUE THREAD

**Issue by Zhou-sx** [mikel-brostrom/Yolov5_StrongSORT_OSNet#484]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Can this repository complete cross camera joint tracking? I mean to continuously track the same object under different IP cameras.

**Comment by mikel-brostrom** [comment]
This is not possible at the moment, we are working on it
