### ISSUE TITLE
Loading weights of OSNet (ReID)

### ISSUE THREAD

**Issue by abdullahjamal** [mikel-brostrom/Yolov5_StrongSORT_OSNet#485]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

When I load the weights of OSNet, I see the following output
The following layers are discarded due to unmatched keys or layer size: 
['conv1.conv.weight', 'conv1.bn.weight', 'conv1.bn.bias', 'conv2.0.conv1.conv.weight', 'conv2.0.conv1.bn.weight', 'conv2.0.conv1.bn.bias', 'conv2.0.conv1.bn.running_mean', 'conv2.0.conv1.bn.running_var', 'conv2.0.conv2.0.layers.0.conv1.weight', 'conv2.0.conv2.0.layers.0.conv2.weight', 'conv2.0.conv2.0.layers.0.bn.weight', 'conv2.0.conv2.0.layers.0.bn.bias', 'conv2.0.conv2.0.layers.0.bn.running_mean', 'conv2.0.conv2.0.layers.0.bn.running_var', 'conv2.0.conv2.0.layers.0.bn.num_batches_tracked', 'conv2.0.conv2.1.layers.0.conv1.weight', 'conv2.0.conv2.1.layers.0.conv2.weight', 'conv2.0.conv2.1.layers.0.bn.weight', 'conv2.0.conv2.1.layers.0.bn.bias', 'conv2.0.conv2.1.layers.0.bn.running_mean', 'conv2.0.conv2.1.layers.0.bn.running_var', 'conv2.0.conv2.1.layers.0.bn.num_batches_tracked', 'conv2.0.conv2.1.layers.1.conv1.weight', 'conv2.0.conv2.1.layers.1.conv2.weight', 'conv2.0.conv2.1.layers.1.bn.weight', 'conv2.0.conv2.1.layers.1.bn.bias', 'conv2.0.conv2.1.layers.1.bn.running_mean', 'conv2.0.conv2.1.layers.1.bn.running_var', 'conv2.0.conv2.1.layers.1.bn.num_batches_tracked', 'conv2.0.conv2.2.layers.0.conv1.weight', 'conv2.0.conv2.2.layers.0.conv2.weight', 'conv2.0.conv2.2.layers.0.bn.weight', 'conv2.0.conv2.2.layers.0.bn.bias', 'conv2.0.conv2.2.layers.0.bn.running_mean', 'conv2.0.conv2.2.layers.0.bn.running_var', 'conv2.0.conv2.2.layers.0.bn.num_batches_tracked', 'conv2.0.conv2.2.layers.1.conv1.weight', 'conv2.0.conv2.2.layers.1.conv2.weight', 'conv2.0.conv2.2.layers.1.bn.weight', 'conv2.0.conv2.2.layers.1.bn.bias', 'conv2.0.conv2.2.layers.1.bn.running_mean', 'conv2.0.conv2.2.layers.1.bn.running_var', 'conv2.0.conv2.2.layers.1.bn.num_batches_tracked', 'conv2.0.conv2.2.layers.2.conv1.weight', 'conv2.0.conv2.2.layers.2.conv2.weight', 'conv2.0.conv2.2.layers.2.bn.weight', 'conv2.0.conv2.2.layers.2.bn.bias', 'conv2.0.conv2.2.layers.2.bn.running_mean', 'conv2.0.conv2.2.layers.2.bn.running_var', 'conv2.0.conv2.2.layers.2.bn.num_batches_tracked', 'conv2.0.conv2.3.layers.0.conv1.weight', 'conv2.0.conv2.3.layers.0.conv2.weight', 'conv2.0.conv2.3.layers.0.bn.weight', 'conv2.0.conv2.3.layers.0.bn.bias', 'conv2.0.conv2.3.layers.0.bn.running_mean', 'conv2.0.conv2.3.layers.0.bn.running_var', 'conv2.0.conv2.3.layers.0.bn.num_batches_tracked', 'conv2.0.conv2.3.layers.1.conv1.weight', 'conv2.0.conv2.3.layers.1.conv2.weight', 'conv2.0.conv2.3.layers.1.bn.weight', 'conv2.0.conv2.3.layers.1.bn.bias', 'conv2.0.conv2.3.layers.1.bn.running_mean', 'conv2.0.conv2.3.layers.1.bn.running_var', 'conv2.0.conv2.3.layers.1.bn.num_batches_tracked', 'conv2.0.conv2.3.layers.2.conv1.weight', 'conv2.0.conv2.3.layers.2.conv2.weight', 'conv2.0.conv2.3.layers.2.bn.weight', 'conv2.0.conv2.3.layers.2.bn.bias', 'conv2.0.conv2.3.layers.2.bn.running_mean', 'conv2.0.conv2.3.layers.2.bn.running_var', 'conv2.0.conv2.3.layers.2.bn.num_batches_tracked', 'conv2.0.conv2.3.layers.3.conv1.weight', 'conv2.0.conv2.3.layers.3.conv2.weight', 'conv2.0.conv2.3.layers.3.bn.weight', 'conv2.0.conv2.3.layers.3.bn.bias', 'conv2.0.conv2.3.layers.3.bn.running_mean', 'conv2.0.conv2.3.layers.3.bn.running_var', 'conv2.0.conv2.3.layers.3.bn.num_batches_tracked', 'conv2.0.gate.fc1.weight', 'conv2.0.gate.fc1.bias', 'conv2.0.gate.fc2.weight', 'conv2.0.gate.fc2.bias', 'conv2.0.conv3.conv.weight', 'conv2.0.downsample.conv.weight', 'conv2.0.downsample.bn.weight', 'conv2.0.downsample.bn.bias', 'conv2.0.downsample.bn.running_mean', 'conv2.0.downsample.bn.running_var', 'conv2.0.IN.weight', 'conv2.0.IN.bias', 'conv2.1.conv1.conv.weight', 'conv2.1.conv1.bn.weight', 'conv2.1.conv1.bn.bias', 'conv2.1.conv1.bn.running_mean', 'conv2.1.conv1.bn.running_var', 'conv2.1.conv2.0.layers.0.conv1.weight', 'conv2.1.conv2.0.layers.0.conv2.weight', 'conv2.1.conv2.0.layers.0.bn.weight', 'conv2.1.conv2.0.layers.0.bn.bias', 'conv2.1.conv2.0.layers.0.bn.running_mean', 'conv2.1.conv2.0.layers.0.bn.running_var', 'conv2.1.conv2.0.layers.0.bn.num_batches_tracked', 'conv2.1.conv2.1.layers.0.conv1.weight', 'conv2.1.conv2.1.layers.0.conv2.weight', 'conv2.1.conv2.1.layers.0.bn.weight', 'conv2.1.conv2.1.layers.0.bn.bias', 'conv2.1.conv2.1.layers.0.bn.running_mean', 'conv2.1.conv2.1.layers.0.bn.running_var', 'conv2.1.conv2.1.layers.0.bn.num_batches_tracked', 'conv2.1.conv2.1.layers.1.conv1.weight', 'conv2.1.conv2.1.layers.1.conv2.weight', 'conv2.1.conv2.1.layers.1.bn.weight', 'conv2.1.conv2.1.layers.1.bn.bias', 'conv2.1.conv2.1.layers.1.bn.running_mean', 'conv2.1.conv2.1.layers.1.bn.running_var', 'conv2.1.conv2.1.layers.1.bn.num_batches_tracked', 'conv2.1.conv2.2.layers.0.conv1.weight', 'conv2.1.conv2.2.layers.0.conv2.weight', 'conv2.1.conv2.2.layers.0.bn.weight', 'conv2.1.conv2.2.layers.0.bn.bias', 'conv2.1.conv2.2.layers.0.bn.running_mean', 'conv2.1.conv2.2.layers.0.bn.running_var', 'conv2.1.conv2.2.layers.0.bn.num_batches_tracked', 'conv2.1.conv2.2.layers.1.conv1.weight', 'conv2.1.conv2.2.layers.1.conv2.weight', 'conv2.1.conv2.2.layers.1.bn.weight', 'conv2.1.conv2.2.layers.1.bn.bias', 'conv2.1.conv2.2.layers.1.bn.running_mean', 'conv2.1.conv2.2.layers.1.bn.running_var', 'conv2.1.conv2.2.layers.1.bn.num_batches_tracked', 'conv2.1.conv2.2.layers.2.conv1.weight', 'conv2.1.conv2.2.layers.2.conv2.weight', 'conv2.1.conv2.2.layers.2.bn.weight', 'conv2.1.conv2.2.layers.2.bn.bias', 'conv2.1.conv2.2.layers.2.bn.running_mean', 'conv2.1.conv2.2.layers.2.bn.running_var', 'conv2.1.conv2.2.layers.2.bn.num_batches_tracked', 'conv2.1.conv2.3.layers.0.conv1.weight', 'conv2.1.conv2.3.layers.0.conv2.weight', 'conv2.1.conv2.3.layers.0.bn.weight', 'conv2.1.conv2.3.layers.0.bn.bias', 'conv2.1.conv2.3.layers.0.bn.running_mean', 'conv2.1.conv2.3.layers.0.bn.running_var', 'conv2.1.conv2.3.layers.0.bn.num_batches_tracked', 'conv2.1.conv2.3.layers.1.conv1.weight', 'conv2.1.conv2.3.layers.1.conv2.weight', 'conv2.1.conv2.3.layers.1.bn.weight', 'conv2.1.conv2.3.layers.1.bn.bias', 'conv2.1.conv2.3.layers.1.bn.running_mean', 'conv2.1.conv2.3.layers.1.bn.running_var', 'conv2.1.conv2.3.layers.1.bn.num_batches_tracked', 'conv2.1.conv2.3.layers.2.conv1.weight', 'conv2.1.conv2.3.layers.2.conv2.weight', 'conv2.1.conv2.3.layers.2.bn.weight', 'conv2.1.conv2.3.layers.2.bn.bias', 'conv2.1.conv2.3.layers.2.bn.running_mean', 'conv2.1.conv2.3.layers.2.bn.running_var', 'conv2.1.conv2.3.layers.2.bn.num_batches_tracked', 'conv2.1.conv2.3.layers.3.conv1.weight', 'conv2.1.conv2.3.layers.3.conv2.weight', 'conv2.1.conv2.3.layers.3.bn.weight', 'conv2.1.conv2.3.layers.3.bn.bias', 'conv2.1.conv2.3.layers.3.bn.running_mean', 'conv2.1.conv2.3.layers.3.bn.running_var', 'conv2.1.conv2.3.layers.3.bn.num_batches_tracked', 'conv2.1.gate.fc1.weight', 'conv2.1.gate.fc1.bias', 'conv2.1.gate.fc2.weight', 'conv2.1.gate.fc2.bias', 'conv2.1.conv3.conv.weight', 'conv2.1.IN.weight', 'conv2.1.IN.bias', 'pool2.0.conv.weight', 'pool2.0.bn.weight', 'pool2.0.bn.bias', 'pool2.0.bn.running_mean', 'pool2.0.bn.running_var', 'pool2.0.bn.num_batches_tracked', 'conv3.0.conv1.conv.weight', 'conv3.0.conv1.bn.weight', 'conv3.0.conv1.bn.bias', 'conv3.0.conv1.bn.running_mean', 'conv3.0.conv1.bn.running_var', 'conv3.0.conv2.0.layers.0.conv1.weight', 'conv3.0.conv2.0.layers.0.conv2.weight', 'conv3.0.conv2.0.layers.0.bn.weight', 'conv3.0.conv2.0.layers.0.bn.bias', 'conv3.0.conv2.0.layers.0.bn.running_mean', 'conv3.0.conv2.0.layers.0.bn.running_var', 'conv3.0.conv2.0.layers.0.bn.num_batches_tracked', 'conv3.0.conv2.1.layers.0.conv1.weight', 'conv3.0.conv2.1.layers.0.conv2.weight', 'conv3.0.conv2.1.layers.0.bn.weight', 'conv3.0.conv2.1.layers.0.bn.bias', 'conv3.0.conv2.1.layers.0.bn.running_mean', 'conv3.0.conv2.1.layers.0.bn.running_var', 'conv3.0.conv2.1.layers.0.bn.num_batches_tracked', 'conv3.0.conv2.1.layers.1.conv1.weight', 'conv3.0.conv2.1.layers.1.conv2.weight', 'conv3.0.conv2.1.layers.1.bn.weight', 'conv3.0.conv2.1.layers.1.bn.bias', 'conv3.0.conv2.1.layers.1.bn.running_mean', 'conv3.0.conv2.1.layers.1.bn.running_var', 'conv3.0.conv2.1.layers.1.bn.num_batches_tracked', 'conv3.0.conv2.2.layers.0.conv1.weight', 'conv3.0.conv2.2.layers.0.conv2.weight', 'conv3.0.conv2.2.layers.0.bn.weight', 'conv3.0.conv2.2.layers.0.bn.bias', 'conv3.0.conv2.2.layers.0.bn.running_mean', 'conv3.0.conv2.2.layers.0.bn.running_var', 'conv3.0.conv2.2.layers.0.bn.num_batches_tracked', 'conv3.0.conv2.2.layers.1.conv1.weight', 'conv3.0.conv2.2.layers.1.conv2.weight', 'conv3.0.conv2.2.layers.1.bn.weight', 'conv3.0.conv2.2.layers.1.bn.bias', 'conv3.0.conv2.2.layers.1.bn.running_mean', 'conv3.0.conv2.2.layers.1.bn.running_var', 'conv3.0.conv2.2.layers.1.bn.num_batches_tracked', 'conv3.0.conv2.2.layers.2.conv1.weight', 'conv3.0.conv2.2.layers.2.conv2.weight', 'conv3.0.conv2.2.layers.2.bn.weight', 'conv3.0.conv2.2.layers.2.bn.bias', 'conv3.0.conv2.2.layers.2.bn.running_mean', 'conv3.0.conv2.2.layers.2.bn.running_var', 'conv3.0.conv2.2.layers.2.bn.num_batches_tracked', 'conv3.0.conv2.3.layers.0.conv1.weight', 'conv3.0.conv2.3.layers.0.conv2.weight', 'conv3.0.conv2.3.layers.0.bn.weight', 'conv3.0.conv2.3.layers.0.bn.bias', 'conv3.0.conv2.3.layers.0.bn.running_mean', 'conv3.0.conv2.3.layers.0.bn.running_var', 'conv3.0.conv2.3.layers.0.bn.num_batches_tracked', 'conv3.0.conv2.3.layers.1.conv1.weight', 'conv3.0.conv2.3.layers.1.conv2.weight', 'conv3.0.conv2.3.layers.1.bn.weight', 'conv3.0.conv2.3.layers.1.bn.bias', 'conv3.0.conv2.3.layers.1.bn.running_mean', 'conv3.0.conv2.3.layers.1.bn.running_var', 'conv3.0.conv2.3.layers.1.bn.num_batches_tracked', 'conv3.0.conv2.3.layers.2.conv1.weight', 'conv3.0.conv2.3.layers.2.conv2.weight', 'conv3.0.conv2.3.layers.2.bn.weight', 'conv3.0.conv2.3.layers.2.bn.bias', 'conv3.0.conv2.3.layers.2.bn.running_mean', 'conv3.0.conv2.3.layers.2.bn.running_var', 'conv3.0.conv2.3.layers.2.bn.num_batches_tracked', 'conv3.0.conv2.3.layers.3.conv1.weight', 'conv3.0.conv2.3.layers.3.conv2.weight', 'conv3.0.conv2.3.layers.3.bn.weight', 'conv3.0.conv2.3.layers.3.bn.bias', 'conv3.0.conv2.3.layers.3.bn.running_mean', 'conv3.0.conv2.3.layers.3.bn.running_var', 'conv3.0.conv2.3.layers.3.bn.num_batches_tracked', 'conv3.0.gate.fc1.weight', 'conv3.0.gate.fc1.bias', 'conv3.0.gate.fc2.weight', 'conv3.0.gate.fc2.bias', 'conv3.0.conv3.conv.weight', 'conv3.0.conv3.bn.weight', 'conv3.0.conv3.bn.bias', 'conv3.0.conv3.bn.running_mean', 'conv3.0.conv3.bn.running_var', 'conv3.0.downsample.conv.weight', 'conv3.0.downsample.bn.weight', 'conv3.0.downsample.bn.bias', 'conv3.0.downsample.bn.running_mean', 'conv3.0.downsample.bn.running_var', 'conv3.1.conv1.conv.weight', 'conv3.1.conv1.bn.weight', 'conv3.1.conv1.bn.bias', 'conv3.1.conv1.bn.running_mean', 'conv3.1.conv1.bn.running_var', 'conv3.1.conv2.0.layers.0.conv1.weight', 'conv3.1.conv2.0.layers.0.conv2.weight', 'conv3.1.conv2.0.layers.0.bn.weight', 'conv3.1.conv2.0.layers.0.bn.bias', 'conv3.1.conv2.0.layers.0.bn.running_mean', 'conv3.1.conv2.0.layers.0.bn.running_var', 'conv3.1.conv2.0.layers.0.bn.num_batches_tracked', 'conv3.1.conv2.1.layers.0.conv1.weight', 'conv3.1.conv2.1.layers.0.conv2.weight', 'conv3.1.conv2.1.layers.0.bn.weight', 'conv3.1.conv2.1.layers.0.bn.bias', 'conv3.1.conv2.1.layers.0.bn.running_mean', 'conv3.1.conv2.1.layers.0.bn.running_var', 'conv3.1.conv2.1.layers.0.bn.num_batches_tracked', 'conv3.1.conv2.1.layers.1.conv1.weight', 'conv3.1.conv2.1.layers.1.conv2.weight', 'conv3.1.conv2.1.layers.1.bn.weight', 'conv3.1.conv2.1.layers.1.bn.bias', 'conv3.1.conv2.1.layers.1.bn.running_mean', 'conv3.1.conv2.1.layers.1.bn.running_var', 'conv3.1.conv2.1.layers.1.bn.num_batches_tracked', 'conv3.1.conv2.2.layers.0.conv1.weight', 'conv3.1.conv2.2.layers.0.conv2.weight', 'conv3.1.conv2.2.layers.0.bn.weight', 'conv3.1.conv2.2.layers.0.bn.bias', 'conv3.1.conv2.2.layers.0.bn.running_mean', 'conv3.1.conv2.2.layers.0.bn.running_var', 'conv3.1.conv2.2.layers.0.bn.num_batches_tracked', 'conv3.1.conv2.2.layers.1.conv1.weight', 'conv3.1.conv2.2.layers.1.conv2.weight', 'conv3.1.conv2.2.layers.1.bn.weight', 'conv3.1.conv2.2.layers.1.bn.bias', 'conv3.1.conv2.2.layers.1.bn.running_mean', 'conv3.1.conv2.2.layers.1.bn.running_var', 'conv3.1.conv2.2.layers.1.bn.num_batches_tracked', 'conv3.1.conv2.2.layers.2.conv1.weight', 'conv3.1.conv2.2.layers.2.conv2.weight', 'conv3.1.conv2.2.layers.2.bn.weight', 'conv3.1.conv2.2.layers.2.bn.bias', 'conv3.1.conv2.2.layers.2.bn.running_mean', 'conv3.1.conv2.2.layers.2.bn.running_var', 'conv3.1.conv2.2.layers.2.bn.num_batches_tracked', 'conv3.1.conv2.3.layers.0.conv1.weight', 'conv3.1.conv2.3.layers.0.conv2.weight', 'conv3.1.conv2.3.layers.0.bn.weight', 'conv3.1.conv2.3.layers.0.bn.bias', 'conv3.1.conv2.3.layers.0.bn.running_mean', 'conv3.1.conv2.3.layers.0.bn.running_var', 'conv3.1.conv2.3.layers.0.bn.num_batches_tracked', 'conv3.1.conv2.3.layers.1.conv1.weight', 'conv3.1.conv2.3.layers.1.conv2.weight', 'conv3.1.conv2.3.layers.1.bn.weight', 'conv3.1.conv2.3.layers.1.bn.bias', 'conv3.1.conv2.3.layers.1.bn.running_mean', 'conv3.1.conv2.3.layers.1.bn.running_var', 'conv3.1.conv2.3.layers.1.bn.num_batches_tracked', 'conv3.1.conv2.3.layers.2.conv1.weight', 'conv3.1.conv2.3.layers.2.conv2.weight', 'conv3.1.conv2.3.layers.2.bn.weight', 'conv3.1.conv2.3.layers.2.bn.bias', 'conv3.1.conv2.3.layers.2.bn.running_mean', 'conv3.1.conv2.3.layers.2.bn.running_var', 'conv3.1.conv2.3.layers.2.bn.num_batches_tracked', 'conv3.1.conv2.3.layers.3.conv1.weight', 'conv3.1.conv2.3.layers.3.conv2.weight', 'conv3.1.conv2.3.layers.3.bn.weight', 'conv3.1.conv2.3.layers.3.bn.bias', 'conv3.1.conv2.3.layers.3.bn.running_mean', 'conv3.1.conv2.3.layers.3.bn.running_var', 'conv3.1.conv2.3.layers.3.bn.num_batches_tracked', 'conv3.1.gate.fc1.weight', 'conv3.1.gate.fc1.bias', 'conv3.1.gate.fc2.weight', 'conv3.1.gate.fc2.bias', 'conv3.1.conv3.conv.weight', 'conv3.1.IN.weight', 'conv3.1.IN.bias', 'pool3.0.conv.weight', 'pool3.0.bn.weight', 'pool3.0.bn.bias', 'pool3.0.bn.running_mean', 'pool3.0.bn.running_var', 'pool3.0.bn.num_batches_tracked', 'conv4.0.conv1.conv.weight', 'conv4.0.conv1.bn.weight', 'conv4.0.conv1.bn.bias', 'conv4.0.conv1.bn.running_mean', 'conv4.0.conv1.bn.running_var', 'conv4.0.conv2.0.layers.0.conv1.weight', 'conv4.0.conv2.0.layers.0.conv2.weight', 'conv4.0.conv2.0.layers.0.bn.weight', 'conv4.0.conv2.0.layers.0.bn.bias', 'conv4.0.conv2.0.layers.0.bn.running_mean', 'conv4.0.conv2.0.layers.0.bn.running_var', 'conv4.0.conv2.0.layers.0.bn.num_batches_tracked', 'conv4.0.conv2.1.layers.0.conv1.weight', 'conv4.0.conv2.1.layers.0.conv2.weight', 'conv4.0.conv2.1.layers.0.bn.weight', 'conv4.0.conv2.1.layers.0.bn.bias', 'conv4.0.conv2.1.layers.0.bn.running_mean', 'conv4.0.conv2.1.layers.0.bn.running_var', 'conv4.0.conv2.1.layers.0.bn.num_batches_tracked', 'conv4.0.conv2.1.layers.1.conv1.weight', 'conv4.0.conv2.1.layers.1.conv2.weight', 'conv4.0.conv2.1.layers.1.bn.weight', 'conv4.0.conv2.1.layers.1.bn.bias', 'conv4.0.conv2.1.layers.1.bn.running_mean', 'conv4.0.conv2.1.layers.1.bn.running_var', 'conv4.0.conv2.1.layers.1.bn.num_batches_tracked', 'conv4.0.conv2.2.layers.0.conv1.weight', 'conv4.0.conv2.2.layers.0.conv2.weight', 'conv4.0.conv2.2.layers.0.bn.weight', 'conv4.0.conv2.2.layers.0.bn.bias', 'conv4.0.conv2.2.layers.0.bn.running_mean', 'conv4.0.conv2.2.layers.0.bn.running_var', 'conv4.0.conv2.2.layers.0.bn.num_batches_tracked', 'conv4.0.conv2.2.layers.1.conv1.weight', 'conv4.0.conv2.2.layers.1.conv2.weight', 'conv4.0.conv2.2.layers.1.bn.weight', 'conv4.0.conv2.2.layers.1.bn.bias', 'conv4.0.conv2.2.layers.1.bn.running_mean', 'conv4.0.conv2.2.layers.1.bn.running_var', 'conv4.0.conv2.2.layers.1.bn.num_batches_tracked', 'conv4.0.conv2.2.layers.2.conv1.weight', 'conv4.0.conv2.2.layers.2.conv2.weight', 'conv4.0.conv2.2.layers.2.bn.weight', 'conv4.0.conv2.2.layers.2.bn.bias', 'conv4.0.conv2.2.layers.2.bn.running_mean', 'conv4.0.conv2.2.layers.2.bn.running_var', 'conv4.0.conv2.2.layers.2.bn.num_batches_tracked', 'conv4.0.conv2.3.layers.0.conv1.weight', 'conv4.0.conv2.3.layers.0.conv2.weight', 'conv4.0.conv2.3.layers.0.bn.weight', 'conv4.0.conv2.3.layers.0.bn.bias', 'conv4.0.conv2.3.layers.0.bn.running_mean', 'conv4.0.conv2.3.layers.0.bn.running_var', 'conv4.0.conv2.3.layers.0.bn.num_batches_tracked', 'conv4.0.conv2.3.layers.1.conv1.weight', 'conv4.0.conv2.3.layers.1.conv2.weight', 'conv4.0.conv2.3.layers.1.bn.weight', 'conv4.0.conv2.3.layers.1.bn.bias', 'conv4.0.conv2.3.layers.1.bn.running_mean', 'conv4.0.conv2.3.layers.1.bn.running_var', 'conv4.0.conv2.3.layers.1.bn.num_batches_tracked', 'conv4.0.conv2.3.layers.2.conv1.weight', 'conv4.0.conv2.3.layers.2.conv2.weight', 'conv4.0.conv2.3.layers.2.bn.weight', 'conv4.0.conv2.3.layers.2.bn.bias', 'conv4.0.conv2.3.layers.2.bn.running_mean', 'conv4.0.conv2.3.layers.2.bn.running_var', 'conv4.0.conv2.3.layers.2.bn.num_batches_tracked', 'conv4.0.conv2.3.layers.3.conv1.weight', 'conv4.0.conv2.3.layers.3.conv2.weight', 'conv4.0.conv2.3.layers.3.bn.weight', 'conv4.0.conv2.3.layers.3.bn.bias', 'conv4.0.conv2.3.layers.3.bn.running_mean', 'conv4.0.conv2.3.layers.3.bn.running_var', 'conv4.0.conv2.3.layers.3.bn.num_batches_tracked', 'conv4.0.gate.fc1.weight', 'conv4.0.gate.fc1.bias', 'conv4.0.gate.fc2.weight', 'conv4.0.gate.fc2.bias', 'conv4.0.conv3.conv.weight', 'conv4.0.downsample.conv.weight', 'conv4.0.downsample.bn.weight', 'conv4.0.downsample.bn.bias', 'conv4.0.downsample.bn.running_mean', 'conv4.0.downsample.bn.running_var', 'conv4.0.IN.weight', 'conv4.0.IN.bias', 'conv4.1.conv1.conv.weight', 'conv4.1.conv1.bn.weight', 'conv4.1.conv1.bn.bias', 'conv4.1.conv1.bn.running_mean', 'conv4.1.conv1.bn.running_var', 'conv4.1.conv2.0.layers.0.conv1.weight', 'conv4.1.conv2.0.layers.0.conv2.weight', 'conv4.1.conv2.0.layers.0.bn.weight', 'conv4.1.conv2.0.layers.0.bn.bias', 'conv4.1.conv2.0.layers.0.bn.running_mean', 'conv4.1.conv2.0.layers.0.bn.running_var', 'conv4.1.conv2.0.layers.0.bn.num_batches_tracked', 'conv4.1.conv2.1.layers.0.conv1.weight', 'conv4.1.conv2.1.layers.0.conv2.weight', 'conv4.1.conv2.1.layers.0.bn.weight', 'conv4.1.conv2.1.layers.0.bn.bias', 'conv4.1.conv2.1.layers.0.bn.running_mean', 'conv4.1.conv2.1.layers.0.bn.running_var', 'conv4.1.conv2.1.layers.0.bn.num_batches_tracked', 'conv4.1.conv2.1.layers.1.conv1.weight', 'conv4.1.conv2.1.layers.1.conv2.weight', 'conv4.1.conv2.1.layers.1.bn.weight', 'conv4.1.conv2.1.layers.1.bn.bias', 'conv4.1.conv2.1.layers.1.bn.running_mean', 'conv4.1.conv2.1.layers.1.bn.running_var', 'conv4.1.conv2.1.layers.1.bn.num_batches_tracked', 'conv4.1.conv2.2.layers.0.conv1.weight', 'conv4.1.conv2.2.layers.0.conv2.weight', 'conv4.1.conv2.2.layers.0.bn.weight', 'conv4.1.conv2.2.layers.0.bn.bias', 'conv4.1.conv2.2.layers.0.bn.running_mean', 'conv4.1.conv2.2.layers.0.bn.running_var', 'conv4.1.conv2.2.layers.0.bn.num_batches_tracked', 'conv4.1.conv2.2.layers.1.conv1.weight', 'conv4.1.conv2.2.layers.1.conv2.weight', 'conv4.1.conv2.2.layers.1.bn.weight', 'conv4.1.conv2.2.layers.1.bn.bias', 'conv4.1.conv2.2.layers.1.bn.running_mean', 'conv4.1.conv2.2.layers.1.bn.running_var', 'conv4.1.conv2.2.layers.1.bn.num_batches_tracked', 'conv4.1.conv2.2.layers.2.conv1.weight', 'conv4.1.conv2.2.layers.2.conv2.weight', 'conv4.1.conv2.2.layers.2.bn.weight', 'conv4.1.conv2.2.layers.2.bn.bias', 'conv4.1.conv2.2.layers.2.bn.running_mean', 'conv4.1.conv2.2.layers.2.bn.running_var', 'conv4.1.conv2.2.layers.2.bn.num_batches_tracked', 'conv4.1.conv2.3.layers.0.conv1.weight', 'conv4.1.conv2.3.layers.0.conv2.weight', 'conv4.1.conv2.3.layers.0.bn.weight', 'conv4.1.conv2.3.layers.0.bn.bias', 'conv4.1.conv2.3.layers.0.bn.running_mean', 'conv4.1.conv2.3.layers.0.bn.running_var', 'conv4.1.conv2.3.layers.0.bn.num_batches_tracked', 'conv4.1.conv2.3.layers.1.conv1.weight', 'conv4.1.conv2.3.layers.1.conv2.weight', 'conv4.1.conv2.3.layers.1.bn.weight', 'conv4.1.conv2.3.layers.1.bn.bias', 'conv4.1.conv2.3.layers.1.bn.running_mean', 'conv4.1.conv2.3.layers.1.bn.running_var', 'conv4.1.conv2.3.layers.1.bn.num_batches_tracked', 'conv4.1.conv2.3.layers.2.conv1.weight', 'conv4.1.conv2.3.layers.2.conv2.weight', 'conv4.1.conv2.3.layers.2.bn.weight', 'conv4.1.conv2.3.layers.2.bn.bias', 'conv4.1.conv2.3.layers.2.bn.running_mean', 'conv4.1.conv2.3.layers.2.bn.running_var', 'conv4.1.conv2.3.layers.2.bn.num_batches_tracked', 'conv4.1.conv2.3.layers.3.conv1.weight', 'conv4.1.conv2.3.layers.3.conv2.weight', 'conv4.1.conv2.3.layers.3.bn.weight', 'conv4.1.conv2.3.layers.3.bn.bias', 'conv4.1.conv2.3.layers.3.bn.running_mean', 'conv4.1.conv2.3.layers.3.bn.running_var', 'conv4.1.conv2.3.layers.3.bn.num_batches_tracked', 'conv4.1.gate.fc1.weight', 'conv4.1.gate.fc1.bias', 'conv4.1.gate.fc2.weight', 'conv4.1.gate.fc2.bias', 'conv4.1.conv3.conv.weight', 'conv4.1.conv3.bn.weight', 'conv4.1.conv3.bn.bias', 'conv4.1.conv3.bn.running_mean', 'conv4.1.conv3.bn.running_var', 'conv5.conv.weight', 'conv5.bn.weight', 'conv5.bn.bias', 'conv5.bn.running_mean', 'conv5.bn.running_var', 'fc.0.weight', 'classifier.weight', 'classifier.bias']

Looks like the weights are not loaded correctly. What am I missing? I'm using the following link for ReID model https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO

**Comment by mikel-brostrom** [comment]
That usually happens when you load a set of weights corresponding to a specific model (let's say OSNet) into another (mobilenet for example).

**Comment by mikel-brostrom** [comment]
Provide the command you are using for better support

**Comment by abdullahjamal** [comment]
`python -W ignore track.py --source ./data/video.mp4 \
--yolo-weights weights/crowdhuman_yolov5m.pt \
--classes 0 \
--strong-sort-weights ./osnet_x0_25_msmt17.pt \
--save-vid`

I haven't changed anything in the track or model files.

**Comment by abdullahjamal** [comment]
Nevermind, I have figured out the problem. When I was saving .pt from .pth, I renamed the model file to different osnet architecture.

**Comment by mikel-brostrom** [comment]
The type of model where the weights are loaded is derived from the file's name. So if you rename your file to `osnet_x1_0_msmt17.pt` when in reality it is a `osnet_x0_25_market1501.pt` you will see this issuel
