### ISSUE TITLE
How can I use this repo?

### ISSUE THREAD

**Issue by heweun** [mikel-brostrom/Yolov5_StrongSORT_OSNet#494]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi!
I'm really apreciate your work.
We used your job to make our result.
Download your github and than revise your track.py
So, can we download all your github work and upload it to our github?

**Comment by mikel-brostrom** [comment]
You can do whatever you want with it as long as you follow the [license](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/LICENSE)
