### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by ShisuiUzumaki** [mikel-brostrom/Yolov5_StrongSORT_OSNet#495]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

How do I contribute to this repo. For example integrating anew detection module.

**Comment by mikel-brostrom** [comment]
The idea of this repo is to provide the most user-friendly and configurable tracker on github. As long as you follow these two things, feel free to submit a PR

**Comment by ShisuiUzumaki** [comment]
Then I would like to add YOLOv6 as detector. Also,could you explain me how did you make connection to yolov5 repo URL rather than adding it as a folder. I mean so the usage of recursive clone, the thing is I am new to this.

**Comment by ShisuiUzumaki** [comment]
> The idea of this repo is to provide the most user-friendly and configurable tracker on github. As long as you follow these two things, feel free to submit a PR

Then I would like to add YOLOv6 as detector. Also,could you explain me how did you make connection to yolov5 repo URL rather than adding it as a folder. I mean so the usage of recursive clone, the thing is I am new to this.

**Comment by ShisuiUzumaki** [comment]
If there is no issue, can I integrate YOLOv6
