### ISSUE TITLE
ModuleNotFoundError: No module named 'torchreid'

### ISSUE THREAD

**Issue by Elumicate** [mikel-brostrom/Yolov5_StrongSORT_OSNet#499]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Tracking

### Bug

After launching my command:
python track.py --source https://www.youtube.com/watch?v=z4vQEMiD3VI --yolo-weights yolov5n.pt --img 640 --strong-sort-weights osnet_x0_25_market1501.pt

I'm getting that error:
Traceback (most recent call last):
File "C:\Users\xoxolo\OneDrive\Documents\GitHub\Yolov5_DeepSort_OSNet\track.py", line 36, in
from strong_sort.utils.parser import get_config
File "C:\Users\xoxolo\OneDrive\Documents\GitHub\Yolov5_DeepSort_OSNet\strong_sort_init_.py", line 1, in
from .strong_sort import StrongSORT
File "C:\Users\xoxolo\OneDrive\Documents\GitHub\Yolov5_DeepSort_OSNet\strong_sort\strong_sort.py", line 9, in
from .sort.nn_matching import NearestNeighborDistanceMetric
File "C:\Users\xoxolo\OneDrive\Documents\GitHub\Yolov5_DeepSort_OSNet\strong_sort\sort\nn_matching.py", line 6, in
from torchreid.metrics.distance import compute_distance_matrix
ModuleNotFoundError: No module named 'torchreid'

Any clue?

### Environment

- Python 3.10
- yolov5: yolov5n.pt 
- Deepsort: osnet_x0_25_market1501.pt
- win 10 pro machine with 2 GTX 1080

### Minimal Reproducible Example

python track.py --source https://www.youtube.com/watch?v=z4vQEMiD3VI --yolo-weights yolov5n.pt --img 640 --strong-sort-weights osnet_x0_25_market1501.pt

**Comment by haixuanTao** [comment]
you can fix it with:
```bash
> `pip install https://github.com/KaiyangZhou/deep-person-reid/archive/master.zip`
```
See: https://github.com/phil-bergmann/tracking_wo_bnw/issues/159

**Comment by mikel-brostrom** [comment]
Is this a Windows only issue? I have never seen it on Linux

**Comment by haixuanTao** [comment]
It's probably linked to https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/commit/b20d9382d13a82b5a1471044c4e8a1078b1ff0c5 as you removed `torchreid` as dependency. 

The error is generic for not founding a module called torchreid. :package:

**Comment by mikel-brostrom** [comment]
Both CI pipelines (Linux & Windows) shows passing without adding this package

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/runs/8014547296?check_suite_focus=true 
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/runs/8014547395?check_suite_focus=true

**Comment by haixuanTao** [comment]
I think that the CI does not catch the error because it does not use function from `torchreid`. the track app on the default argument you passed never import `torchreid`, the import are unused.

I believe that in my example and the example mentioned above, track will call a ` from torchreid.metrics.distance import compute_distance_matrix`. 

if you open an interpreter, it is easy to check that 
```bash
import torchreid
# and 
from torchreid.metrics.distance import compute_distance_matrix
# will not work
```

You can choose to remove all `torchreid` if you do not want to add `torchreid`

**Comment by mikel-brostrom** [comment]
You are right. Some files still import from the package `torchreid` and not from the folder
`strong_sort.deep.reid.torchreid`

**Comment by mikel-brostrom** [comment]
What is weird is that this:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/6faeb4a38c632761ca566aa2ce1d06ce099243d3/strong_sort/strong_sort.py#L13

still works in the pipeline without the package being installed

**Comment by haixuanTao** [comment]
> https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/6faeb4a38c632761ca566aa2ce1d06ce099243d3/strong_sort/strong_sort.py#L13

This is never actually imported because `FeatureExtractor` is never used. If you call it, the `ModuleNotFoundError` is going to get triggered.

**Comment by mikel-brostrom** [comment]
Sorry, wrong file. It is used here:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/6faeb4a38c632761ca566aa2ce1d06ce099243d3/strong_sort/reid_multibackend.py#L13

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/6faeb4a38c632761ca566aa2ce1d06ce099243d3/strong_sort/reid_multibackend.py#L50

**Comment by haixuanTao** [comment]
So as you have replaced this import in ef83022d6127b429477eb7455194271999739cd2, the issue should be fixed.

**Comment by Leonerist** [comment]
> ```shell
> pip install https://github.com/KaiyangZhou/deep-person-reid/archive/master.zip
> ```

I got it when i use Ubuntu-22

**Comment by haixuanTao** [comment]
Just for information, I have repackaged `strong_sort` without torchreid and yolov5 as submodule. Only the strong_sort algorithm from this package, here: https://github.com/haixuanTao/yolov5_strongsort_package for people who want it extracted
