### ISSUE TITLE
Yolov7 version

### ISSUE THREAD

**Issue by MyraBaba** [mikel-brostrom/Yolov5_StrongSORT_OSNet#509]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,

Is there any Yolov7 integration ?  I want to detect vehicles as possible as much from traffic cameras. I thought Yolov7 e6e is the best one. 

Best

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet
