### ISSUE TITLE
How to improve the stability of the moving target box and make it look smoother

### ISSUE THREAD

**Issue by songjiahao-wq** [mikel-brostrom/Yolov5_StrongSORT_OSNet#510]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I have tried to replace the original Kalman. Are there any other parameters that have not been set to make the change of the target box smoother

**Comment by mikel-brostrom** [comment]
You could try out the previous KF, anything prior to v3.0. For example this one: https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/60d0a408a3c2c31233635ce241be32ee01979273/deep_sort_pytorch/deep_sort/sort/kalman_filter.py.  You can find the reason why it got changed here: https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/166
