### ISSUE TITLE
 Extract features from the image

### ISSUE THREAD

**Issue by pgupta119** [mikel-brostrom/Yolov5_StrongSORT_OSNet#511]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

 Hi Team,
 currently, I am working on  HDD (Honda dataset) initially 107 hours of video data but I received images of the video ( frame by frame). I  would like to use yolov5/ yolov7 to detect the object/ feature extraction.  How could  I use this code to get the feature/object detection from the ( input) images?   I also used the InceptionResnet-V2  neural network model pre-trained on Imagnet dataset to extract features from the images.  Following this paper( https://arxiv.org/pdf/1811.07391.pdf)

**Comment by mikel-brostrom** [comment]
You would need to train a Yolov5 model. I recommend you to check out this:

https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
