### ISSUE TITLE
torch and torchvision versions conflict in Orin

### ISSUE THREAD

**Issue by pbustos** [mikel-brostrom/Yolov5_StrongSORT_OSNet#513]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello, 
I am having this error when executing track.py in a Jetson Orin.
Installed versions of torch and torchvision are:

nvidia@jetson-orin-0:~/software/Yolov5_StrongSORT_OSNet$ pip list|grep torch
torch                   1.12.0a0+8a1a93a9.nv22.5
torchvision             0.13.0      

I have tried other version satisfying the requirements and got the same result. With pip install torch, it works but does not use the GPU.

Output:

nvidia@jetson-orin-0:~/software/Yolov5_StrongSORT_OSNet$ python3 track.py --source 0 --yolo-weights yolov5n.pt
/home/nvidia/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
/home/nvidia/software/Yolov5_StrongSORT_OSNet/strong_sort/deep/reid/torchreid/metrics/rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(
track: yolo_weights=[PosixPath('yolov5n.pt')], strong_sort_weights=/home/nvidia/software/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.pt, config_strongsort=strong_sort/configs/strong_sort.yaml, source=0, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=, show_vid=False, save_txt=False, save_conf=False, save_crop=False, save_vid=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/track, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False, eval=False
YOLOv5 🚀 2022-9-1 Python-3.8.10 torch-1.12.0a0+8a1a93a9.nv22.5 CUDA:0 (Orin, 30536MiB)

Fusing layers... 
YOLOv5n summary: 213 layers, 1867405 parameters, 0 gradients
1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)

Model: osnet_x0_25
- params: 203,568
- flops: 82,316,000
/home/nvidia/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:1402: UserWarning: positional arguments and argument "destination" are deprecated. nn.Module.state_dict will not accept them in the future. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
Successfully loaded pretrained weights from "/home/nvidia/software/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
Traceback (most recent call last):
  File "track.py", line 328, in <module>
    main(opt)
  File "track.py", line 323, in main
    run(**vars(opt))
  File "/home/nvidia/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 161, in run
    pred = non_max_suppression(pred, conf_thres, iou_thres, classes, agnostic_nms, max_det=max_det)
  File "/home/nvidia/software/Yolov5_StrongSORT_OSNet/yolov5/utils/general.py", line 888, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
  File "/home/nvidia/.local/lib/python3.8/site-packages/torchvision/ops/boxes.py", line 39, in nms
    _assert_has_ops()
  File "/home/nvidia/.local/lib/python3.8/site-packages/torchvision/extension.py", line 33, in _assert_has_ops
    raise RuntimeError(
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
terminate called without an active exception

Thanks!

**Comment by LQIN-1** [comment]
How did you solve it?

**Comment by mikel-brostrom** [comment]
Isn't the matrix under https://github.com/pytorch/vision#installation enough to solve it?
