### ISSUE TITLE
'Annotator' object has no attribute 'draw'

### ISSUE THREAD

**Issue by sunaixiadashuaibi** [mikel-brostrom/Yolov5_StrongSORT_OSNet#517]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

'Annotator' object has no attribute 'draw'，Hello, I reported an error here. What's the reason. Thank you for your reply

**Comment by mikel-brostrom** [comment]
Seems that your repo isn't up to date. Please, ppdate or reclone:

`git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet.git`
