### ISSUE TITLE
No module named 'torchreid.metrics'

### ISSUE THREAD

**Issue by GUETtrauto** [mikel-brostrom/Yolov5_StrongSORT_OSNet#518]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

When I run this project ,the program print this warning

**Comment by GUETtrauto** [comment]
[reid @ 4a07937](https://github.com/KaiyangZhou/deep-person-reid/tree/4a0793780bd13f53ec2ca753a94dcef62dc9e955)
download this can solve

**Comment by mikel-brostrom** [comment]
`git pull` and try again. I have replaced all `import torchreid` by alternative that should let you run the code without `pip install torchreid`

**Comment by mikel-brostrom** [comment]
Let me know if it works for you now :smile:

**Comment by vector987** [comment]
You should download torchreid use pip in command, like 'pip install torchreid'. Then, you can add 'from torchreid.reid.metrics import xxx' that you can use you want to use.
