### ISSUE TITLE
ModuleNotFoundError: No module named 'torchreid'

### ISSUE THREAD

**Issue by msadoun** [mikel-brostrom/Yolov5_StrongSORT_OSNet#519]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Tracking

### Bug

(yolo) C:\Users\sadoun\Desktop\Yolov5_StrongSORT_OSNet-master>python track.py --source C:\Users\sadoun\Desktop\detect --yolo-weights yolov5\runs\train\exp25\weights\best.pt --img 640 --save-txt
Traceback (most recent call last):
  File "track.py", line 36, in <module>
    from strong_sort.utils.parser import get_config
  File "C:\Users\sadoun\Desktop\Yolov5_StrongSORT_OSNet-master\strong_sort\__init__.py", line 1, in <module>
    from .strong_sort import StrongSORT
  File "C:\Users\sadoun\Desktop\Yolov5_StrongSORT_OSNet-master\strong_sort\strong_sort.py", line 9, in <module>
    from .sort.nn_matching import NearestNeighborDistanceMetric
  File "C:\Users\sadoun\Desktop\Yolov5_StrongSORT_OSNet-master\strong_sort\sort\nn_matching.py", line 6, in <module>
    from torchreid.metrics.distance import compute_distance_matrix
ModuleNotFoundError: No module named 'torchreid'

(yolo) C:\Users\sadoun\Desktop\Yolov5_StrongSORT_OSNet-master>

### Environment

I am using anaconda environment with all requirements. What could be the issue?

**Comment by mikel-brostrom** [comment]
I will provide a stable solution for this, this weekend. Menawhile you can:

`pip install torchreid`

**Comment by msadoun** [comment]
Thank you this worked !
