### ISSUE TITLE
Why did you use Cholesky factorization for kalman gain?

### ISSUE THREAD

**Issue by Zillurcuet** [mikel-brostrom/Yolov5_StrongSORT_OSNet#520]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Thanks for sharing this great work. I was wondering why did you use cholesky factorization to compute kalman gain. Kalman gain, K can be computed as below too:
`                                                       K = P*H.T*S^-1`
                                            where `S = H*P*H.T + R; `   R = measurement noise covariance, H = update matrix, P = process covariance

**Comment by mikel-brostrom** [comment]
https://www.jstor.org/stable/3087325
