### ISSUE TITLE
Training a custom Strong Sort Model

### ISSUE THREAD

**Issue by shubham190398** [mikel-brostrom/Yolov5_StrongSORT_OSNet#521]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello. I am trying to train a custom YOLO model with StrongSort. I have trained the custom model in YOLO from scratch. How would I do the same for StrongSort weights? What would be the best way to arrange the directories for the training? Would highly appreciate it if you could direct me to a relevant resource.

Thank you.

**Comment by mikel-brostrom** [comment]
https://kaiyangzhou.github.io/deep-person-reid/user_guide.html

**Comment by shubham190398** [comment]
Thank you @mikel-brostrom . Would this model be suited for small objects like letters?

**Comment by mikel-brostrom** [comment]
It depends how small the letters are in the field of view of the camera. The smaller, the harder to detect and hence to track

**Comment by shubham190398** [comment]
The v5 model I trained was able to detect the letters accurately. So in that case, I guess I could go ahead with the Deep-Person-ReID sort model and just replace people with letters?

**Comment by mikel-brostrom** [comment]
Sure! Make sure to report back with your results :smile:
