### ISSUE TITLE
running on GPU

### ISSUE THREAD

**Issue by YeetMasterYeet** [mikel-brostrom/Yolov5_StrongSORT_OSNet#522]
### Search before asking

- [x] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

hello, after cloning the repo and installing the requirements, i have managed to run the code on my camera, videos and pictures..
when i run the code,  the detection process is very slow, and i have seen that i am running on my CPU only
` YOLOv5  2022-9-11 Python-3.8.13 torch-1.12.1+cpu CPU'
my question is how can i use my GPU to run the code in order to get faster results.
thanks!

**Comment by mikel-brostrom** [comment]
1. Can you reach your Nvidia GPU by:

`nvidia-smi `

?

2. If yes. Try to explicitly install a CUDA version of pytorch:

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113`

If not, install CUDA
