### ISSUE TITLE
Unspecified FFMPEG error when saving video

### ISSUE THREAD

**Issue by Shanky71** [mikel-brostrom/Yolov5_StrongSORT_OSNet#524]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

![WhatsApp Image 2022-09-13 at 18 23 30](https://user-images.githubusercontent.com/72705901/189906333-b3a27720-5603-4ad0-bf60-b6b8a56d6381.jpeg)

I am trying to save the tracked video with the bounding boxes and id's. However I am not being able to save the video because of the highlighted error. Can you suggest what can be done to solve it.

**Comment by mikel-brostrom** [comment]
Do you have `ffmpeg` installed?

**Comment by Shanky71** [comment]
![WhatsApp Image 2022-09-13 at 19 59 49](https://user-images.githubusercontent.com/72705901/189928719-f55d6810-9cfe-4d40-b245-af7d7415d16d.jpeg)
Hey yes Iit's already installed in it

**Comment by mikel-brostrom** [comment]
I have never encountered this error. One relevant source that may be relevant for you issue:

https://github.com/DeepLabCut/DeepLabCut/issues/244

I recommend you to start from clean slate

**Comment by Shanky71** [comment]
I tried but still I am not able to save it. Can you recommend something more?

**Comment by Shanky71** [comment]
Thanks, for help. I solved it

**Comment by mikel-brostrom** [comment]
WHat was the issue @Shanky71?

**Comment by Shanky71** [comment]
In track.py where the flag to save video was defined I changed the from Mp4 to XVID.
                        fps, w, h = 25, 23040,2160
                    save_path = str(Path(save_path).with_suffix('.avi'))# force *.mp4 suffix on results videos
                    #vid_writer[i] = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (w, h))
                    fourcc = cv2.VideoWriter_fourcc('X','V','I','D')
                    vid_writer[i] = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc('M','J','P','G'), fps, (w, h))
                vid_writer[i].write(im0)
I hope this can help.

**Comment by Shanky71** [comment]
Thanks for the suggestions though.

**Comment by mikel-brostrom** [comment]
Thank you for letting us know :+1:
