### ISSUE TITLE
Colab: Run inference on video error 

### ISSUE THREAD

**Issue by wujoho** [mikel-brostrom/Yolov5_StrongSORT_OSNet#526]
hi Mike, does the below error matter?
![image](https://user-images.githubusercontent.com/12386794/190390640-b1f2f6b8-ac4f-47cf-97cb-f6bca07615a1.png)

**Comment by mikel-brostrom** [comment]
THe ReiD model is used as a feature extractor, so the classification layers in not needed. Hence, it is discarded

**Comment by wujoho** [comment]
sorry I meant the ERROR message "but you have importlib-metadata 4.2.0 which is incompatible"

**Comment by mikel-brostrom** [comment]
I recommend you to have different environments for different projects. `gym` is not part of Yolov5 StrongSORT OSNet
