### ISSUE TITLE
Colab: why the output video length is different to the input video's?

### ISSUE THREAD

**Issue by wujoho** [mikel-brostrom/Yolov5_StrongSORT_OSNet#527]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

1. changed the out.avi length from 3 seconds to 5 seconds, and the generated out.avi did have 5 seconds
2. the output.mp4 only has 3 seconds, why it is not 5 seconds too?
![image](https://user-images.githubusercontent.com/12386794/190394678-ffc8fac0-a9bf-4a7f-83d4-91ac3d18945e.png)

**Comment by mikel-brostrom** [comment]
It will probably work if you specify the original FPS of the video. If I am reading this right:

`https://trac.ffmpeg.org/wiki/Seeking`

>  the x264 encoder by default uses a GOP size of 250 (which means 1 keyframe each 10 seconds if the input frame rate is 25 fps)

I don't think the video has 25 FPS, probably lower.

**Comment by wujoho** [comment]
did more testing:
after running the below _python track.py_ steps, the generated mp4 files (out2.mp4, ..., out8.mp4) already halved:
out2.avi: 2 seconds -- out2.mp4: 1 second
out4.avi: 4 seconds -- out4.mp4: 2 seconds
out6.avi: 6 seconds -- out6.mp4: 3 seconds
out8.avi: 8 seconds -- out8.mp4: 4 seconds
![image](https://user-images.githubusercontent.com/12386794/191226741-7a57e89a-1988-48d2-afb6-10bb02401ea4.png)

so it seems that it was not caused by the below _ffmpeg_ step:
_!ffmpeg -i /content/Yolov5_StrongSORT_OSNet/runs/track/exp/out.mp4 output.mp4_
also adding fps=30 didn't help because the above mp4 files already run 2x fast:
_!ffmpeg -i /content/Yolov5_StrongSORT_OSNet/runs/track/exp/out.mp4 -filter:v fps=30 output.mp4_

**Comment by mikel-brostrom** [comment]
Solved by:

`!yes | ffmpeg -ss 00:00:00 -i test.avi -t 00:00:01 -vf fps=30 out.avi`

This:

`!yes | ffmpeg -ss 00:00:00 -i test.avi -t 00:00:01 out.avi`

assumes 60FPS

**Comment by mikel-brostrom** [comment]
Will update this tomorrow. Thank for helping me debug @wujoho ! :smile:

**Comment by mikel-brostrom** [comment]
Colab script updated based on this!
