### ISSUE TITLE
how do I keep count for classes found

### ISSUE THREAD

**Issue by eidichap** [mikel-brostrom/Yolov5_StrongSORT_OSNet#529]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

how do I keep count for classes found

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/521
