### ISSUE TITLE
training StrongSORT on custom dataset 

### ISSUE THREAD

**Issue by lorenzlorg** [mikel-brostrom/Yolov5_StrongSORT_OSNet#530]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I don't undestrand how to train StrongSORT on a custom dataset. Are there some useful links or some tutorial?

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/521

**Comment by lorenzlorg** [comment]
> #521

thanks @mikel-brostrom
