### ISSUE TITLE
Colab: no need to convert avi to mp4

### ISSUE THREAD

**Issue by wujoho** [mikel-brostrom/Yolov5_StrongSORT_OSNet#532]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi Mike, the below step in colab actually didn't convert avi to mp4, because the input file is already a mp4 file, so i assume it's not converting a avi file to mp4:
![image](https://user-images.githubusercontent.com/12386794/191231036-54428b8a-6983-4ab2-9405-5f4dc95e51aa.png)

**Comment by mikel-brostrom** [comment]
This step is needed otherwise an error is triggered

![Screenshot from 2022-09-20 14-19-04](https://user-images.githubusercontent.com/18719680/191255768-1b0df5b9-411d-4eaf-a79e-2035ee10ade6.png)
