### ISSUE TITLE
How to use argument line-thickness?

### ISSUE THREAD

**Issue by wujoho** [mikel-brostrom/Yolov5_StrongSORT_OSNet#533]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

The argument `--line-thickness` seems not working, the bounding box thickness in the below two running results are the same:
`python track.py --source 0 --yolo-weights weights/yolov5m.pt --line-thickness 2`
`python track.py --source 0 --yolo-weights weights/yolov5m.pt --line-thickness 200`

**Comment by mikel-brostrom** [comment]
I integrated that argument in the code. Thanks for pointing this out!
