### ISSUE TITLE
Issue with VID_FORMATS

### ISSUE THREAD

**Issue by latentnyc** [mikel-brostrom/Yolov5_StrongSORT_OSNet#537]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

Line:

from yolov5.utils.dataloaders import VID_FORMATS, LoadImages, LoadStreams 

does not appear to be working properly, I am using:

--source video.mp4

Despite that it is naming the MOD tracking file after my directory parent so I think 

                if source.endswith(VID_FORMATS):
                    txt_file_name = p.stem
                    save_path = str(save_dir / p.name)  # im.jpg, vid.mp4, ...
                # folder with imgs
                else:
                    txt_file_name = p.parent.name  # get folder name containing current img
                    save_path = str(save_dir / p.parent.name)  # im.jpg, vid.mp4, ...

in detection is failing and reverting to the else statement, most likely culprit is VID_FORMATS?  I did not pursue further and just did a very hacky remove of 'parent' from the save_path and txt_file_name for my use - I am searching my dashcam footage for airplanes!  I do not have a good reason to do this.

**Comment by mikel-brostrom** [comment]
Sorry cannot reproduce. 

```
~/Downloads/vid1.mp4 --save-vid
```

saves the resulting video file under 

```
./runs/track/expN/vid1.mp4
