### ISSUE TITLE
Model type suffixes

### ISSUE THREAD

**Issue by shahzaib3120** [mikel-brostrom/Yolov5_StrongSORT_OSNet#539]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Integrations

### Bug

```
F:\Machine-Learning\Yolov5_DeepSort_Pytorch
F:\Machine Learning\Yolov5_DeepSort_Pytorch\yolov5
F:\Machine-Learning\Yolov5_DeepSort_Pytorch\env\python310.zip
F:\Machine-Learning\Yolov5_DeepSort_Pytorch\env\DLLs
F:\Machine-Learning\Yolov5_DeepSort_Pytorch\env\lib
F:\Machine-Learning\Yolov5_DeepSort_Pytorch\env
F:\Machine-Learning\Yolov5_DeepSort_Pytorch\env\lib\site-packages
F:\Machine-Learning\Yolov5_DeepSort_Pytorch\yolov5
F:\Machine-Learning\Yolov5_DeepSort_Pytorch\strong_sort
F:\Machine-Learning\Yolov5_DeepSort_Pytorch\strong_sort/deep/reid\torchreid\metrics\rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(
track: yolo_weights=['weights/mario-23-09-22.pt'], strong_sort_weights=osnet_x0_25_market1501.pt, config_strongsort=strong_sort/configs/strong_sort.yaml, source=video/mario.mp4, imgsz=[416, 416], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=, show_vid=True, save_txt=False, save_conf=False, save_crop=False, save_vid=True, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\track, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False
YOLOv5  2022-9-23 Python-3.10.4 torch-1.12.1 CUDA:0 (NVIDIA GeForce GTX 1660 Ti, 6144MiB)

Fusing layers...
Model summary: 157 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
Traceback (most recent call last):
  File "F:\Machine-Learning\Yolov5_DeepSort_Pytorch\track.py", line 327, in <module>
    main(opt)
  File "F:\Machine-Learning\Yolov5_DeepSort_Pytorch\track.py", line 322, in main
    run(**vars(opt))
  File "F:\Machine-Learning\Yolov5_DeepSort_Pytorch\env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\Machine-Learning\Yolov5_DeepSort_Pytorch\track.py", line 122, in run
    StrongSORT(
  File "F:\Machine-Learning\Yolov5_DeepSort_Pytorch\strong_sort\strong_sort.py", line 34, in __init__
    self.model = ReIDDetectMultiBackend(weights=model_weights, device=device, fp16=fp16)
  File "F:\Machine-Learning\Yolov5_DeepSort_Pytorch\strong_sort\reid_multibackend.py", line 32, in __init__
    self.saved_model, self.pb, self.tflite, self.edgetpu, self.tfjs = self.model_type(w)  # get backend
  File "F:\Machine-Learning\Yolov5_DeepSort_Pytorch\strong_sort\reid_multibackend.py", line 106, in model_type
    pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, xml2 = (s in p for s in suffixes)
ValueError: too many values to unpack (expected 12)
```

### Environment

YOLOv5 
2022-9-23
Python-3.10.4
torch-1.12.1
CUDA:11.3
cuDNN: 8.5 
(NVIDIA GeForce GTX 1660 Ti, 6144MiB)
Windows 11

### Minimal Reproducible Example

After updating the repo to latest version of https://github.com/ultralytics/yolov5:

`python track.py --source video/tekken-6.mp4 --strong-sort-weights osnet_x0_25_market1501.pt --yolo-weights weights/crowdhuman_yolov5m.pt --classes 0 --save-vid --show-vid `

After some debugging, I found a quick fix for it. 
 
changing 
`pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs,  xml2 = (s in p for s in suffixes)` 
to 
`pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, _ ,  xml2 = (s in p for s in suffixes)` 
worked  for me.

as suffixes was this list: 
`['.pt', '.torchscript', '.onnx', '_openvino_model', '.engine', '.mlmodel', '_saved_model', '.pb', '.tflite', '_edgetpu.tflite', '_web_model', '_paddle_model', '.xml']`

of length 13. but code was expecting 12.

**Comment by mikel-brostrom** [comment]
I will take care of this when I update the Yolov5 repo. Thanks :smile:

**Comment by neo133** [comment]
I am getting this error with the updated repo @mikel-brostrom. Please suggest what to do.

**Comment by mikel-brostrom** [comment]
My suggestion is that you use the Yolov5 version in the repo. It is there for a reason

**Comment by neo133** [comment]
Thanks a lot for the amazing repo.
