### ISSUE TITLE
Problem when detect more than 1 detection TensorRT version

### ISSUE THREAD

**Issue by salazarvalverdefd** [mikel-brostrom/Yolov5_StrongSORT_OSNet#540]
Related to commit [multi-backend inference with dynamic batch-size for PT, ONNX, ENGINE …](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/commit/c3158fe1983e220ef684609751622398cdf9e78b) 

I test this repo a month ago and works fine, but now I have a problem with updated repo, when I have more than 1 detection when try to forward strongsort only return 1 feature matrix and get a error

    ---------------------------------------------------------------------------
    IndexError                                Traceback (most recent call last)
    <ipython-input-5-6fa342f7aff4> in <module>
         36         #half=False,  # use FP16 half-precision inference TODO
         37         dnn=False,  # use OpenCV DNN for ONNX inference
    ---> 38         eval=False,  # run multi-gpu eval
         39 )
    
    ~/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
         26         def decorate_context(*args, **kwargs):
         27             with self.__class__():
    ---> 28                 return func(*args, **kwargs)
         29         return cast(F, decorate_context)
         30 
    
    <ipython-input-3-114a7b59ad20> in run(source, yolo_weights, strong_sort_weights, config_strongsort, data, imgsz, conf_thres, iou_thres, max_det, device, show_vid, show_new, save_txt, save_conf, save_crop, save_vid, nosave, classes, agnostic_nms, augment, visualize, update, project, name, exist_ok, line_thickness, hide_labels, hide_conf, hide_class, half, dnn, eval)
        188                 print(i)
        189                 # pass detections to strongsort
    --> 190                 outputs[i] = strongsort_list[i].update(xywhs.cpu(), confs.cpu(), clss.cpu(), im0)
        191                 t6 = time_sync()
        192                 dt[4] += t6 - t5
    
    ~/Yolov5_StrongSORT_OSNet/strong_sort/strong_sort.py in update(self, bbox_xywh, confidences, classes, ori_img)
         50         print('bbox_tlwh', bbox_tlwh.shape)
         51         detections = [Detection(bbox_tlwh[i], conf, features[i]) for i, conf in enumerate(
    ---> 52             confidences)]
         53 
         54         # run on non-maximum supression
    
    ~/Yolov5_StrongSORT_OSNet/strong_sort/strong_sort.py in <listcomp>(.0)
         49         print('features', features.shape)
         50         print('bbox_tlwh', bbox_tlwh.shape)
    ---> 51         detections = [Detection(bbox_tlwh[i], conf, features[i]) for i, conf in enumerate(
         52             confidences)]
         53 
    
    IndexError: index 1 is out of bounds for dimension 0 with size 1

I debbug this code and found that _get_features in [strong_sort.py](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/strong_sort/strong_sort.py), only return 1 feature matrix when I have 2 detections

    def update(self, bbox_xywh, confidences, classes, ori_img):
        self.height, self.width = ori_img.shape[:2]
        # generate detections
        features = self._get_features(bbox_xywh, ori_img)
        bbox_tlwh = self._xywh_to_tlwh(bbox_xywh)

        print('bbox_xywh', bbox_xywh.shape)
        print('features', features.shape)
        print('bbox_tlwh', bbox_tlwh.shape)

        detections = [Detection(bbox_tlwh[i], conf, features[i]) for i, conf in enumerate(
            confidences)]

Result before get error

    bbox_xywh torch.Size([2, 4])
    features torch.Size([1, 512])
    bbox_tlwh torch.Size([2, 4])

And commit to [reid_multibackend.py](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/strong_sort/reid_multibackend.py), change "for" sintaxis and I only have 1 result in forward not 2 how I want

I used yolov5n.engine and osnet_x0_25_msmt17_2.engine exported by your [reid_export.py](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/reid_export.py), works fine with version before this (https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/commit/c3158fe1983e220ef684609751622398cdf9e78b)

**Comment by mikel-brostrom** [comment]
I cannot reproduce your error without your full reid export commands. However, notice this:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/52c82aabca110d89fcc13854b5056cae7d16bdc2/reid_export.py#L112

Using this export command:

```bash
python reid_export.py --weights ./weights/osnet_x0_25_msmt17.pt  --include engine onnx --device 0 --dynamic --simplify --batch-size 10
```

I have no issue detecting more than 1 object:

```bash
using layers... 
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients
1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)

Loading weights/osnet_x0_25_msmt17.engine for TensorRT inference...
[09/26/2022-10:56:08] [TRT] [I] [MemUsageChange] Init CUDA: CPU +193, GPU +0, now: CPU 1635, GPU 1571 (MiB)
[09/26/2022-10:56:08] [TRT] [I] Loaded engine size: 1 MiB
[09/26/2022-10:56:08] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +272, GPU +110, now: CPU 1930, GPU 1677 (MiB)
[09/26/2022-10:56:08] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +114, GPU +46, now: CPU 2044, GPU 1723 (MiB)
[09/26/2022-10:56:08] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.4.0
[09/26/2022-10:56:08] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +1, now: CPU 0, GPU 1 (MiB)
[09/26/2022-10:56:08] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 2041, GPU 1715 (MiB)
[09/26/2022-10:56:08] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +8, now: CPU 2042, GPU 1723 (MiB)
[09/26/2022-10:56:08] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.4.0
[09/26/2022-10:56:08] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +16, now: CPU 0, GPU 17 (MiB)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.680s), StrongSORT:(0.040s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.039s), StrongSORT:(0.019s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.042s), StrongSORT:(0.010s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.040s), StrongSORT:(0.016s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.040s), StrongSORT:(0.011s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.041s), StrongSORT:(0.010s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.040s), StrongSORT:(0.010s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.040s), StrongSORT:(0.010s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.040s), StrongSORT:(0.011s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.039s), StrongSORT:(0.011s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.041s), StrongSORT:(0.011s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.043s), StrongSORT:(0.011s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.040s), StrongSORT:(0.010s)
0: 480x640 2 persons, 1 cup, 1 chair, Done. YOLO:(0.041s), StrongSORT:(0.011s)
```

**Comment by salazarvalverdefd** [comment]
I used this command to export:

    python3 reid_export.py --weights ./weights/osnet_x0_25_msmt17.pt --include onnx engine --device 0 --half

Result:

    TensorRT: export success, saved as weights/osnet_x0_25_msmt17.engine (1.8 MB)

And only return 1 features when test

Also I export yolov5 version and it works fine with default detect.py

    python3 export.py --weights yolov5n.pt --include onnx engine --device 0 --half

I didn't use simplify and dynamic tags, also I used default batch size 1, I am testing on a Jetson Nano 4GB

- I test your command:

      python3 reid_export.py --weights ./weights/osnet_x0_25_msmt17.pt  --include engine onnx --device 0 --dynamic --simplify --batch-size 10

It doesn't finish on Jetson Nano

- I test your command batch size 2:

      python3 reid_export.py --weights ./weights/osnet_x0_25_msmt17.pt  --include engine onnx --device 0 --dynamic --simplify --batch-size 2

  Result Error when found 3 objects, it means that batch size limit number of objects allowed to strongsor?

      bbox_xywh torch.Size([3, 4])
      features torch.Size([2, 512])
      bbox_tlwh torch.Size([3, 4])

Remember with previous version don't have this issue, or it is correct that batch size limit max number of objects to predict in strongsort?

**Comment by mikel-brostrom** [comment]
> It doesn't finish on Jetson Nano

Could you provide the error?

**Comment by salazarvalverdefd** [comment]
I used this command to export I didn't use dynamic flag

    python3 reid_export.py --weights ./weights/osnet_x0_25_msmt17.pt --include onnx engine --device 0 --half

But get a error described in the start of the issue when I have 2 or more predictions, I understand if put dynamic flag I need to put maximum batch size argument, but if I didn't put this flag (no dynamic) then I need to put batch size limit too?

I write this issue because it work normally in a previous version, using no dynamic and default batch size.

If you said that It is necessary put maximum batch size when export dynamic or not dynamic model, I can use the previous version to do my process normally, because this work for me, but I think this is maybe an issue.

Thanks for your help!

**Comment by mikel-brostrom** [comment]
> I write this issue because it work normally in a previous version, using no dynamic and default batch size.

Ok, thanks for pointing this out, will check this out.

With the current state of the repo however, if you want a TensorRT model that can take a minimum of three detections as an input you have to export it like this:

```bash
python3 reid_export.py --weights ./weights/osnet_x0_25_msmt17.pt --include onnx engine --device 0 --dynamic --simplify --batch-size 3
```

to be on the safe side, this is to be able to accommodate for more inputs, then you should increase `--batch-size`
