### ISSUE TITLE
How to keep the same id for the same person in multiple videos?

### ISSUE THREAD

**Issue by wujoho** [mikel-brostrom/Yolov5_StrongSORT_OSNet#541]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

For example, in video 1, there are 3 people, person A (with id=1), person B (with id=2), and person C (with id=3); in video 2, there are only two people, A and C, questions:
1. is it possible to let A and C in video 2 to get the same id as in video 1, i.e., A's id=1, C's id=3?
2. if possible, what are the main steps that need to be implemented in order to achieve that?
Thanks

**Comment by mikel-brostrom** [comment]
Sorry , this is not supported at the moment

**Comment by wujoho** [comment]
Hi Mike, do you mean this functionality is not supported in this repo, or you believe such kind of functionality is not supported by other public repo either?
Is it due to it's too hard to achieve that at current stage?
