### ISSUE TITLE
Long term occlusion

### ISSUE THREAD

**Issue by Stephen-Ning** [mikel-brostrom/Yolov5_StrongSORT_OSNet#542]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

One person in the video I tested was blocked for a long time. How can I improve this? (Is it to adjust his T_LOST value?) Do you have any suggestions?

**Comment by mikel-brostrom** [comment]
> T_LOST

???

You can increase the max lifetime of an object without being associated:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/52c82aabca110d89fcc13854b5056cae7d16bdc2/strong_sort/configs/strong_sort.yaml#L7

**Comment by Stephen-Ning** [comment]
> > T_LOST
> 
> ？？？
> 
> 您可以在不关联的情况下增加对象的最大生命周期：
> 
> https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/52c82aabca110d89fcc13854b5056cae7d16bdc2/strong_sort/configs/strong_sort.yaml#L7
Thank you for your reply. I'll try to solve it.

**Comment by Stephen-Ning** [comment]
Thank you for your reply. I'll try to solve it.

**Comment by Stephen-Ning** [comment]
![479df799ead2f40d9f9470f0f6fd7bb](https://user-images.githubusercontent.com/108001646/192294902-f461ef14-a2cf-4fa5-93f5-c69dce2bd1e0.jpg)

**Comment by Stephen-Ning** [comment]
![479df799ead2f40d9f9470f0f6fd7bb](https://user-images.githubusercontent.com/108001646/192295276-b55df640-e3dd-4ffb-b82e-5e2de91d356d.jpg)
![31e2e82c673bc5fbafa76910df452b0](https://user-images.githubusercontent.com/108001646/192295290-174fd11e-3aef-4733-be14-9e4eb2fe71fa.jpg)

**Comment by mikel-brostrom** [comment]
Just out of curiosity. What are you using the repo for? :)

**Comment by westlinkin** [comment]
Hello,

What is the `MAX_AGE` unit, I changed it from 30 to 300, and the result seems the same.

**Comment by mikel-brostrom** [comment]
It is impossible to tell what this value should be without analyzing the video you run the tracker on
