### ISSUE TITLE
Is it possible to track an object when it's moving out of the frame and then move in again?

### ISSUE THREAD

**Issue by westlinkin** [mikel-brostrom/Yolov5_StrongSORT_OSNet#544]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Is it possible to track an object when it's moving out of the frame and then move in again? The object always gets a new ID. If an object moves out of the video frame for 2 seconds and then moves in again, how can the algorithm assign the same ID? 

Thanks in advance.

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/542
