### ISSUE TITLE
Does the use of a person re-ID affect tracking?

### ISSUE THREAD

**Issue by ZePinto99** [mikel-brostrom/Yolov5_StrongSORT_OSNet#546]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi, it is my understanding that YOLO does the detection and StrongSORT does the tracking. How is the OSNet (torchreid person re-ID CNN) being used? And the fact that a person re-ID is being used dosen't afect the tracking in other classes?

**Comment by mikel-brostrom** [comment]
> it is my understanding that YOLO does the detection and StrongSORT does the tracking

Yes, that is right

> How is the OSNet (torchreid person re-ID CNN) being used?

Source: https://arxiv.org/pdf/2202.13514.pdf

![Screenshot from 2022-09-27 08-01-04](https://user-images.githubusercontent.com/18719680/192445201-783c80b3-7319-4cb4-8f82-892347601463.png)

Instead of ResNeSt50 you have OSNet in this repo

> And the fact that a person re-ID is being used dosen't afect the tracking in other classes?

I don't understand this question

**Comment by ZePinto99** [comment]
Thanks for the reply! 
What I meant by "And the fact that a person re-ID is being used dosen't afect the tracking in other classes?" was since the model that replaced the ResNeSt50 is a person re-ID model if it affects tracking results for other objects other than people. 

![image](https://user-images.githubusercontent.com/49788794/192478040-54a480fa-b29d-405b-a632-134cd8e952a4.png)

**Comment by mikel-brostrom** [comment]
Aha, yes. OSNet is trained on people only. So it won't work equally good for other classes than people

**Comment by ZePinto99** [comment]
Thanks for the help!
