### ISSUE TITLE
A question about Strongsort

### ISSUE THREAD

**Issue by Stephen-Ning** [mikel-brostrom/Yolov5_StrongSORT_OSNet#547]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello, why don't you use Strongsort's plug-ins (AFLink and GSI)?

**Comment by mikel-brostrom** [comment]
Because is is a post-processing step. I only focus on real-time tracking in this repo

**Comment by Stephen-Ning** [comment]
> 因为是后处理步骤。我只关注这个 repo 中的实时跟踪
OK, thank you for your reply! Can I use these plug-ins in this project to improve my tracking results?

**Comment by mikel-brostrom** [comment]
Sure. You can use the ones provided by the official repo: https://github.com/dyhBUPT/StrongSORT

**Comment by Stephen-Ning** [comment]
> Sure. You can use the ones provided by the official StrongSORT repo: https://github.com/dyhBUPT/StrongSORT

Thank you!Your project has helped me a lot.
