### ISSUE TITLE
Object movement direction is opposite in laptop camera?

### ISSUE THREAD

**Issue by wujoho** [mikel-brostrom/Yolov5_StrongSORT_OSNet#549]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

When open camera app in my laptop (Windows 10), object movement direction is the same in camera, but when running `python track.py --source 0` the object movement direction in camera is opposite, i.e., if my figures move left, in camera the figure move right, how to keep the movement direction the same in camera when running `python track.py --source 0`? thanks

**Comment by mikel-brostrom** [comment]
Add this:

`im0 = cv2.flip(im0, 1)`

before `imshow` in `track.py`

**Comment by wujoho** [comment]
Thanks, it works.
I added it just after line `p, im0, _ = path[i], im0s[i].copy(), dataset.count` so that the following drawing box and text would be on the flipped image.

**Comment by wujoho** [comment]
Hi Mike, noticed another issue here, I was running `python track.py --source 0 --class 0`, the detected person (myself) was moving to the same direction on result video after adding `im0 = cv2.flip(im0, 1)`, but the drawn boxes and text were still not flipped, same position as without using the new added flip line of code, which means the box position was already calculated before flipping, but I thought I have put the line `im0 = cv2.flip(im0, 1)` as early as possible. Any further suggestion please?

**Comment by samihormi** [comment]
> ### Search before asking
> * [x]  I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.
> 
> ### Question
> When open camera app in my laptop (Windows 10), object movement direction is the same in camera, but when running `python track.py --source 0` the object movement direction in camera is opposite, i.e., if my figures move left, in camera the figure move right, how to keep the movement direction the same in camera when running `python track.py --source 0`? thanks

Add *`im = cv2.flip(im, 1)`* to [update()](https://github.com/ultralytics/yolov5/blob/91a81d48fa4e34dbdbaf0e45a1f841c11216aab5/utils/dataloaders.py#L360) in **dataloader.py** right after _**if success:**_

```
def update(self, i, cap, stream):
        # Read stream `i` frames in daemon thread
        n, f, read = 0, self.frames[i], 1  # frame number, frame array, inference every 'read' frame
        while cap.isOpened() and n < f:
            n += 1
            # _, self.imgs[index] = cap.read()
            cap.grab()
            if n % read == 0:
                success, im = cap.retrieve()
                if success:
                    im = cv2.flip(im, 1)
                    self.imgs[i] = im
                else:
                    LOGGER.warning('WARNING: Video stream unresponsive, please check your IP camera connection.')
                    self.imgs[i] = np.zeros_like(self.imgs[i])
                    cap.open(stream)  # re-open stream if signal was lost
            time.sleep(0.0)  # wait time
```
