### ISSUE TITLE
Do the proposed tracking method combine appearance features and spatial features?

### ISSUE THREAD

**Issue by pouryajafarzadeh** [mikel-brostrom/Yolov5_StrongSORT_OSNet#550]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Do the proposed method extract the embedding vector (as an appearance feature) for different objects such as car, bike, etc?
And also use the spatial feature for the Kalman filter?

**Comment by mikel-brostrom** [comment]
Yes

**Comment by mikel-brostrom** [comment]
@
