### ISSUE TITLE
Crop 1 image for every new obect

### ISSUE THREAD

**Issue by spinxi** [mikel-brostrom/Yolov5_StrongSORT_OSNet#554]
### Search before asking

- [x] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Well I'm facing some issues about cropping from videos, when cropping is set to True, it does its job, but it exports detected objects from every frame of video (well, it's logical, in every frame it sees new object detections), but I need to export 1 cropped image for every new object. For example if the first 3 second of video there is 1 object with for example ID: 1, I need 1 cropped image for that object, if there appears another object, I need second 1 crop for that new object. Is there any suggestions how to make it workable

**Comment by mikel-brostrom** [comment]
You would need to keep track of which detected objects you have stored crops of, so that you don't store them again. This:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/8efea8b44eb9b148cbe50d4b9c7458ba112fef73/track.py#L238

Could be updated by:

```python
if save_crop and id is not in id_list_of_stored_crops:
...
```
