### ISSUE TITLE
frame by frame

### ISSUE THREAD

**Issue by Yung-Chih-Lo** [mikel-brostrom/Yolov5_StrongSORT_OSNet#556]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

How to track frame by frame? Because I want to use the real-time video of the CCTV camera, and I extracts every frame from it, I know that at least two frames are needed. So I don't know if this will work.

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet#tracking-sources
