### ISSUE TITLE
How to speed up track.py running by analyzing fewer frames?

### ISSUE THREAD

**Issue by wujoho** [mikel-brostrom/Yolov5_StrongSORT_OSNet#557]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

With limited CPU/Memory/GPU resources, I thought might be able to speed up the running by only analyzing half of the frames, for example, only analyzing the frames with odd index, a 30 FPS 10 seconds video, there are 300 frames in total, if only analyzing the odd frames, only 150 frames need to be analyzed, guess would double up the speed.
Is this feasible in this project? if it doesn't support such kind of feature currently, would you suggest to use another tool like FFmpeg to edit the video first by extract the odd frames to generate a new source video which includes 5 seconds with same 30 FPS? thanks

**Comment by mikel-brostrom** [comment]
You can process the video in many ways. I would start with:

- Resize the video to a smaller resolution, specially if you perform inference at 640 anyways
- If you have a video with high FPSs you can try to remove some of the frames

**Comment by wujoho** [comment]
Hi Mike, thanks for your suggestions, I found they are helpful, each one improved the speed to process the video and still keep the inference result almost the same.
