### ISSUE TITLE
How to speed up track.py running by using more hardware resources?

### ISSUE THREAD

**Issue by wujoho** [mikel-brostrom/Yolov5_StrongSORT_OSNet#558]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

When running track.py against a 10 minutes video (25 FPS, 1920x1080), my laptop (see below resources image) took around 25 minutes to finish, I saw the laptop's hardware resources are not fully utilized, any suggest for speed up the running by using more hardware resources from the laptop please? thanks

![image](https://user-images.githubusercontent.com/12386794/194852003-cff1c28d-866d-4da3-904b-b6064d68892f.png)

**Comment by wujoho** [comment]
I have installed CUDA ([link](https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local)) and noticed the speed improvement vs. running on CPU.

When running `python track.py`, the terminal also showed the below log:

> YOLOv5  2022-9-24 Python-3.8.9 torch-1.12.1+cu113 CUDA:0 (Quadro T1000, 4096MiB)
> 
> Fusing layers... 
> YOLOv5m6 summary: 378 layers, 35704908 parameters, 0 gradients
> 1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)

so I assume it was using GPU?

**Comment by mikel-brostrom** [comment]
> so I assume it was using GPU?

Looks like it now :smile:

**Comment by wujoho** [comment]
but even the log showed it was using GPU, the speed was slow and hardware resources were not fully utilized, any suggestion about how to use more hardware resources to improve the speed please?

**Comment by mikel-brostrom** [comment]
The models used in this repo are small, they won't fill your GPU computationally-wise not memory-wise. I suggest you to export the models to a HW friendly framework which suits you needs:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/wiki/ReID-multi-framework-model-export

**Comment by wujoho** [comment]
Hi Mike,
I am not understand the above suggestion, could you please add more details, or relevant information to help me understand:
1. What is "export the models", is it for better utilizing the hardware?
2. when need to consider exporting the models?
3. Export which models?
4. After exporting the models, what to do with the exported models?

Tried to run the below code according to your mention link above:
`python reid_export.py --weights weights/yolo5m6.pt --include torchscript, onnx, openvino, engine`
but got the below errors:

> strong_sort/deep/reid\torchreid\metrics\rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
>   warnings.warn(
> YOLOv5  2022-9-24 Python-3.8.9 torch-1.12.1+cu113 CPU
> 
> weights\yolo5m6.pt
> strong_sort/deep/reid\torchreid\utils\tools.py:43: UserWarning: No file found at "weights\yolo5m6.pt"
>   warnings.warn('No file found at "{}"'.format(fpath))
> Traceback (most recent call last):
>   File "reid_export.py", line 332, in <module>
>     extractor = FeatureExtractor(
>   File "C:\Projects\tracker\strong_sort\deep\reid\torchreid\utils\feature_extractor.py", line 71, in __init__  
>     model = build_model(
>   File "strong_sort/deep/reid\torchreid\models\__init__.py", line 114, in build_model
>     raise KeyError(
> KeyError: "Unknown model: None. Must be one of ['resnet18', 'resnet34', 'resnet50', 'resnet101', 'resnet152', 'resnext50_32x4d', 'resnext101_32x8d', 'resnet50_fc512', 'se_resnet50', 'se_resnet50_fc512', 'se_resnet101', 'se_resnext50_32x4d', 'se_resnext101_32x4d', 'densenet121', 'densenet169', 'densenet201', 'densenet161', 'densenet121_fc512', 'inceptionresnetv2', 'inceptionv4', 'xception', 'resnet50_ibn_a', 'resnet50_ibn_b', 'nasnsetmobile', 'mobilenetv2_x1_0', 'mobilenetv2_x1_4', 'shufflenet', 'squeezenet1_0', 'squeezenet1_0_fc512', 'squeezenet1_1', 'shufflenet_v2_x0_5', 'shufflenet_v2_x1_0', 'shufflenet_v2_x1_5', 'shufflenet_v2_x2_0', 'mudeep', 'resnet50mid', 'hacnn', 'pcb_p6', 'pcb_p4', 'mlfn', 'osnet_x1_0', 'osnet_x0_75', 'osnet_x0_5', 'osnet_x0_25', 'osnet_ibn_x1_0', 'osnet_ain_x1_0', 'osnet_ain_x0_75', 'osnet_ain_x0_5', 'osnet_ain_x0_25']"

Thanks

**Comment by mikel-brostrom** [comment]
Sorry for my late answer @wujoho 

> What is "export the models", is it for better utilizing the hardware?

Short answer. Yes

> when need to consider exporting the models?

What hardware to run on GPU, CPU (android/desktop)

> Export which models?

Both Yolo and ReID

> After exporting the models, what to do with the exported models?

Use them as weights for inference
