### ISSUE TITLE
Where did you implement StrongSORT components?

### ISSUE THREAD

**Issue by htdung167** [mikel-brostrom/Yolov5_StrongSORT_OSNet#559]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi, 
I researched and read articles about StrongSORT and I found StrongSORT has components like ECC, NSA Kalman,.. And when i read your code, I just found ECC's code.
Can you show me where you implemented the other components (NSA Kalman, EMA, Vanilla Matching)? 
Sorry if this question seems stupid.

**Comment by leduy99** [comment]
having the same question :D I don't see these components that come from StrongSORT too

**Comment by mikel-brostrom** [comment]
Please look closer. Compare the original repo components to this one. Vanilla matching:

https://github.com/dyhBUPT/StrongSORT/blob/90e954740b889ccbc2d568e1fbedafed89b60802/deep_sort/linear_assignment.py#L127

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/d4306deac21c0c32ae83c90527a3d706540400e7/trackers/strong_sort/sort/linear_assignment.py#L118

Good luck finding the rest :)

**Comment by gyh420** [comment]
have you find nsa?
