### ISSUE TITLE
Show results from source N only when using multiple sources

### ISSUE THREAD

**Issue by spinxi** [mikel-brostrom/Yolov5_StrongSORT_OSNet#561]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Well, I need to separate **im0** in track.py for multi streaming
```
            # if show_vid:
            #     cv2.imshow(str(p), im0)
            #     cv2.waitKey(1)  # 1 millisecond
```
For example I'm running streams.txt with 2 streaming urls , it opens 2 windows for all these streamings, But I need to open up only second streaming windows.

 **Any hint would be appreciated**

**Comment by mikel-brostrom** [comment]
```python
if show_vid and i == 1:  # 0 would be first tream, 1 second and so on...
```

**Comment by spinxi** [comment]
You're my hero
