### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'xxx/Yolov5_StrongSORT_OSNet/weights'

### ISSUE THREAD

**Issue by hanifizzudinrahman** [mikel-brostrom/Yolov5_StrongSORT_OSNet#562]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

FileNotFoundError: [Errno 2] No such file or directory: 'xxx/Yolov5_StrongSORT_OSNet/weights'

### Minimal Reproducible Example

this error happen when i run
```
python track.py --source "../test_videos/xxx.mp4" --yolo-weights yolov5s.pt --img 640 --save-vid --show-vid
```

I think, this is easy to be solved

**Comment by sabdha** [comment]
I think you need to create a folder called weights inside the Yolov5_StrongSort_OSNet. I have done the same thing for another version of yolo, but dont remember exactly which one.

**Comment by neo133** [comment]
I solved this issue by creating a folder named "weights" inside the downloaded repo and the command ran without any errors. Perhaps you could try the same and check.

**Comment by mikel-brostrom** [comment]
Hmm, that folder should be created automatically. Will double check

**Comment by sabdha** [comment]
I am facing this in colab  and created weight directory but While running track.py in jetson nano with Ubuntu there is no issue.

**Comment by mikel-brostrom** [comment]
This is not an issue. The CI pipeline passes and it has no weights folder

**Comment by andrerivas** [comment]
> 



> I solved this issue by creating a folder named "weights" inside the downloaded repo and the command ran without any errors.

Thanks! I had this exact same issue and this solved it for me too.

**Comment by 2019UCP1350** [comment]
Thanks! I had this same issue, and this solved it for me.

**Comment by mmarada** [comment]
This is still an issue. Creating a weights folder solved it for me! @mikel-brostrom

**Comment by nschmidtg** [comment]
Here MacOS M2. Manually created the folder `/examples/weights` solved the issue.
