### ISSUE TITLE
GPU usage && unmatched keys or layer size for .weights

### ISSUE THREAD

**Issue by spinxi** [mikel-brostrom/Yolov5_StrongSORT_OSNet#563]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Well, first issue is this

`** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']`

Every time I run track.py, I get that warning. 

Second one is GPU usage for rtsp:// streaming, 2-3 sec delay .
It runs :

`YOLOv5  2022-10-7 Python-3.9.13 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)`

But GPU is mostly 0%. Any ideas? 

### Image
![gpu usage](https://user-images.githubusercontent.com/50767516/195903257-cc7f5332-a022-4bba-a5bb-8573fd5653c6.PNG)

**Comment by mikel-brostrom** [comment]
The discarded layers are ok. It is the normal behavior of the repo. 

Do you have CUDA installed? What do you get when running `nvidia-smi `

**Comment by spinxi** [comment]
![nvidia smi](https://user-images.githubusercontent.com/50767516/196155465-d33d7089-1562-4f59-8f8b-886cd6840d85.PNG)


Also 
```
===torch.cuda.is_available()
===True
```

**Comment by mikel-brostrom** [comment]
Aha, okay so you are running on GPU. Then the frame retrieval from the stream is the issue. This is only fixable if you control over the stream

**Comment by spinxi** [comment]
Well, will make a research on it definitelly, but it also shows the same result on a simle video. Still can't figure out the problem. GPU doesn't get more than 3%.

P.S (out of content): I'm willing to deploy your repo on azure web app, that runs about 7 security cameras RTSP:// . What will be your minimum requirements of server for that (if you have some info bout it)

**Comment by mikel-brostrom** [comment]
> Still can't figure out the problem. GPU doesn't get more than 3%

It is clear by this:

`YOLOv5 2022-10-7 Python-3.9.13 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)`

that you are running on GPU. So, I guess it is a stream problem.

> I'm willing to deploy your repo on azure web app, that runs about 7 security cameras RTSP:// . What will be your minimal and recommended requirements of server for that

The lower the FPSs of your streams the cheaper the virtual machine that you will need to set up as a cheaper GPU+CPU combination could be an option for handling the data at that speed. GPU memory may be an issue as the detection process is batched. Larger image size for inference will require larger GPU memory.
