### ISSUE TITLE
No such file or directory: 'strong_sort/configs/strong_sort.yaml' when runing on Google Colab

### ISSUE THREAD

**Issue by nadinewijaya** [mikel-brostrom/Yolov5_StrongSORT_OSNet#564]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Tracking

### Bug

My code
`!python track.py --source [insert path] --yolo-weights ../runs/train/exp3/weights/best.pt --strong-sort-weights ../strong_sort/deep/checkpoint/osnet_x0_25_market1501.pth --classes 0 1 --save-vid --save-txt`

I saved my yolov5 weights in drive and retrieved it from path: `../runs/train/exp3/weights/best.pt `

The strongsort weights were from: `../strong_sort/deep/checkpoint/osnet_x0_25_market1501.pth`

I cloned this repo, but got the following error of missing `stong sort yaml file` when I tried to run the code:

```Traceback (most recent call last):
  File "/content/Yolov5_DeepSort_Pytorch/track.py", line 328, in <module>
    main(opt)
  File "/content/Yolov5_DeepSort_Pytorch/track.py", line 323, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/Yolov5_DeepSort_Pytorch/track.py", line 117, in run
    cfg.merge_from_file(config_strongsort)
  File "/content/Yolov5_DeepSort_Pytorch/strong_sort/utils/parser.py", line 24, in merge_from_file
    with open(config_file, 'r') as fo:
FileNotFoundError: [Errno 2] No such file or directory: 'strong_sort/configs/strong_sort.yaml'



### Environment

- YOLO: YOLOv5 🚀 v6.2-183-gc98128f Python-3.7.14 torch-1.12.1+cu113 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)
- StrongSORT: osnet_x0 _25_market1501.pth

### Minimal Reproducible Example

_No response_

**Comment by mikel-brostrom** [comment]
Have you checked the official Colab?

https://colab.research.google.com/drive/18nIqkBr68TkK8dHdarxTco6svHUJGggY?usp=sharing

**Comment by nadinewijaya** [comment]
Hi Mikel,

The code ran perfectly with the official Colab but not when I've cloned the repo in a new Colab file. 

Thank you for the help!
