### ISSUE TITLE
ECC warp_matrix bug

### ISSUE THREAD

**Issue by wsw321** [mikel-brostrom/Yolov5_StrongSORT_OSNet#566]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

if (src.any() or dst.any() is None):
            return None, None
In Yolov5_StrongSORT_OSNet/strong_sort/sort/track.py
Thanks for your wonderful work! I met a problem, in this judgment statement, it seems always true. Then it always return None.

**Comment by wsw321** [comment]
Even if src is not null and dst is not null, this statement still returns none.

**Comment by mikel-brostrom** [comment]
The statement is only false the first frame of the video. This is because two images are needed for warping. src and dst are initialized as None

**Comment by wsw321** [comment]
> But it always returns "None,None" when the 2th, 3th, 4th ,... frame, so the ECC does not work.

**Comment by mikel-brostrom** [comment]
Now I see. Yes, seems like a bug.

**Comment by wsw321** [comment]
Thank you for your contribution and such an excellent repo.

**Comment by wsw321** [comment]
In addition, can I use this wonderful repo for academic purposes? Thank you very much.

**Comment by mikel-brostrom** [comment]
> In addition, can I use this wonderful repo for academic purposes?

Yes, that is not conflicting with the License in any way

**Comment by fcakyon** [comment]
> Now I see. Yes, seems like a bug.

Is this bug fixed in the repo?

Thanks for the great source!

**Comment by wsw321** [comment]
> > Now I see. Yes, seems like a bug.
> 
> Is this bug fixed in the repo?
> 
> Thanks for the great source!

"       if src.any() is None: 
            return None, None
        if dst.any() is None: 
            return None, None" 

Each individual judgment will activate ECC module.

**Comment by fcakyon** [comment]
@wsw321 do you know why ECC is disabled in this project? https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/df98545056e7efbb3c206214b932911a325771c7/track.py#L179

How can I activate it?

**Comment by mikel-brostrom** [comment]
This is fixed. `git pull` and try again
