### ISSUE TITLE
Problems on saving results as a txt-file

### ISSUE THREAD

**Issue by RicTimeMuseum** [mikel-brostrom/Yolov5_StrongSORT_OSNet#572]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Tracking

### Bug

Hello, and I would like to report a problem here. 
When I run track.py on a number of images or on a single video with the "--save-txt" argument enabled, I found that the txt-format results starts from the **third** frame or image with detections, which means that the results of the very **first** and the **second** ones with detections are not exported. 

### Environment

- YOLO: YOLOv5 🚀 v6.1-318-g7215a0f torch 1.11.0+cu102 CUDA:1,2 (Tesla T4, 15110MiB)
- StrongSORT: osnet_x1_0_msmt17
- OS: CentOS 7.8.2003
- Python: 3.9.12
- ...

**Comment by mikel-brostrom** [comment]
No bug. It is the expected behavior. CHange it by setting your preferred value here:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/d4306deac21c0c32ae83c90527a3d706540400e7/trackers/strong_sort/configs/strong_sort.yaml#L8
