### ISSUE TITLE
A Bug: TensorRT: export failure: 'OSNet' object has no attribute 'model'?

### ISSUE THREAD

**Issue by GalSang17** [mikel-brostrom/Yolov5_StrongSORT_OSNet#576]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

When I use the osnet_x0_25_msmt17.pt model to transfer tensorrt, TensorRT: export failure: 'OSNet' object has no attribute 'model', onnx can be generated normally, and the reasoning of onnx model by track.py is also normal, but the generation of tensorrt keeps reporting errors

(py38) yangyang@ysd-18:~/Code/YOLOv5s/YOLOv5-SSORT$ python reid_export1.py --weights weights/osnet_x0_25_msmt17.pt --include onnx engine --device 3
YOLOv5 🚀 2022-10-26 Python-3.8.10 torch-1.9.1+cu111 CUDA:3 (NVIDIA GeForce RTX 3080 Ti, 12054MiB)

Successfully loaded pretrained weights from "weights/osnet_x0_25_msmt17.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

PyTorch: starting from weights/osnet_x0_25_msmt17.pt with output shape (1, 512) (3.1 MB)

starting export with onnx 1.8.0...
export success, saved as weights/osnet_x0_25_msmt17.onnx (0.8 MB)
run --dynamic ONNX model inference with: 'python detect.py --weights weights/osnet_x0_25_msmt17.onnx'

TensorRT: export failure: 'OSNet' object has no attribute 'model'

I hope to get your answers. By the way, we will provide the C++ deployment code with the tracing part later

### Environment

Pytorch:1.9.1
Cuda:11.1
TensorRT: 7.2.3
Python: 3.8.10
Onnx: 1.8.0 comes with
project code:latest

**Comment by mikel-brostrom** [comment]
Cannot reproduce. Use this command for export

python3 reid_export.py --include onnx openvino engine --device 0 --batch-size <your_input_size> --dynamic

**Comment by GalSang17** [comment]
> Cannot reproduce. Use this command for export
> 
> `python3 reid_export.py --include onnx openvino engine --device 0 --batch-size <your_input_size> --dynamic`
> 
> > By the way, we will provide the C++ deployment code with the tracing part later
> 
> Would love to see it!

I just tried your command, and the error will be as follows. In addition, I found that there are two definitions of export_engine functions in the reid_export.py file. I want to ask what is the difference?

(py38) yangyang@ysd-18:~/Code/YOLOv5s/YOLOv5-SSORT$ python reid_export1.py --include onnx engine --device 2 --batch-size 8 --dynamic
YOLOv5 🚀 2022-10-26 Python-3.8.10 torch-1.9.1+cu111 CUDA:2 (NVIDIA GeForce RTX 3080 Ti, 12054MiB)

Successfully loaded pretrained weights from "/home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias'] 

PyTorch: starting from /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.pt with output shape (8, 512) (3.1 MB)

starting export with onnx 1.8.0...
export success, saved as /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx (0.8 MB)
run --dynamic ONNX model inference with: 'python detect.py --weights /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx'

starting export with onnx 1.8.0...
export success, saved as /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx (0.8 MB)
run --dynamic ONNX model inference with: 'python detect.py --weights /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx'

TensorRT: starting export with TensorRT 7.2.3.4...
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] ERROR: (Unnamed Layer* 407) [Shuffle]: at most one dimension may be inferred
ERROR: onnx2trt_utils.cpp:1517 In function scaleHelper:
[8] Assertion failed: dims.nbDims == 4 || dims.nbDims == 5
Traceback (most recent call last):
  File "reid_export1.py", line 355, in <module>
    export_engine(model.eval(), im, f, False, args.half, args.dynamic, args.simplify, args.workspace, args.verbose)
  File "reid_export1.py", line 275, in export_engine
    raise RuntimeError(f'failed to load ONNX file: {onnx}')
RuntimeError: failed to load ONNX file: /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx

**Comment by mikel-brostrom** [comment]
```bash
(import_test2) ➜  Yolov5_StrongSORT_OSNet git:(master) ✗ python3 reid_export.py --include onnx openvino engine --device 0 --batch-size 3 --dynamic
YOLOv5 🚀 2022-10-21 Python-3.8.13 torch-1.12.1+cu102 CUDA:0 (Quadro P2000, 4032MiB)

Successfully loaded pretrained weights from "/home/mikel.brostrom/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

PyTorch: starting from /home/mikel.brostrom/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.pt with output shape (3, 512) (9.3 MB)

starting export with onnx 1.12.0...
/home/mikel.brostrom/Yolov5_StrongSORT_OSNet/trackers/strong_sort/deep/models/osnet.py:424: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if return_featuremaps:
export success, saved as /home/mikel.brostrom/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.onnx (0.9 MB)
run --dynamic ONNX model inference with: 'python detect.py --weights /home/mikel.brostrom/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.onnx'

starting export with onnx 1.12.0...
export success, saved as /home/mikel.brostrom/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.onnx (0.9 MB)
run --dynamic ONNX model inference with: 'python detect.py --weights /home/mikel.brostrom/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.onnx'

TensorRT: starting export with TensorRT 8.4.3.1...
[10/27/2022-10:57:00] [TRT] [I] [MemUsageChange] Init CUDA: CPU +190, GPU +0, now: CPU 1624, GPU 1400 (MiB)
[10/27/2022-10:57:01] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +6, GPU +2, now: CPU 1647, GPU 1402 (MiB)
reid_export.py:211: DeprecationWarning: Use set_memory_pool_limit instead.
  config.max_workspace_size = workspace * 1 << 30
[10/27/2022-10:57:01] [TRT] [I] ----------------------------------------------------------------
[10/27/2022-10:57:01] [TRT] [I] Input filename:   /home/mikel.brostrom/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.onnx
[10/27/2022-10:57:01] [TRT] [I] ONNX IR version:  0.0.7
[10/27/2022-10:57:01] [TRT] [I] Opset version:    13
[10/27/2022-10:57:01] [TRT] [I] Producer name:    pytorch
[10/27/2022-10:57:01] [TRT] [I] Producer version: 1.12.1
[10/27/2022-10:57:01] [TRT] [I] Domain:           
[10/27/2022-10:57:01] [TRT] [I] Model version:    0
[10/27/2022-10:57:01] [TRT] [I] Doc string:       
[10/27/2022-10:57:01] [TRT] [I] ----------------------------------------------------------------
[10/27/2022-10:57:01] [TRT] [W] onnx2trt_utils.cpp:369: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
TensorRT: Network Description:
TensorRT:       input "images" with shape (-1, 3, 256, 128) and dtype DataType.FLOAT
TensorRT:       output "output" with shape (-1, 512) and dtype DataType.FLOAT
TensorRT: building FP32 engine in /home/mikel.brostrom/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.engine
reid_export.py:239: DeprecationWarning: Use build_serialized_network instead.
  with builder.build_engine(network, config) as engine, open(f, 'wb') as t:
[10/27/2022-10:57:02] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +271, GPU +108, now: CPU 1922, GPU 1510 (MiB)
[10/27/2022-10:57:02] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +113, GPU +46, now: CPU 2035, GPU 1556 (MiB)
[10/27/2022-10:57:02] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.4.0
[10/27/2022-10:57:02] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[10/27/2022-10:57:25] [TRT] [I] Detected 1 inputs and 1 output network tensors.
[10/27/2022-10:57:25] [TRT] [I] Total Host Persistent Memory: 198736
[10/27/2022-10:57:25] [TRT] [I] Total Device Persistent Memory: 318976
[10/27/2022-10:57:25] [TRT] [I] Total Scratch Memory: 17920
[10/27/2022-10:57:25] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 0 MiB, GPU 0 MiB
[10/27/2022-10:57:25] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 150.576ms to assign 11 blocks to 234 nodes requiring 5113856 bytes.
[10/27/2022-10:57:25] [TRT] [I] Total Activation Memory: 5113856
[10/27/2022-10:57:25] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 2345, GPU 1690 (MiB)
[10/27/2022-10:57:25] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.4.0
[10/27/2022-10:57:25] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
[10/27/2022-10:57:25] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
[10/27/2022-10:57:25] [TRT] [W] The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
TensorRT: export success, saved as /home/mikel.brostrom/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.engine (1.5 MB)

OpenVINO: starting export with openvino 2022.2.0-7713-af16ea1d79a-releases/2022/2...
export success, saved as /home/mikel.brostrom/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17_openvino_model/ (1.4 MB)
```

**Comment by GalSang17** [comment]
> 
I tried the command you gave again, and the error is as follows：

(py38) yangyang@ysd-18:~/Code/YOLOv5s/YOLOv5-SSORT$ python reid_export1.py --include onnx engine --device 2 --batch-size 3 --dynamic
YOLOv5 🚀 2022-10-26 Python-3.8.10 torch-1.9.1+cu111 CUDA:2 (NVIDIA GeForce RTX 3080 Ti, 12054MiB)

Successfully loaded pretrained weights from "/home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias'] 

PyTorch: starting from /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.pt with output shape (3, 512) (3.1 MB)

starting export with onnx 1.8.0...
export success, saved as /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx (0.8 MB)
run --dynamic ONNX model inference with: 'python detect.py --weights /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx'

starting export with onnx 1.8.0...
export success, saved as /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx (0.8 MB)
run --dynamic ONNX model inference with: 'python detect.py --weights /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx'

TensorRT: starting export with TensorRT 7.2.3.4...
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] ERROR: (Unnamed Layer* 407) [Shuffle]: at most one dimension may be inferred
ERROR: onnx2trt_utils.cpp:1517 In function scaleHelper:
[8] Assertion failed: dims.nbDims == 4 || dims.nbDims == 5

TensorRT: export failure: failed to load ONNX file: /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx

But when I remove the dynamic batch and add half-precision inference, I can generate the engine file, but when I use this engine for inference, it will report an index exceeding error：

(py38) yangyang@ysd-18:~/Code/YOLOv5s/YOLOv5-SSORT$ python reid_export1.py --include onnx engine --device 2 --half
YOLOv5 🚀 2022-10-26 Python-3.8.10 torch-1.9.1+cu111 CUDA:2 (NVIDIA GeForce RTX 3080 Ti, 12054MiB)

Successfully loaded pretrained weights from "/home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

PyTorch: starting from /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.pt with output shape (1, 512) (3.1 MB)

starting export with onnx 1.8.0...
export success, saved as /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx (0.4 MB)
run --dynamic ONNX model inference with: 'python detect.py --weights /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx'

starting export with onnx 1.8.0...
export success, saved as /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx (0.4 MB)
run --dynamic ONNX model inference with: 'python detect.py --weights /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.onnx'

TensorRT: starting export with TensorRT 7.2.3.4...
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
TensorRT: Network Description:
TensorRT:       input "images" with shape (1, 3, 256, 128) and dtype DataType.HALF
TensorRT:       output "output" with shape (-1, 512) and dtype DataType.HALF
TensorRT:WARNING: --dynamic model requires maximum --batch-size argument
TensorRT: building FP16 engine in /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.engine
[TensorRT] INFO: Detected 1 inputs and 1 output network tensors.
TensorRT: export success, saved as /home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/weights/osnet_x0_25_msmt17.engine (1.0 MB)

Here is my inference script and its error：
python track1.py \
    --source testdata/test.avi \
    --tracking-method strongsort \
    --yolo-weights weights/yolov5l.engine \
    --appearance-descriptor-weights weights/osnet_x0_25_msmt17.engine \
    --show-vid \
    --track-vis \
    --half
(py38) yangyang@ysd-18:~/Code/YOLOv5s/YOLOv5-SSORT$ ./track.sh
track1: yolo_weights=[PosixPath('weights/yolov5l.engine')], appearance_descriptor_weights=weights/osnet_x0_25_msmt17.engine, tracking_method=strongsort, source=testdata/test.avi, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=2, show_vid=True, track_vis=True, save_txt=False, save_conf=False, save_crop=False, save_vid=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/track, name=exp, exist_ok=False, line_thickness=2, hide_labels=False, hide_conf=False, hide_class=False, half=True, dnn=False, eval=False
default message here: Parse error at "'+https:/'": Expected stringEnd
YOLOv5 \U0001f680 2022-10-26 Python-3.8.10 torch-1.9.1+cu111 CUDA:2 (NVIDIA GeForce RTX 3080 Ti, 12054MiB)

Loading weights/yolov5l.engine for TensorRT inference...
Loading weights/osnet_x0_25_msmt17.engine for TensorRT inference...
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1136, condition: profileMaxDims.d[i] >= dimensions.d[i]
Traceback (most recent call last):
  File "track1.py", line 339, in <module>
    main(opt)
  File "track1.py", line 334, in main
    run(**vars(opt))
  File "/home/yangyang/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "track1.py", line 202, in run
    outputs[i] = tracker_list[i].update(det.cpu(), im0)
  File "/home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/trackers/strong_sort/strong_sort.py", line 53, in update
    detections = [Detection(bbox_tlwh[i], conf, features[i]) for i, conf in enumerate(
  File "/home/yangyang/Code/YOLOv5s/YOLOv5-SSORT/trackers/strong_sort/strong_sort.py", line 53, in <listcomp>
    detections = [Detection(bbox_tlwh[i], conf, features[i]) for i, conf in enumerate(
IndexError: index 1 is out of bounds for dimension 0 with size 1

**Comment by mikel-brostrom** [comment]
First of all, your are not fulfilling the minimum requirements:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/bf2fb0fa801a98dff298e3f5a85dd2c93e439634/requirements.txt#L49
