### ISSUE TITLE
byte track result save-vid didn't save the corresponding class_id

### ISSUE THREAD

**Issue by captain0305** [mikel-brostrom/Yolov5_StrongSORT_OSNet#577]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

![image](https://user-images.githubusercontent.com/63387697/198245302-f91844c0-42f3-4a70-bb4c-13e490254738.png)

the byte track result just don't have the output[5] as the classid so it is all zeros in this output list.

below are the corresponding codes in track.py
![image](https://user-images.githubusercontent.com/63387697/198245671-7aef457b-8862-4795-a05d-bc2d0ed7b4c8.png)

below are the corresponding codes in byte_tracker.py
![image](https://user-images.githubusercontent.com/63387697/198246546-8b54fa0f-00f8-41da-8b95-72319dd4133c.png)

**Comment by mikel-brostrom** [comment]
This got solved today:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/bf2fb0fa801a98dff298e3f5a85dd2c93e439634/trackers/bytetrack/byte_tracker.py#L308

 `git pull` and try again
