### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by ilyas882** [mikel-brostrom/Yolov5_StrongSORT_OSNet#578]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Integrations

### Bug

track.py: error: unrecognized arguments: --yolo_weights /content/drive/MyDrive/best.pt

**Comment by mikel-brostrom** [comment]
`--yolo_weights` --> `--yolo-weights`
