### ISSUE TITLE
Classes' id don't match COCO's

### ISSUE THREAD

**Issue by a-freitas** [mikel-brostrom/Yolov5_StrongSORT_OSNet#580]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Tracking

### Bug

It's a minor bug, but it seems all ids are one less than in the COCO dataset list. It may be because background (id = 0) is not an option here.

### Environment

YOLOv5 🚀 2022-10-28 Python-3.10.8 torch-1.13.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3060, 12050MiB)

### Minimal Reproducible Example

´´´
python track.py --source input/cars.mp4 --yolo-weights yolov5m.pt --classes 7 # truck is actually class 8
´´´

**Comment by mikel-brostrom** [comment]
Classes start at 0

**Comment by a-freitas** [comment]
I'm just saying that the numbers are moved 1 place compared to the ones in the COCO list (https://gist.github.com/AruniRC/7b3dadd004da04c80198557db5da4bda), that's all.

**Comment by mikel-brostrom** [comment]
Sure, but there is no background class bounding-box for object detection. However, it  may be used for segmentation. The offsetting is stated in the README: https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet#filter-tracked-classes

**Comment by a-freitas** [comment]
Sorry! Didn't see that last comment below. I read the line of code written just above, where it mentions the classes cat and dog matching COCO's indexing.
