### ISSUE TITLE
Wrong tracked bounding box directions 

### ISSUE THREAD

**Issue by purvang3** [mikel-brostrom/Yolov5_StrongSORT_OSNet#585]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,

I am trying to run ByteTrack on custom dataset, where objects moving from top to bottom direction (⬇️) but when I see the output, tracked bounding boxes moving in ➡︎ directions. How can I solve this issue?

Thank you

**Comment by mikel-brostrom** [comment]
I have no idea what you mean. Your output video is rotated?

**Comment by purvang3** [comment]
exactly objects that I want to track is moving from top to down in my video but when I see my output, I see tracked bounding box are moving in left to right direction, even there is no object moving in that direction. let me know if it makes sense

**Comment by mikel-brostrom** [comment]
Cannot reproduce. Seems like you have made custom changes to the code.
I would recommend you to start from a clean slate.
