### ISSUE TITLE
Is ECC feature disabled?

### ISSUE THREAD

**Issue by fcakyon** [mikel-brostrom/Yolov5_StrongSORT_OSNet#586]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello,

Thanks for the great project! I have two questions.

1. I see there is an issue mentioning a potential bug on strong_sort ECC. Is it fixed or still present?

2. Is ECC features disabled now? If yes, is is temporarily disabled till the bug is fixed or is this repo not compatible with ECC feature?

**Comment by wsw321** [comment]
1. In fix_ecc branch, this bug has been fixed, but it has not been merged into the main branch.
2. This repo is perfectly compatible with the ecc algorithm.
3. If your code is downloaded from the main branch, you can change the original judgment code to judge each condition separately or without judging. Of course, the precondition is that the ECC option in the configuration file is True.

**Comment by fcakyon** [comment]
Thanks for the answer! Unfortunately it is not possible to merge the ecc-fix into main since the code diverged a lot since then https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/tree/ecc-fix

**Comment by mikel-brostrom** [comment]
ECC is a heavy operation, I usually deactivate it for experimentation as it is not giving too much of a boost. I must have deactivated it and not taken it back :smiling_face_with_tear: 

|  | HOTA | MOTA | IDF1 | 
| ------------- | ------------- | ------------- | ------------- |
| w ECC  | 54.391  | 60.301  |  69.427  |
| wo ECC | 54.337  |  60.179  |  69.374  |

**Comment by mikel-brostrom** [comment]
ECC is now activated again

**Comment by fcakyon** [comment]
> ECC is now activated again

Thanks a lot!
