### ISSUE TITLE
How to evaluate on custom tracking dataset? 

### ISSUE THREAD

**Issue by dariogonle** [mikel-brostrom/Yolov5_StrongSORT_OSNet#590]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,

 I have a YOLOv5 model, a video and its ground truth. I would like to evaluate YOLOv5 StrongSORT on this video but I do not know how to do it? Is there any tutorial, or someone can explain it to me?

Thank you in advance.

**Comment by mikel-brostrom** [comment]
The least painfull way has to be, to put you sequence inside MOT17 and specify that single sequence in the MOT subprocess

**Comment by mikel-brostrom** [comment]
I just had a look at `val.py`, there are more things that has to be done for custom evevaluation. I will have a look at this tomorrow

**Comment by dariogonle** [comment]
Thank you so much @mikel-brostrom. I guess this is a lot of work, but it would be perfect if it is posible to add a --gt and a --source to val.py. With --source you will be able to pass a video to val.py and generate the corresponding detections (tracking) with your own yolo model. With --gt you will be able to pass a .txt file to val.py and compare the result of tracking your custom video.

**Comment by mikel-brostrom** [comment]
I didn't have to change anything in `val.py` to get custom dataset evaluation working @dariogonle. I created a tutorial for how to prepare the data for evaluation:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/wiki/Evaluation-on-custom-tracking-dataset

Please, provide feedback! :smile:

**Comment by dariogonle** [comment]
Thank you so much @mikel-brostrom. I will be busy for a couple of days, but when I have some time I'll provide feedback

**Comment by C-C-Y** [comment]
@mikel-brostrom  Hi,I tried to evaluate custom dataset in this way, but there was an error, and I don't know how to solve this problem，Thank you in advance. 
![050363ea317b6b14ab1d5d5d3479901](https://user-images.githubusercontent.com/37317031/202133413-40029c5d-fec0-48e7-985e-ae1a26f26be2.png)

**Comment by mikel-brostrom** [comment]
Which file is not found @C-C-Y ?

**Comment by C-C-Y** [comment]
> 

Sorry, although I have solved the previous problem, there are still many problems later. I don't know why. I would like to ask if I can directly evaluate the tracking results using TrackEval.

**Comment by dariogonle** [comment]
Finally, I got some time to work with this @mikel-brostrom. I've having some trouble to carry out a custom tracking evaluation, so I decided to evaluate with MOT17. For my surprise, the val.py script is not working. Any idea? The MOT2017 is downloaded, as it can be seen in the image below.


![image](https://user-images.githubusercontent.com/80393891/202416248-90eb96d1-83f4-4806-9ef4-49dde4f4d4d1.png)

**Comment by mikel-brostrom** [comment]
This just got fixed. pull

**Comment by dariogonle** [comment]
Thank you so much @mikel-brostrom. I'm going to go on working with this project and I'll give you feedback with the custom dataset evaluation.

**Comment by dariogonle** [comment]
I have a question that I would like to ask you, @mikel-brostrom, if it is possible. How many classes are been used for the evaluation? Is it only using pedestrian class? If it is the case, how can I use all classes in the dataset?

**Comment by mikel-brostrom** [comment]
> How many classes are been used for the evaluation?

1, people

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/eab08d1a7bf4b3c63251e9400fe8fe6df6a1c977/val.py#L154

> If it is the case, how can I use all classes in the dataset?

Just delete this line of code

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/eab08d1a7bf4b3c63251e9400fe8fe6df6a1c977/val.py#L154

**Comment by dariogonle** [comment]
I've done what you said @mikel-brostrom, but when I comment that line and execute val.py I get this output.
CLASSES_TO_EVAL      : ['pedestrian']

Shouldn't any other line be deleted?

**Comment by mikel-brostrom** [comment]
Try setting `CLASSES_TO_EVAL` in the subprocess:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/eab08d1a7bf4b3c63251e9400fe8fe6df6a1c977/val.py#L177

As in this example:

https://github.com/JonathonLuiten/TrackEval/blob/ec237ec3ef654548fdc1fa1e100a45b31a6d4499/scripts/run_kitti_mots.py#L25

**Comment by dariogonle** [comment]
I've been trying to evaluate MOT17 with pedestrians and cars. For doing so, I modified Yolov5_StrongOSNet/val_utils/trackval/datasets/mot_challenge_2d_box.py. I change line 24 with 'CLASSES_TO_EVAL': ['pedestrian', 'car'], and line 71 with self.valid_classes = ['pedestrian', 'car']. I'm using yolov5n.pt as weights so I understand that car's id is 3. Therefore is not necessary to modify line 76.

With all this changes, I've run val.py getting this:
![image](https://user-images.githubusercontent.com/80393891/202713368-d5e4a934-b527-4b33-baa9-078320cc9fc7.png)

Why all car metrics are 0? Isn't it weird that car's dets are the same as pedestrians' dets? Is that because there aren't cars in MOT17 gt? If it is the case, how should we add more classes to the gt? Can you eval cars with MOT17?

Thank you in advance @mikel-brostrom.

**Comment by mikel-brostrom** [comment]
> Why all car metrics are 0?

I have never tried to evaluate on something different than MOT16, 17 and 20. So, I have no idea what is going on here.

If you are evaluating on kitti you may find this interesting:
https://github.com/JonathonLuiten/TrackEval/blob/ec237ec3ef654548fdc1fa1e100a45b31a6d4499/scripts/run_kitti_mots.py

**Comment by mikel-brostrom** [comment]
Follow this: https://github.com/mikel-brostrom/yolov8_tracking/wiki/How-to-evaluate-on-custom-tracking-dataset @Gamattention
