### ISSUE TITLE
Update yolov5 and wire --vid-stride

### ISSUE THREAD

**Issue by FObermaier** [mikel-brostrom/Yolov5_StrongSORT_OSNet#591]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar enhancement requests.

### Description

Update yolov5 dependency to at least https://github.com/ultralytics/yolov5/commit/1aea74cddbc78e7f79dac07090cb157dfc24dbcc and take advantage of the newly added --vid-stride parameter.

### Use case

This allows to run the track program only on every x-th frame which is sufficient in many use cases. Thus it will give an enormous performance boost.

**Comment by mikel-brostrom** [comment]
Good point! Will update this when it gets released with v6.3 which should be quite soon

**Comment by mikel-brostrom** [comment]
This is now available! Example usage:

`python3 track.py --source 0 --vid-stride 120`

Let me know if it works for you! :smile:
