### ISSUE TITLE
Cross camera tracking

### ISSUE THREAD

**Issue by faizan1234567** [mikel-brostrom/Yolov5_StrongSORT_OSNet#594]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar enhancement requests.

### Description

I want to use local camera tracklets generated by one of trackers such as bytetracker, strongsort, or ocstort in your repo. I want to generate global trajectries across cameras. I saw issue #370 that you are still working on cross camera reid. is there any update on it or cross camera tracking? how effectilvely one should use local tracklets to generate global trajectories? I will appreciate your help.

**Comment by mikel-brostrom** [comment]
Had to put this completely on hold due to lack of time and resources.

**Comment by mikel-brostrom** [comment]
The idea here is to:

1. Calibrate your set of cameras
2. Projection of people detections to transform image points from different cameras to a global ground plane for each frame
3. Use a clustering method or similar to get a unified understanding across all the cameras
4. Use this for motion cost
5. Take the average of the feature from each perspective, alternatively use a single camera source to extract features
6. Use this for appearance cost

**Comment by faizan1234567** [comment]
I didn't understand what you just said.

**Comment by mikel-brostrom** [comment]
Those are the steps to get multi-camera tracking to work with a unified understanding among all the cameras

**Comment by arturo-collado-rosell** [comment]
Ok but, what about the execution time? I made something similar using 9 cameras and I can not achieve real-time processing. I am working on a parallel implementation. Any suggestions @mikel-brostrom ? Thanks.

**Comment by mikel-brostrom** [comment]
Have you identified your bottleneck @arturo-collado-rosell?

**Comment by tgrmev** [comment]
> The idea here is to:
> 
>     1. Calibrate your set of cameras
> 
>     2. Projection of people detections to transform image points from different cameras to a global ground plane for each frame
> 
>     3. Use a clustering method or similar to get a unified understanding across all the cameras
> 
>     4. Use this for motion cost
> 
>     5. Take the average of the feature from each perspective, alternatively use a single camera source to extract features
> 
>     6. Use this for appearance cost

Which method do you recommend finding distance and feature extraction? I am planning to extract the features from point cloud but I could not be sure for that.

**Comment by mikel-brostrom** [comment]
If you have a point cloud you could take the average depth of the points within the 3D bounding box. For extracting features in point clouds nothing in this repo will be helpful. Check out 3D object detection in paperswithcode.com

**Comment by tgrmev** [comment]
> If you have a point cloud you could take the average depth of the points within the 3D bounding box. For extracting features in point clouds nothing in this repo will be helpful. Check out 3D object detection in paperswithcode.com

Now I decided not to use Point cloud, because of the hardware problem. I cropped the bounding boxed images and saved them into a file. After that in another python script, I compare this images by using SIFT algorithm. Additionally, I found the wolrd coordinate of each object  from their pixel coordinates. What is the next step and how can I merge my work with your repository output? How can I do re-identification for cross camera tracking? Thanks @mikel-brostrom.

**Comment by farukokumus** [comment]
Thanks for this repository @mikel-brostrom. I want also to do cross-tracking. You mentioned that we need to feature extraction. Should I use CNN feature extraction or basic feature extraction methods

**Comment by mikel-brostrom** [comment]
@tgrmev 

> What is the next step and how can I merge my work with your repository output?

Create a pull request

> How can I do re-identification for cross camera tracking?

Everything is clearly stated here: https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/594#issuecomment-1310624465

**Comment by mikel-brostrom** [comment]
@farukokumus 

> Should I use CNN feature extraction or basic feature extraction methods

Visual appearance is already calculated

**Comment by alaap001** [comment]
Hey, Any update here? 
I am looking for some ideas or any implementations. The goal is to identify if the human detected btw 4 camera streams is the same instead of having 4 instances of tracker and have 4 different IDs. Essentially multi-camera tracking problem.
