### ISSUE TITLE
Yolov5 .pt model to easily use it with loading the .pt model

### ISSUE THREAD

**Issue by WaniAthar** [mikel-brostrom/Yolov5_StrongSORT_OSNet#595]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

How to export the current model to the '.pt' model so that we can use it in the separate custom file just by loading it?

**Comment by mikel-brostrom** [comment]
I don't understand what you mean. All models downloaded automatically with this repo are `.pt` models

**Comment by WaniAthar** [comment]
> I don't understand what you mean. All models downloaded automatically with this repo are `.pt` models

I have a custom trained model which I want to use in tkinter with tracking.
I want my model to export as .pt (added strong sort), so that I dont have to use explicitly Strong sort, I want to load the model from hub and use it.

**Comment by mikel-brostrom** [comment]
What is the type of model you have? Is it for object detection?

**Comment by WaniAthar** [comment]
> What is the type of model you have? Is it for object detection? Is it Yolov5?

Yes yolov5

**Comment by mikel-brostrom** [comment]
THen you have a `.pt` model

**Comment by WaniAthar** [comment]
If I export the code to . tflite will it work?
If yes then how to export it to tflite, i tried it but got some errors

**Comment by mikel-brostrom** [comment]
The model is only doing a small part of the association process. So, no, it won't work

**Comment by WaniAthar** [comment]
Ok.. thanks for your time
