### ISSUE TITLE
How to  get the output video (processed video stream) and detection logs from track.py?

### ISSUE THREAD

**Issue by sleekmike** [mikel-brostrom/Yolov5_StrongSORT_OSNet#597]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello, 

Please does anyone know how to get the output video or processed video stream and detection logs from track.py?

I need to get the output video or processed frames(with detections and bounding boxes) and the detection logs as it is displayed on the terminal and pipe or stream them to an API .

**Comment by mikel-brostrom** [comment]
```python3 track.py --save-vid --save-txt```

**Comment by sleekmike** [comment]
Hello,
I think you did not understand me well, so let me explain more in detail.

Basically I am trying to stream video through my IP cam or webcam and processed using it using YOLOv5 and Strongsort  and then stream the processed video feed and detections in real time through an API endpoint.

So I modified track.py file and imported  it inside my API code, I am passing a video source(using webcam or IP stream link), and I want to get the processed frames or video in real-time so that I can stream to an endpoint in my API.

Already the processed video frame is available and displayed with opencv in the code below:


`# Stream results
im0 = annotator.result()
if show_vid:
      cv2.imshow(str(p), im0)
      cv2.waitKey(1)  # 1 millisecond
`

But I am trying to get im0 and some other detection logs out of the "run" function in track.py without interrupting the function or stopping detection and tracking operations

<img width="709" alt="run" src="https://user-images.githubusercontent.com/37389692/202041957-dd344e64-f775-40f5-b81c-aa89882249c8.png">

<img width="1091" alt="two" src="https://user-images.githubusercontent.com/37389692/202042027-966ffa79-da1b-4400-b548-e321f5143a09.png">

**Comment by sleekmike** [comment]
> python3 track.py --save-vid --save-txt

I have already used this command but its not what I am looking for, I want to be able to get processed frames and other data in realtime, and not afterwards.

I have tried to modify the "run" function and also use producer and consumer pattern to get these needed data out of run function or track.py but I have not been able to do so yet.
