### ISSUE TITLE
Enhance Performance

### ISSUE THREAD

**Issue by yamiefun** [mikel-brostrom/Yolov5_StrongSORT_OSNet#598]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar enhancement requests.

### Description

Hi,

I noticed that between yolo and strongsort, those temporary detections are moved from gpu back to cpu, and back to gpu again for appearance network. Is it possible to enhance performance by not moving those data between devices?

Thanks!

**Comment by mikel-brostrom** [comment]
Here are the CUDA bboxes moved to CPU:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/92cd8447b915e5aea87b398b787d60f1f0be95e7/track.py#L188

The original img is on CPU:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/92cd8447b915e5aea87b398b787d60f1f0be95e7/trackers/strong_sort/strong_sort.py#L133

Before ReID batched inference, the batch is moved to GPU:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/92cd8447b915e5aea87b398b787d60f1f0be95e7/trackers/strong_sort/reid_multibackend.py#L185

Yep, then the features are moved to CPU for distance calculation, which is not needed, this could be done on GPU

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/92cd8447b915e5aea87b398b787d60f1f0be95e7/trackers/strong_sort/reid_multibackend.py#L229

But then this result would need to be moved to CPU anyways.

**Comment by yamiefun** [comment]
Thanks very much for explaining the details. I'm trying to speedup the whole process including yolo and tracking. The yolo part can be done by converting the model to TensorRT, but I'm not sure how to accelerate the tracking part. Do you have any suggestion?
Thanks again for your great work!

**Comment by mikel-brostrom** [comment]
Convert the ReID model to TensorRT. That will give you the largest speedup
