### ISSUE TITLE
feature extraction training

### ISSUE THREAD

**Issue by JustinLibo** [mikel-brostrom/Yolov5_StrongSORT_OSNet#603]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Thanks for your work！

I want to detect and track the target is the rubik's cube constantly flipping in a scene, tracking the left and right hands and rubik's cube appearing in the video;

At present, I have the training weights at the end of yolov7 training, do I need to use StrongSORT for feature extraction training of the data set (because I noticed that the training in the code is mainly for person re-identification) to obtain the weight file? If necessary, how should I train? 

Thank you!

**Comment by mikel-brostrom** [comment]
Have you checked if this repo fulfills your tracking needs without any custom modification? Usually no extra training is needed for simple scenarios.

**Comment by JustinLibo** [comment]
I tried the following combination:
--yolo-weights uses yolov7's training weights file
--strong-sort-weights use the osnet_x0_25_market1501.pt file.

But the results were not satisfactory.
In my scene, there is a fixed camera to collect video from above, in which the left and right hands sometimes exceed the range of the camera for a few seconds, and sometimes the hand turning the Rubik's cube will be partially blocked by the cube for several frames. In both cases, the ID switching times of the left and right hands will change.

However, the recognition effect of partially occluded hands and Rubik's cube in yolov7 detection was not bad, so I was thinking that strongsort weight with more pertinence would have a better effect.

**Comment by mikel-brostrom** [comment]
Objects entering and exiting the field of view are one of the hardest cases for mono camera tracking. It does not feel that a different ReID model would make a lot of difference here. Maybe it is a Yolov7 issue. Hard to tell without a video to analyze.

**Comment by JustinLibo** [comment]
Yeah, you're right. 

I'm using your yolov7-strongsort repo and I have trained my own dataset used [FastReID](https://github.com/JDAI-CV/fast-reid) to extract feature and get a wight file.

But when I change the --strong-sort-weights, it shows Unknown model. In other issue, I notice you mentioned add model type in __model_types https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/325#issuecomment-1072599653.

But it still reminds me unknown model. Could you tell me how I can user custom StrongSort weight?

Thanks in advance!

![image](https://user-images.githubusercontent.com/39175411/203785815-41958612-9fa8-465a-a931-6fad817efb50.png)
![image](https://user-images.githubusercontent.com/39175411/203785971-64401d9d-657e-456f-8546-e0a53c138560.png)

**Comment by mikel-brostrom** [comment]
is your model trained with any of the architectures above?

**Comment by JustinLibo** [comment]
the pretrained model I uesd is resnet50-19c8e357.pth

**Comment by mikel-brostrom** [comment]
What is the name of the model you are trying yo load? It should contain `resnet50_....py` so that the model can load the weights into the right architecture

**Comment by JustinLibo** [comment]
Sorry, I don't quite understand what you mean.

The weight name I try to load is model_final (as shown in the figure above) which is trained from [FastReID](https://github.com/JDAI-CV/fast-reid), the pretrained model, as I said above, is resnet50-19c8e357.pth.

Could I just rename the weight file to resnet50.pt to run the code?

**Comment by mikel-brostrom** [comment]
Yes, just insert resnet50 in the name of your weights. Example: `resnet50_final.py`

**Comment by mikel-brostrom** [comment]
Was this solved @JustinLibo ?

**Comment by JustinLibo** [comment]
Sorry for the late reply.

I tried the above approach, but there was no improvement. The results are the same as when I didn't use the training weights. So I was looking for other ways to solve the problem.

Thank you for your patience!
