### ISSUE TITLE
Using strongsort.py 

### ISSUE THREAD

**Issue by uzumakinaruto19** [mikel-brostrom/Yolov5_StrongSORT_OSNet#604]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi , I've been trying to use the model with a yolov5 input. currently, I'm using Deepsort as my tracker and trying to use strong sort with OSnet. I found the strongsort.py in your repo and tried to use that but got lots of errors.

this is my main function
 ```
def main_func(input_data):

features = encoder(frame, boxs)
boxs = np.array(input_data['detections']) # data-type conversion
        curr_frame_people_count = len(boxs)
        boxs_new = []
        for bb in boxs:
            temp_x1 = bb[0]
            temp_x2 = bb[2]
            temp_y1 = bb[1]
            temp_y2 = bb[3]
            temp_p1 = convert1080_720((temp_x1,temp_y1)) 
            temp_p2 = convert1080_720((temp_x2,temp_y2)) 
            boxs_new.append([temp_p1[0],temp_p1[1],temp_p2[0],temp_p2[1]])

        boxs = boxs_new.copy()

        detections = [Detection(bbox, 1.0, feature)
                        for bbox, feature in zip(boxs, features)]
        # Run non-maxima suppression.
        boxes = np.array([d.tlwh for d in detections])
        scores = np.array([d.confidence for d in detections])
        indices = preprocessing.non_max_suppression(
            boxes, nms_max_overlap, scores)
        detections = [detections[i] for i in indices]

        tracker.predict()
        tracker.update(detections)

        track_ids_list = []
        trackid_location_center = []

        for track in tracker.tracks:
            if not track.is_confirmed() or track.time_since_update > 1:
                continue
```
          later this tracker is used to find certain metrics
                
input data contains the Yolov5 output in a JSON
so my question is how to change this code to use Strongsort tracker..?
PS: I know it's a dumb thing to ask but I've been trying for many days and made no progress

**Comment by mikel-brostrom** [comment]
The easiest would be to start from a clean slate, just follow:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet#installation
