### ISSUE TITLE
Add model from PyTorch Hub load

### ISSUE THREAD

**Issue by thihoangngocba** [mikel-brostrom/Yolov5_StrongSORT_OSNet#605]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi! How can I add a custom model using torch.hub.load() to work with your StrongSORT?
Thanks!

**Comment by mikel-brostrom** [comment]
Most of the code surrounding the tracking isn't neural network related. So `torch.hub.load()` is not an option.
