### ISSUE TITLE
Re-ID Feature Enhancement

### ISSUE THREAD

**Issue by Sirish07** [mikel-brostrom/Yolov5_StrongSORT_OSNet#608]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello @mikel-brostrom!

Thank you for your amazing work.

I am dealing with a system which has a single birds' eye view camera (entire scene in its FOV) and multiple zone-wise cameras (with limited FOV). The zone-wise cameras observe the person in a frontal view and the birds' eye view camera observe the person in a birds' eye view. As a result, the re-id features obtained from both the viewpoints aren't matching very reliably. Is there any way, where I can fuse the re-id features from multiple perspectives into an enhanced representation of the person? Thoughts?

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/594#issuecomment-1310624465

**Comment by Sirish07** [comment]
Yeah, I came across your comment. I was hoping if there were better ways to integrate features from different perspectives. Thank you for your time.

**Comment by mikel-brostrom** [comment]
You could concat the features from the different camera perspectives for an object before calculating the distance between the objects. By doing so you wouldn't loose any information. However, the computational cost would increase quite a lot
