### ISSUE TITLE
Cannot load the pth model file from ReID model zoo

### ISSUE THREAD

**Issue by tendrillion** [mikel-brostrom/Yolov5_StrongSORT_OSNet#610]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Cannot load the pth model file from ReID model zoo
acceptable suffix is ['.pt', '.torchscript', '.onnx', '_openvino_model', '.engine', '.mlmodel', '_saved_model', '.pb', '.tflite', '_edgetpu.tflite', '_web_model', '.xml']

**Comment by mikel-brostrom** [comment]
If you have downloaded the model manually you will need to change the termination manually as well. From `.pth` to `.pt`
