### ISSUE TITLE
Using pre-trained object detection model layer to extract features instead of FastReID

### ISSUE THREAD

**Issue by vocdex** [mikel-brostrom/Yolov5_StrongSORT_OSNet#613]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Thanks for sharing your code. My question might be related to #603 
I am trying to use it for tracking a plant in a greenhouse farm. I have trained YoloV5 bounding box detection and Detectron2 instance segmentation models. They both work pretty well.
Next, I want to use StrongSORT for tracking with the following combination:
1. Bounding boxes from Detectron2 instance segmentation model.
2. Feature maps for detected bounding boxes from the same Detectron2 instance segmentation layer by partially executing the model. I guess this should produce some feature maps for bounding boxes similar to what FastReId does.

My question is : will this work or do I need to train FastReId model?

**Comment by mikel-brostrom** [comment]
Sure, you can try it out. But notice, that those models are not meant to learn discriminative features, which not only capture different spatial scales but also encapsulate an arbitrary combination of multiple scales. Notice as well that the input to

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/5caab02c6fdfafb9f308d09b9a44136421e110c5/trackers/strong_sort/sort/nn_matching.py#L30

is an (N, M) matrix
