### ISSUE TITLE
Would it be possible to have just deepsort as an option?

### ISSUE THREAD

**Issue by ChrisRawstone** [mikel-brostrom/Yolov5_StrongSORT_OSNet#614]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar enhancement requests.

### Description

Hi, I am doing this project where I am comparing deepsort for different versions of yolo. Of the trackmethods available It seems that just normal deepsort is not an option. Is that correct or is there somewhere an easy way to turn on just deepsort.

### Use case

Comparing deepsort for different versions of yolo

**Comment by mikel-brostrom** [comment]
DeepSORT got upgraded to StrongSORT. So why not using StrongSORT for your project, which is the better version?

**Comment by ChrisRawstone** [comment]
Because we are looking only at the improvement that yolo gives. Upgrading from yolov3 to yolov5

**Comment by mikel-brostrom** [comment]
I am not planing to take DeepSORT back as it is quite an outdated tracking method (early 2017). If you still want to check the difference on it you can just checkout any of the following releases: https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/releases/tag/v1.0 and https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/releases/tag/v.2.0
