### ISSUE TITLE
No KF updates for detections without associations?

### ISSUE THREAD

**Issue by Stephen-Ning** [mikel-brostrom/Yolov5_StrongSORT_OSNet#615]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

When occlusion occurs for a long time (no occlusion target detection), the occlusion target track matching fails and cannot be updated. In the next few frames, kf will always predict (but not update, because there is no corresponding detection). Until the occluded object is detected and matched with the prediction of kf. Am I right?

**Comment by mikel-brostrom** [comment]
> Am I right?

Yes. We are looking into this and will add this feature promplty

**Comment by Stephen-Ning** [comment]
> > 我对吗？
> 
> 是的。我们正在对此进行调查，并将尽快添加此功能

The estimation of the occluded kf (updated without detection) may diverge, which makes it difficult to recover the occluded id.

**Comment by mikel-brostrom** [comment]
The branch:
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/tree/kf-pred-and-update-when-no-matching

The results:
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/wiki/Effect-of-KF-updates-ahead-for-tracks-with-no-associations,-on-MOT17

**Comment by Stephen-Ning** [comment]
Great work！For an occluded target (not detected), using kf update in advance is to update the kf estimation of its current frame with the detection before occlusion. Am I right?

**Comment by mikel-brostrom** [comment]
The state is updated by it's predicted state. So no, it is not updated constantly by the detection before occlusion

**Comment by Stephen-Ning** [comment]
> 如果没有观测支持，KF 将不可避免地发散。为了从遮挡中恢复，需要来自预测的足够好的速度估计。在这种情况下，速度当然是一种推断状态，因为检测没有来自 yolo 的速度。我看到的唯一选择是尝试从可以支持预测的输入图像中得出一个测量值，例如光流或类似的东西。你怎么看？
> 
> 编辑：我想到的另一件事是，当轨道没有关联时，也许可以增加轨道的噪声协方差？

You're right.

**Comment by mikel-brostrom** [comment]
Predictions for the unmatched tracks in white:

https://user-images.githubusercontent.com/18719680/205062044-4546752b-c48d-4f64-be3d-1b93be422932.mp4

**Comment by mikel-brostrom** [comment]
This has been merged after showing consistent boosts on MOT17

**Comment by Stephen-Ning** [comment]
> ， kf将观测避免恢复恢复恢复恢复恢复恢复，需要输入图像中得到一个测量值，例如光流或类似的东西。你怎么认为？
> 
> 编辑：我想到的另一件事是，当轨道没有关联时，也许可以增加轨道的噪声协方差？

Hello! I see that you have tried many kinds of Kalman filters in multi-target tracking. Is there any good effect?
