### ISSUE TITLE
Running track.py on mp4 results in slow video playback

### ISSUE THREAD

**Issue by mlongoria1** [mikel-brostrom/Yolov5_StrongSORT_OSNet#623]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I have been running the track.py on rtsp stream and the video plays as live, but when we run it on an MP4 then the video we see is not live but much slower. We have a 35-sec video and it takes 65 seconds to complete the play back. It is not choppy or skipping frames it is just playing in slow motion. So why if the "--source" is an MP4 video the playback is in slow motion but if the --source is webcam/rtsp the playback is pretty much live(as it should be)?

**Comment by mikel-brostrom** [comment]
Sorry, I need more details to help you out here. Are you running on GPU? What is the resolution of each source? How are you calling the tracker?

**Comment by mlongoria1** [comment]
Are you running on GPU:
Yes sir, 1050 TI

What is the resolution:
1080p but we have also tried on 640p video and the same issue stands.

How are you calling the tracker:
We are running from the command line, simply:
`python track.py --source ..\videos\symphony-35-secs-in.mp4 --yolo-weights .\yolov5\weights\crowdhuman_yolov5m.pt --show-vid`

Thank you for your help.

**Comment by mlongoria1** [comment]
I was looking a little closer at the MP4 file after you asked about the resolution. If I right-click on it and check the properties/details of the file, the width is 1920 and the height is 1080. But when the video has finished I get this output from your program and it's in slow motion.

`Speed: 1.1ms pre-process, 28.6ms inference, 4.0ms NMS, 2.3ms bytetrack update per image at shape (1, 3, 640, 640)`

Based on this output it leads me to believe that your program thinks it's a 640 video... I'm not sure about that but just thinking out loud.

Here is the output from the rtsp feed hope this helps. this is at normal playback speed(as expected)
`Speed: 1.2ms pre-process, 38.5ms inference, 2.7ms NMS, 0.4ms bytetrack update per image at shape (1, 3, 640, 640)`

**Comment by mikel-brostrom** [comment]
> If I right-click on it and check the properties/details of the file, the width is 1920 and the height is 1080. But when the video has finished I get this output from your program and it's in slow motion.

What is the FPS of your original video? You can find it under properties as well

**Comment by mikel-brostrom** [comment]
This is relevant because the tracking script assumes 30 FPS:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/90fd92422b0d93ac1ec2de44d768d9efcc4222ff/track.py#L248

**Comment by mlongoria1** [comment]
The FPS is at 30.1 FPS

![mRemoteNG_NH0t3s1Q1u](https://user-images.githubusercontent.com/38320817/205663895-47a9b23f-0cd5-4955-8148-c0a73dbe1a10.png)

**Comment by mlongoria1** [comment]
> > If I right-click on it and check the properties/details of the file, the width is 1920 and the height is 1080. But when the video has finished I get this output from your program and it's in slow motion.
> 
> What is the FPS of your original video? You can find it under properties as well. Make sure that the FPS for the video are the same as what is passed to the video writer:
> 
> https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/90fd92422b0d93ac1ec2de44d768d9efcc4222ff/track.py#L250

I ran the test and Yes, the FPS for the video is the same. Inside the snapshot above the frame rate is 30.10 as viewed in the properties of the video and as you can see here I checked the fps variable at the line you specified and it is also 30.10 and some change.

![mRemoteNG_dXmTuRLybR](https://user-images.githubusercontent.com/38320817/206506555-8e572b05-e88a-4e75-bc34-627eace39b39.png)

Is there anything else we can check to figure out why this is happening?

Here is another video that I have seen this happen in and you can access it easily for testing. It's from another repo I was looking at before I found yours.
https://github.com/saimj7/People-Counting-in-Real-Time/tree/master/videos

**Comment by mikel-brostrom** [comment]
Seems like a problem with your video to me...

**Comment by anidh** [comment]
Hi @mlongoria1 I ran [this](https://github.com/saimj7/People-Counting-in-Real-Time/tree/master/videos) which you shared with us and I found that the video was playing perfectly fine without any issues. I have stitched the original video vs the output video and the two videos are identical in runtime and frame. Seems like there is some issue with the video files which you have.

**Comment by KevinGong2013** [comment]
> > > If I right-click on it and check the properties/details of the file, the width is 1920 and the height is 1080. But when the video has finished I get this output from your program and it's in slow motion.
> > 
> > 
> > What is the FPS of your original video? You can find it under properties as well. Make sure that the FPS for the video are the same as what is passed to the video writer:
> > https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/90fd92422b0d93ac1ec2de44d768d9efcc4222ff/track.py#L250
> 
> I ran the test and Yes, the FPS for the video is the same. Inside the snapshot above the frame rate is 30.10 as viewed in the properties of the video and as you can see here I checked the fps variable at the line you specified and it is also 30.10 and some change.
> 
> ![mRemoteNG_dXmTuRLybR](https://user-images.githubusercontent.com/38320817/206506555-8e572b05-e88a-4e75-bc34-627eace39b39.png)
> 
> Is there anything else we can check to figure out why this is happening?
> 
> Here is another video that I have seen this happen in and you can access it easily for testing. It's from another repo I was looking at before I found yours. https://github.com/saimj7/People-Counting-in-Real-Time/tree/master/videos

@mlongoria1 Have you resolved this issue? I have the same issue.
