### ISSUE TITLE
Using yolov5-seg to improve Reid

### ISSUE THREAD

**Issue by ozayr** [mikel-brostrom/Yolov5_StrongSORT_OSNet#630]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar enhancement requests.

### Description

Hi, I would like to know if theoretically using segmentation to mask the objects of surroundings before passing it into the Reid network could improve the mot metrics especially in scenarios where objects overlap with each other. I'm not aware of how exactly the Reid captures the embedding from the specific object. I have seen cases where the objects I'm trying to detect and ID end being inside other object bounding boxes. 

### Use case

theoretically improve Reid embedding extraction

**Comment by mikel-brostrom** [comment]
> I'm not aware of how exactly the Reid captures the embedding from the specific object

It just cuts out the detected objects by their respective bboxes. These bboxes are then passed to the ReID model

> I would like to know if theoretically using segmentation to mask the objects of surroundings before passing it into the Reid network

The segmentation could be used to cut out the rest of the information. By doing so, two objects would never be mixed under the same bbox

**Comment by ozayr** [comment]
> I'm not aware of how exactly the Reid captures the embedding from the specific object

My confusion here was that I'm not sure if the model was trained to focus on the object, if it was then the surrounding info would not matter hence removing it also would not make a difference.

> The segmentation could be used to cut out the rest of the information. By doing so, two objects would never be mixed under the same bbox

so this will definitely produce more unique embeddings. 

Thanks for the speedy reply, cannot thank enough for the amazing work!
