### ISSUE TITLE
Can I know the bug fixes when going from v5.0 to v6.0?

### ISSUE THREAD

**Issue by youngjae-avikus** [mikel-brostrom/Yolov5_StrongSORT_OSNet#635]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I'm currently following Deepsort, but when it overlaps, I got id-sw and found that an allocation error occurred in the cost_matrix calculation below

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/bd27fadf1c34b08d5f04c6e3894e4af5ea360d7f/deep_sort/sort/nn_matching.py#L163

Is there any bug I miss like this?

**Comment by mikel-brostrom** [comment]
Sorry, I don't understand what you mean. ID switches happens. This is not a solved field.

**Comment by youngjae-avikus** [comment]
@mikel-brostrom 

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/7f2957ec34231cc7c09562236228ec5c2b891089/trackers/strong_sort/sort/nn_matching.py#L161

You have assigned cost_matrix row to the master bracnch now, so I think there was a code (v5.0) problem here

**Comment by mikel-brostrom** [comment]
Ahaa, yes this was a bug under this release. Sorry for the inconvenience
