### ISSUE TITLE
Not able to do inference about last git pull

### ISSUE THREAD

**Issue by ChrisRawstone** [mikel-brostrom/Yolov5_StrongSORT_OSNet#636]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi I just updated my repo, with the latest push, however I am not able to do inference anymore as I get this message.

I only pulled in strongsort github, should git pull for yolov5 as well?

Sorry if these questions are obvious.

![image](https://user-images.githubusercontent.com/52676332/206261205-008d27a5-751d-4b8c-8b82-d9ba5bcdfe6a.png)

**Comment by ChrisRawstone** [comment]
If it is the case that I need to update the yolov5 repo. Can you tell what command I need to do, since It will not let me pull the normal when I am the yolov5 folder.

![image](https://user-images.githubusercontent.com/52676332/206264976-2fd07897-d12c-467d-9444-a57bdcb631cf.png)

**Comment by mikel-brostrom** [comment]
`cd yolov5` and `git checkout 7398d2d`

**Comment by mikel-brostrom** [comment]
Instead of the last command you could also run `git pull --recurse-submodules`
