### ISSUE TITLE
Track objects of the same shape and color

### ISSUE THREAD

**Issue by collonia00** [mikel-brostrom/Yolov5_StrongSORT_OSNet#638]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello. Thank you for your work.

I'm trying to keep track of cups with balls in a frontal view "Cups and Balls game". The three problems I face are: 1. The cups are all the same shape and color; 2. In the process of mixing the cups, one cup occludes 100% of the other cup for a while (because the video I shoot is looking at the cup from the front); 3. In the video, a cup that is not used in the game is filmed together.
(An example image is below.)

I detect almost 100% of cups as bounding boxes through yolo v5 training. I tried tracking with your code using my yolo v5 weight and osnet_x0_25_market1501.pt but my cups are not tracking well. The bounding box being tracked is confused with the cups behind it.

At this point, there are three questions.

1. Is creating a new Reid model for cups of the same shape significant to improve the performance of tracking?

2. Is it possible to track only a specific class among many classes and only detect the rest?

3. Is it possible to track only a specific object (the id of the cup with the ball) in the same class?

![cups and balls](https://user-images.githubusercontent.com/120391956/207064458-305aa3ec-2ced-481b-97ab-dc253ec4daf0.png)

**Comment by mikel-brostrom** [comment]
> Is creating a new Reid model for cups of the same shape significant to improve the performance of tracking?

It feels like this would make much of a difference.

> Is it possible to track only a specific class among many classes and only detect the rest?

Yes, for tracking class 1 only: `python track.py --classes 1`

> Is it possible to track only a specific object (the id of the cup with the ball) in the same class?

Not out of the box, you will need to implement it yourself

> one cup occludes 100% of the other cup for a while (because the video I shoot is looking at the cup from the front)

You could try: `pyhton track.py --save-trajectories` for visualizing the predictions when objects are occluded

**Comment by collonia00** [comment]
I admire your kindness. I'll try again.
