### ISSUE TITLE
Running Tracking seperately from the detector.

### ISSUE THREAD

**Issue by PiDGMT** [mikel-brostrom/Yolov5_StrongSORT_OSNet#640]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi, I want to run the object detection on a device that cannot also handle a tracker. I want to use the results of the yolo detections (eg. bboxes, images, bboxes) and run the tracker on this data on another device. Is this doable within this repo? What inputs do I need to feed to the detector? 
Thanks!

**Comment by mikel-brostrom** [comment]
> Hi, I want to run the object detection on a device that cannot also handle a tracker

Select one of lightweight trackers: ByteTrack or OCSORT. They are CPU only.

> and run the tracker on this data on another device. Is this doable within this repo?

It is not possible at the moment to load detections into the trackers

**Comment by PiDGMT** [comment]
Thanks! Loading the detections into the tracker worked for me.

I ran the yolo detect.py on a video and saved the output (detections and images) and used this as an input for the Strongsort.update() and got the same results as running track.py on the same video, aside from some single pixel differences in bbox locations

**Comment by mikel-brostrom** [comment]
Feel free to submit a PR for the detections loading :smile:

**Comment by PiDGMT** [comment]
I will. I'm trying to figure out how to save the yolo output more efficienty, as saving the frames as a numpy arrays is very big in file size.

**Comment by mikel-brostrom** [comment]
> as saving the frames as a numpy arrays is very big in file size.

Do you need to? Can you just feed the original video + the detections from a `.txt?`

**Comment by songjiahao-wq** [comment]
Is there any update
