### ISSUE TITLE
The visualization bounding boxes for bytetrack is not correct.

### ISSUE THREAD

**Issue by JiahaoXia** [mikel-brostrom/Yolov5_StrongSORT_OSNet#641]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Please find the attached traffic video, you can find the bounding boxes are not that accurate somehow. The detection result of yolov5 is good, so i guess it is related to the bytetrack part.

https://drive.google.com/file/d/1FkIXzpKqlaB-pP1J8klzHjPL0Bu8O1r1/view?usp=sharing

**Comment by mikel-brostrom** [comment]
ByteTrack is taken directly from its original implementation (https://github.com/ifzhang/ByteTrack). We made some minor modification so that each track store its conf and id. This is a question for the original repository.

**Comment by lhfabc9** [comment]
> ### 询问前搜索
> * [x] 我已经搜索了Yolov5_StrongSORT_OSNet[问题](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues)，没有发现类似的错误报告。
> 
> ### 问题
> 请找到随附的交通视频，您会发现边界框不知何故并不那么准确。yolov5的检测结果很好，所以我想它与字节轨道部分有关。
> 
> https://drive.google.com/file/d/1FkIXzpKqlaB-pP1J8klzHjPL0Bu8O1r1/view?usp=sharing

Hello, have you solved this problem later?
