### ISSUE TITLE
How to use with yolo-seg

### ISSUE THREAD

**Issue by TingTingin** [mikel-brostrom/Yolov5_StrongSORT_OSNet#643]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Cant figure out how to use with the yolo segmentation models when I change to a segmentation model it barely detects anything dont know what code needs to be changed to support them properly

**Comment by mikel-brostrom** [comment]
We are working on this. It will hopefully be released before the end of the year 🚀

**Comment by mikel-brostrom** [comment]
This feature is now available. Try: `python track_val.py`
