### ISSUE TITLE
track.py doesn't produce any output

### ISSUE THREAD

**Issue by danielsabinasz** [mikel-brostrom/Yolov5_StrongSORT_OSNet#647]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello!

With the latest repository version, I run the following command:

python track.py --yolo-weights ../my_custom_yolo_weights_from_custom_dataset.pt --classes 0 1 --source my_video.mp4

In effect, a directory is created at runs/track/exp, but that directory is empty!

This is confusing to me, given that the output of running the above Python command doesn't seem to report a severe error that suggests that running the command was not successful (see the attached file for the output). Only a few frames yield an "ecc transform failed" error.

Yolo itself tags the bounding boxes just fine when running it in isolation.

Any ideas?

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/d3e687ba37d163b00cf6f7aa98b0cc8d86060c9c/track.py#L305

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/d3e687ba37d163b00cf6f7aa98b0cc8d86060c9c/track.py#L310

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/d3e687ba37d163b00cf6f7aa98b0cc8d86060c9c/track.py#L306
