### ISSUE TITLE
Any Suggestions on a productive labeling tool for custom dataset evaluation ?

### ISSUE THREAD

**Issue by ozayr** [mikel-brostrom/Yolov5_StrongSORT_OSNet#649]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Looking for any suggestions for a labeling tool that allows one to label a custom dataset which can then be used to evaluate against. Something that allows AI assisted labeling as well as assigning IDs.

**Comment by mikel-brostrom** [comment]
I would recommend that you use any existing SOTA tracking solution for generating tracking GT and then refine it manually. Not sure about which tool would be the best for custom tracking annotations, but checl: https://github.com/taivop/awesome-data-annotation
