### ISSUE TITLE
Use TensorRT Without using Pytorch

### ISSUE THREAD

**Issue by yamiefun** [mikel-brostrom/Yolov5_StrongSORT_OSNet#659]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Is there any example of using feature model in TensorRT with no need of pytorch?

Thanks very much.

**Comment by mikel-brostrom** [comment]
Not in this repo. But there are good resources out there. https://github.com/cyrusbehr/tensorrt-cpp-api,
