### ISSUE TITLE
Classes not in txt output

### ISSUE THREAD

**Issue by 0akGr0ve** [mikel-brostrom/Yolov5_StrongSORT_OSNet#661]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I noticed that the —save-txt output doesn’t contain the class number. I’ve tried using the —save-conf and —save-trajectories but to no avail. It does affect the output video though which is neat, but it’d be nice to have it be represented in the actual text file. Am I overlooking something here?

**Comment by mikel-brostrom** [comment]
Just change:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/4a0819c5a5f693f9d127011be52dcaa527611ef6/track.py#L231

to

`bbox_top, bbox_w, bbox_h, cls, -1, -1, i)) `

**Comment by OakGroove** [comment]
It worked. Thank you.
