### ISSUE TITLE
save crops from every source

### ISSUE THREAD

**Issue by spinxi** [mikel-brostrom/Yolov5_StrongSORT_OSNet#665]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I have 2 source RTSP cameras,
When I run it on --save-vid or --save-crop... it saves from only first camera, how can I handle it to save from both sources?

**Comment by mikel-brostrom** [comment]
Sorry cannot reproduce. My results on two streams (webcam + YT video):

![Screenshot from 2022-12-27 13-29-19](https://user-images.githubusercontent.com/18719680/209666892-da63c59f-693c-4244-b027-8ae3e50cd76d.png)
2.png)

All the crops are ordered by source, class name and their respective ID.
Videos are saved as well.

Command used:

`python3 track.py --source source.txt --save-trajectories --save-crop`
