### ISSUE TITLE
When I draw a motion path with multi-camera, the objects with the same ID number are connected by a line, is there a solution?

### ISSUE THREAD

**Issue by caramelpop** [mikel-brostrom/Yolov5_StrongSORT_OSNet#668]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello.

As shown in the figure below, 
the motion paths of camera 0 [1 keyboard] and camera 1 [1 tv], camera 0 [2 tv] and camera 1 [2 keyboard] are connected.
(The center points are connected.)

![0](https://user-images.githubusercontent.com/92441447/209658832-22022528-16f3-43e7-8bfd-2a1ec0d09947.png)
・camera0

![1](https://user-images.githubusercontent.com/92441447/209658850-a0482a31-54f6-4350-aad9-0444b4b98868.png)
・camera1

モーションパスは#221を参考にしました。(https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues/221)

Is there any way to resolve this?

Thank you for your cooperation.

**Comment by mikel-brostrom** [comment]
Sorry, cannot reproduce. Just tried this on separate sources and there are no issues with trajectories being mixed up between sources.

**Comment by caramelpop** [comment]
I was using zip data from 4 months ago and did not realize that they had changed a lot of things.

When I downloaded the latest zip data, I could not install the 'lap' module, so I will report again when I can!

Thanks.

**Comment by caramelpop** [comment]
I tried with the latest file and motion path was connected.

![3](https://user-images.githubusercontent.com/92441447/209963308-8bc1d4b9-51a5-4b5b-979b-a9109fa3d31d.png)
・camera0

![2](https://user-images.githubusercontent.com/92441447/209963351-b2f309af-700e-4db6-9902-8e0b9012ae46.png)
・camera1

It seems to be occurring especially at runtime.
(ID number is 1 or 2, etc.).

If there is motion in the camera image, the incidence will be lower because the ID number will advance.


The only additions I have made are the following.

    from collections import deque
    pts = [deque(maxlen=30) for _ in range(9999)]

        center = (int(((output[0]) + (output[2]))/2) , int(((output[1]) + (output[3]))/2))
        pts[id].append(center)
        cv2.circle(im0 ,  (center), 1, color=colors(c, True), thickness=5)
        for k in range(1, len(pts[id])):
            if pts[id][k - 1] is None or pts[id][k] is None:
                continue
            cv2.line(im0 , (pts[id][k-1]) , (pts[id][k]) , color=colors(c, True) , thickness=3)

**Comment by mikel-brostrom** [comment]
Sorry we don't support custom modifications of this repo

**Comment by mikel-brostrom** [comment]
I you want to show trajectories in real-time use:

`python track.py --save-trajectories`

**Comment by caramelpop** [comment]
Thank you very much.

--save-trajectories : I didn't know this feature existed.

Problem solved.

Thank you.

**Comment by WestbrookZero** [comment]
> I tried with the latest file and motion path was connected.
> 
> ![3](https://user-images.githubusercontent.com/92441447/209963308-8bc1d4b9-51a5-4b5b-979b-a9109fa3d31d.png) ・camera0
> 
> ![2](https://user-images.githubusercontent.com/92441447/209963351-b2f309af-700e-4db6-9902-8e0b9012ae46.png) ・camera1
> 
> It seems to be occurring especially at runtime. (ID number is 1 or 2, etc.).
> 
> If there is motion in the camera image, the incidence will be lower because the ID number will advance.
> 
> The only additions I have made are the following.
> 
> ```
> from collections import deque
> pts = [deque(maxlen=30) for _ in range(9999)]
> 
>     center = (int(((output[0]) + (output[2]))/2) , int(((output[1]) + (output[3]))/2))
>     pts[id].append(center)
>     cv2.circle(im0 ,  (center), 1, color=colors(c, True), thickness=5)
>     for k in range(1, len(pts[id])):
>         if pts[id][k - 1] is None or pts[id][k] is None:
>             continue
>         cv2.line(im0 , (pts[id][k-1]) , (pts[id][k]) , color=colors(c, True) , thickness=3)
> ```


pts[id].append(center)
TypeError: list indices must be integers or slices, not numpy.float64

How can I solve it?
