### ISSUE TITLE
Error when running track.run

### ISSUE THREAD

**Issue by OakGroove** [mikel-brostrom/Yolov5_StrongSORT_OSNet#676]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

Getting the following error:

`Traceback (most recent call last):   File "c:/Users/user/Desktop/notebook/DeepSort_brostrom/Yolov5_StrongSORT_OSNet/inference_workflow.py", line 6, in <module>     track.run(source = vid_path, yolo_weights=pt)   File "C:\Users\user\.conda\envs\ds-b-sys\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context     return func(*args, **kwargs)   File "c:\Users\user\Desktop\notebook\DeepSort_brostrom\Yolov5_StrongSORT_OSNet\track.py", line 87, in run     exp_name = yolo_weights.stem AttributeError: 'str' object has no attribute 'stem'`

Happens when I’m trying to run track.py as a command within a python script. Like so:

`
import track

vid_path = r'C:/Users/user/Desktop/notebook/DeepSort_brostrom/Yolov5_StrongSORT_OSNet/videos/sm_mot_test_trim1.mp4' 
pt = r'C:/Users/user/Desktop/notebook/DeepSort_brostrom/Yolov5_StrongSORT_OSNet/yolov5/models/last.pt'
 
track.run(source = vid_path, yolo_weights=pt)
`

It looks like it’s reading in the weight file as a string rather than as a .pt file. This error does not show when I run the regular “python track.py” command in the command line. Is there a work around to this?

**Comment by mikel-brostrom** [comment]
Sorry, we don't support custom modifications of the code.

**Comment by OakGroove** [comment]
Ah, sorry it’s not so much as a modification to the code as it is running it in a python script rather than the command line. As I mentioned I can run the command regularly on the command line without any issue, but when I use track.run() within a script I get an error. I’ll try to better show what I’m trying to do later when I have access to my computer.

**Comment by OakGroove** [comment]
Ok, so I can write the following command in the command line and the process will run fine. 
![image](https://user-images.githubusercontent.com/93164738/210803656-5232a389-8df9-4037-bf6b-8256aee430c0.png)

But if I write the equivalent command within a python script like below, I get the error in the original comment.
![image](https://user-images.githubusercontent.com/93164738/210807028-e4cc3f79-377e-456e-8b41-7b24be004273.png)

Nothing about track.py has been changed/modified. As mentioned, my closest guess is that somewhere within track.py, the path to the yolo weight file is being mishandled or just plainly not being read correctly, but I'm not so sure how,

**Comment by mikel-brostrom** [comment]
```python
import track
from pathlib import Path

video_path = Path(...)
pt = Path(...)

track.run(source = video_path, yolo_weights=pt)
```

**Comment by OakGroove** [comment]
Yep that worked. Thanks a bunch. I'll marked as closed, but I did notice something else that might be worth looking at. When I pass a video path that is in a nested directory structure, I'd get an error saying that the file didn't exist (I did make sure that I wrote the path correctly). This happened when running the command on the command line, perhaps the path was too long?
