### ISSUE TITLE
可以在track.py中可视化移动目标的速度吗？

### ISSUE THREAD

**Issue by computer-vision666** [mikel-brostrom/Yolov5_StrongSORT_OSNet#677]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

可以在track.py中可视化移动目标的速度吗？怎么在track.py中修改代码

**Comment by mikel-brostrom** [comment]
> 可以在track.py中可视化移动目标的速度吗？

For this you need to have information related to you deployment scenario. It is nothing we offer out-of-the-box.
