### ISSUE TITLE
How to train own model

### ISSUE THREAD

**Issue by Chengyunlai** [mikel-brostrom/Yolov5_StrongSORT_OSNet#679]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi, I recently had a job on object tracking.I didn't have much experience before. I want to train my own model on the dataset. What should I do? Thanks

**Comment by mikel-brostrom** [comment]
Check `tutorials` under: https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet#installation
