### ISSUE TITLE
--vid-stride does not work

### ISSUE THREAD

**Issue by FFsvip** [mikel-brostrom/Yolov5_StrongSORT_OSNet#681]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

--vid-stride does not work

**Comment by mikel-brostrom** [comment]
Should be working now for `LoadImages` dataloader as well
