### ISSUE TITLE
How to save single crop per ID

### ISSUE THREAD

**Issue by Swalii** [mikel-brostrom/Yolov5_StrongSORT_OSNet#683]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

 I am grateful for this incredible work . I have a custom YOLOv5 model that has been trained for detection of vehicle license plates and it is working perfectly for object detection. My goal now is to track the vehicles and save a unique image of the object as soon as the confidence score reaches a certain threshold, from a RTSP video stream. I am currently exploring different options on how to achieve this, and then using the unique image for OCR (I have already implemented OCR functionality). Can you guide me on how to accomplish this task?
 
`python3 track.py --yolo-weights /eu-data/EU-License-Plate-Public.pt --source /VID_20230105_110034.mp4 --show-vid --conf-thres 0.8 --iou-thres 0.2 --max-det 2 --vid-stride 10 --save-trajectories`

`--save-crop` option is throwing a error which I have already asked in a different issue but sharing here just in case its relevant 

```
 File "/Users/Documents/Workspace/Yolov5_StrongSORT_OSNet/track.py", line 344, in <module>
    main(opt)
  File "/Users/Documents/Workspace/Yolov5_StrongSORT_OSNet/track.py", line 339, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/Documents/Workspace/Yolov5_StrongSORT_OSNet/track.py", line 246, in run
    save_one_box(bbox.astype(np.int16), imc, file=save_dir / 'crops' / txt_file_name / names[c] / f'{id}' / f'{p.stem}.jpg', BGR=True)
AttributeError: 'list' object has no attribute 'astype'


```

**Comment by mikel-brostrom** [comment]
I just run `track.py` with `--save-crop` and get that `print(type(bbox))` gives `<class 'numpy.ndarray'>`

**Comment by Swalii** [comment]
Thanks for the reply , I am getting error with -`-save-crop `

`AttributeError: 'list' object has no attribute 'astype'`

**Comment by mikel-brostrom** [comment]
What I mean is that I don't understand how you can get type `list`. Have you made any custom modifications?

**Comment by Swalii** [comment]
there is no custom modifications 
```
Yolov5_StrongSORT_OSNet test$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

```
even running with default yolo weights exe `yolov5n.pt` I am getting the same error , I can share the weight file and video which I am testing .

**Comment by mikel-brostrom** [comment]
`git pull` should be fixed now

**Comment by Swalii** [comment]
@mikel-brostrom  Thank you for your contribution and resolving the issue. It is now functioning properly. Can you please provide more clarification on your comment regarding identifying unique objects, specifically with the use of print(type(bbox)) and any examples? Also, during tracking, 

if an object is present in the frame for 10 seconds, I am getting multiple copies of the same object when using save-crop. I am trying to extract unique objects based on class and confidence threshold. Please let me know if I have missed anything obvious. Apologies for any confusion.

**Comment by mikel-brostrom** [comment]
A simple solution would be to store the IDs of saved crops in a list
