### ISSUE TITLE
How to change trajectories length?

### ISSUE THREAD

**Issue by buyi6666** [mikel-brostrom/Yolov5_StrongSORT_OSNet#686]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi，
When I want to save trajectories, but the trajectories are not displayed from beginning to end.
![111](https://user-images.githubusercontent.com/102564895/211751936-803f000b-ee4c-4a5d-9785-8638d9e8d4bb.png)
![222](https://user-images.githubusercontent.com/102564895/211751965-e6614baf-5d54-40b0-a653-e0cfd01b37d9.png)
It looks like a tail. It seems that the track has length limit.

**Comment by mikel-brostrom** [comment]
Change the queue length here:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/ce5a7c37c98ed8c8add7e1fa850d4378390e488e/trackers/strongsort/sort/track.py#L95

**Comment by buyi6666** [comment]
Thank you very much！！！

**Comment by ChenShupan** [comment]
How should I use this code?

**Comment by ChenShupan** [comment]
> 非常感谢！！！

Hello, has the problem of trajectory length been solved?

**Comment by buyi6666** [comment]
> > 非常感谢！！！
> 
> Hello, has the problem of trajectory length been solved?

yes，look at this reply.

Change the queue length here:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/ce5a7c37c98ed8c8add7e1fa850d4378390e488e/trackers/strongsort/sort/track.py#L95

**Comment by ChenShupan** [comment]
> > > 非常感谢！！！
> > 
> > 
> > 你好，轨迹长度的问题解决了吗？
> 
> 是的，看看这个回复。
> 
> 在此处更改队列长度：
> 
> https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/ce5a7c37c98ed8c8add7e1fa850d4378390e488e/trackers/strongsort/sort/track.py#L95

I found it. Thank you very much.

**Comment by buyi6666** [comment]
> > > > > 非常感谢！！！
> > > > 
> > > > 
> > > > 你好，轨道长度的问题解决了吗？
> > > 
> > > 
> > > 是的，看这个回复。
> > > 在此处更改队伍长度：
> > > https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/ce5a7c37c98ed8c8add7e1fa850d4378390e488e/trackers/strongsort/sort/track.py#L95
> > 
> > 我找到了。非常感谢。
> How to give different colors to the trajectories generated by different objects?
> Have you ever encountered such a problem?

yes, you can try to search for the  module about `color`.

**Comment by ChenShupan** [comment]
> 

I will try.
