### ISSUE TITLE
Is there any way to apply ROI to the entire model, not just when displaying the result?

### ISSUE THREAD

**Issue by aerenkaradag** [mikel-brostrom/Yolov5_StrongSORT_OSNet#687]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Is there any way to apply ROI (region of interest) to source (for both the prediction(yolo) model and the tracking model)?

i can capable to set borders of roi with this code lines:
```
# Create ROI 
cap = cv2.VideoCapture(source)
frame = cap.read()
frame = imutils.resize(frame[1], width=960, height=540)

if roi is not False:
    roi = cv2.selectROI(frame,showCrosshair=False)
    cv2.destroyWindow('ROI selector')        
else:
    print("[INFO] roi not requested")
cap.release()
```
However, using this adjusted roi like this(the following line) only affects the display output (Stream results in --show-vid option) and the model keeps looking at the whole picture:
```
for frame_idx, (path, im, im0s, vid_cap, s) in enumerate(dataset):
    im0s=im0s[int(roi[1]):int(roi[1])+int(roi[3]),int(roi[0]):int(roi[0])+int(roi[2])]
```
when i did the same also for 'im' i got this error: 

>   File "C:\Python310\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Python310\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [48, 12, 3, 3], expected input[1, 0, 0, 320] to have 12 channels, but got 0 channels instead

when i did the same also for 'im0' i got this error: 

>   File "D:\Yolov5_StrongSORT_OSNet\track.py", line 218, in run
    det[:, :4] = scale_boxes(im.shape[2:], det[:, :4], im0.shape).round()  # rescale boxes to im0 size
  File "C:\Python310\lib\site-packages\yolov5\utils\general.py", line 794, in scale_boxes
    gain = min(img1_shape[0] / img0_shape[0], img1_shape[1] / img0_shape[1])  # gain  = old / new
ZeroDivisionError: division by zero

I also tried to directly edit the LoadStreams in the yolov5/utils/dataloaders.py but i couldn't figure out. How can I implement ROI to whole system before or after the video/stream loaded? Do you have any suggestions?

**Comment by mikel-brostrom** [comment]
Crop the ROI in the dataloader by

`im = im[y1:y2, x1:x2]`

before return

**Comment by aerenkaradag** [comment]
Thank you Mikel it works now when added after `cap.retrieve()`. Also, appreciate for this awesome repo!
